import { useAtlasMetadata } from '../../hooks/useAtlasMetadata'
import AsPontesLocal from './AsPontesLocal'
import { useState } from 'react'
import { asPontesPublication } from '../../data/asPontesResearch'
import { AtlasCandidateHero,AtlasLanguageSelector,AtlasLocaleProvider,AtlasCandidateNav,AtlasDataTable,AtlasDemandLadder,AtlasDossierCTA,AtlasEvidenceBadge,AtlasScorecard,AtlasSection,AtlasWarning } from '../../components/atlas/AtlasPrimitives'

const dossier='/media/albedo-industries/atlas-as-pontes-gate-1-research-report.pdf'
const nav=[{id:'overview',label:'Overview'},{id:'decision',label:'Decision'},{id:'power',label:'Power'},{id:'land',label:'Land'},{id:'fiber',label:'Fiber'},{id:'validation',label:'Validation'},{id:'demand',label:'Demand'},{id:'risks',label:'Risks'},{id:'updates',label:'Updates'}]
const scores=['Power','Fiber','Land','Water / Cooling','Climate','Construction','Regulation','Customer Demand','Community','Competition','Capital'].map(dimension=>({dimension,note:'Candidate-specific comparable score has not yet been published.'}))
export default function AsPontesCandidatePage(){
 const [locale,setLocale]=useState<'en'|'es'|'pt'|'fi'>('en')
 useAtlasMetadata({name:'As Pontes',country:'Spain',description:'An evidence-led Project Atlas Gate 1 assessment of As Pontes, Spain. Atlas continues research while grid capacity, land control and operator demand remain unverified.',route:'/infrastructure/spain/as-pontes'})
 if(locale==='es')return <AsPontesLocal locale={locale} setLocale={setLocale}/>
 return <AtlasLocaleProvider locale="en"><div lang="en" className="bg-white text-zinc-950"><AtlasCandidateHero languageControl={<AtlasLanguageSelector locale={locale} localCode="es" onChange={setLocale}/>} country="Spain" name="As Pontes" id="EU-ES-01" gate="Gate 1" status="CONTINUE RESEARCHING" date="August 2026" researchState="Published research · active validation" assessment="As Pontes has a credible post-coal industrial and energy thesis, but its demand-side connection, controllable land and customer demand are not yet demonstrated." blocker="Available demand-side grid capacity and a connection route are unverified." dossier={dossier}/><AtlasCandidateNav items={nav}/>
 <AtlasSection number="02" title="Executive Assessment"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[['Why this location?','Industrial energy legacy and formal just-transition context.','CONFIRMED'],['What the evidence says','The regional thesis is real; development access is not proven.','INDICATED'],['Primary blocker','No written large-load connection pathway.','BLOCKER'],['Atlas position','Continue research without beginning development.','CONFIRMED']].map(x=><article className="rounded-2xl border p-6" key={x[0]}><AtlasEvidenceBadge status={x[2] as 'CONFIRMED'}/><h3 className="mt-5 font-semibold">{x[0]}</h3><p className="mt-3 text-sm text-zinc-600">{x[1]}</p></article>)}</div></AtlasSection>
 <AtlasSection id="decision" number="03" title="Gate Decision"><div className="rounded-3xl bg-zinc-950 p-8 text-white"><p className="text-sm font-bold text-sky-200">CONTINUE RESEARCHING</p><h3 className="mt-4 text-3xl font-semibold">Prove the connection before development.</h3><p className="mt-5 max-w-3xl text-zinc-300">Former generation and nearby transmission establish context, not available demand capacity. Atlas has no secured parcel, permit, grid allocation or customer commitment.</p><p className="mt-6 border-l-2 border-amber-300 pl-5 text-xl">A good location is not necessarily an Atlas opportunity.</p><div className="mt-8"><AtlasDossierCTA candidate="As Pontes" href={dossier} invert/></div></div></AtlasSection>
 <AtlasSection number="04" title="Candidate Scorecard"><AtlasScorecard scores={scores}/></AtlasSection>
 <AtlasSection id="power" number="05" title="Power & Grid Validation"><AtlasWarning title="AVAILABLE MW NOT VERIFIED">The former 1,403.5 MW thermal plant and 400 kV context do not establish capacity, connection cost, reinforcements, timing or permits for a new large load.</AtlasWarning><div className="mt-8 grid gap-4 md:grid-cols-3"><Fact title="Verified context" text="Four coal units closed definitively; high-voltage infrastructure exists in the area."/><Fact title="Evidence required" text="A written connection study for a defined load and real parcel."/><Fact title="Gate effect" text="No credible demand connection route would stop progression."/></div></AtlasSection>
 <AtlasSection id="land" number="06" title="Land Parcel Investigation"><AtlasDataTable headers={['Question','Current evidence','Next action']} rows={[["Is a compliant parcel controllable?",'No parcel, land control or development agreement is identified.','Screen ownership, zoning, easements, ground and environmental constraints.'],['Can industrial legacy become a site?','Regional industrial context only.','Obtain parcel-specific planning evidence.']]}/></AtlasSection>
 <AtlasSection id="fiber" number="07" title="Fiber, Cooling & Local Infrastructure"><div className="grid gap-4 md:grid-cols-2"><Fact title="Fiber diversity" text="Candidate-specific physically diverse routes remain unverified."/><Fact title="Cooling" text="The restored mine lake is environmental context, not a verified cooling-water right."/></div></AtlasSection>
 <AtlasSection id="validation" number="08" title="Active Validation Work"><ol className="grid gap-4 md:grid-cols-2">{['Request written grid route, capacity, reinforcement, cost and timing evidence.','Investigate specific parcels and planning compatibility.','Validate diverse fiber and a low-water cooling concept.','Record government, municipality and operator engagement as dated evidence.'].map((x,i)=><li className="rounded-2xl border p-6" key={x}><span className="text-xs text-zinc-400">0{i+1}</span><p className="mt-3 text-sm">{x}</p></li>)}</ol></AtlasSection>
 <AtlasSection id="demand" number="09" title="Operator Interest"><AtlasDemandLadder level={0} note="NO OPERATOR DEMAND VALIDATED"/></AtlasSection>
 <AtlasSection id="risks" number="10" title="Risks & Critical Unknowns"><AtlasDataTable headers={['Risk','Evidence','Consequence','Response']} rows={[["Grid thesis failure",<AtlasEvidenceBadge status="BLOCKER"/>,'No credible connection route stops progression.','Written connection study'],['Uncontrolled land',<AtlasEvidenceBadge status="UNVERIFIED"/>,'Industrial context may not yield a compliant parcel.','Parcel diligence'],['No customer evidence',<AtlasEvidenceBadge status="UNKNOWN"/>,'No commercial case.','Structured operator validation']]}/></AtlasSection>
 <AtlasSection id="updates" number="11" title="Latest Validation Updates"><article className="rounded-2xl border p-6"><time className="text-xs text-zinc-400">4 August 2026</time><h3 className="mt-2 font-semibold">Evidence review published</h3><p className="mt-3 text-sm text-zinc-600">Primary-source regional context was separated from unresolved site, grid, fiber, cooling and demand evidence.</p></article><details className="mt-8 rounded-2xl border p-6"><summary className="cursor-pointer font-semibold">Reviewed source register</summary><ul className="mt-5 space-y-3 text-sm text-zinc-600">{asPontesPublication.sources.map(s=><li key={s.id}>{s.id} · {s.title} — {s.publisher}</li>)}</ul></details><div className="mt-8"><AtlasDossierCTA candidate="As Pontes" href={dossier}/></div></AtlasSection>
 </div></AtlasLocaleProvider>}
function Fact({title,text}:{title:string;text:string}){return <article className="rounded-2xl border p-6"><h3 className="font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-zinc-600">{text}</p></article>}
