import { useState } from 'react'
import { Link } from 'react-router-dom'
import { AtlasLanguageSelector, AtlasLocaleProvider } from '../../components/atlas/AtlasPrimitives'
import { useAtlasMetadata } from '../../hooks/useAtlasMetadata'

const dossier='/media/albedo-industries/Project_Atlas_Canelones_Gate1_Dossier_v1.1.pdf'
const mailto='mailto:alex@albedo-industries.com?subject=Project%20Atlas%20%E2%80%94%20Canelones%20investment%20or%20partnership&body=Hello%20Project%20Atlas%2C%0A%0AI%20am%20contacting%20you%20as%3A%20investor%20%2F%20operator%20or%20customer%20%2F%20energy%20or%20fibre%20partner%20%2F%20land%20or%20development%20partner%20%2F%20public%20or%20institutional%20stakeholder%20%2F%20other.%0A%0AName%3A%0AOrganization%3A%0AMessage%3A'
const copy={
es:{back:'Project Atlas',sub:'Una oportunidad emergente para infraestructura de IA de 10–25 MW, respaldada por un ecosistema digital real y pendiente de validación directa con UTE.',status:'CONTINUAR VALIDACIÓN',download:'Descargar dossier completo',discuss:'Hablar sobre inversión o colaboración',honesty:'Atlas no tiene potencia reservada, parcela controlada, cliente ni financiación comprometida en Canelones.',snapshot:'Resumen de la oportunidad',why:'Por qué Canelones',corridors:'Tres corredores bajo evaluación',verifiedOpen:'Lo verificado y lo que sigue abierto',verified:'Verificado',open:'Pendiente de validar',path:'Ruta de desarrollo',cta:'Ayuda a validar y avanzar Canelones.',ctaBody:'Atlas busca interlocución con inversores, operadores de centros de datos, empresas de IA, proveedores de energía y fibra, propietarios de suelo y socios técnicos.',finalDownload:'Descargar dossier de Gate 1',legal:'Oportunidad en fase de investigación · se requiere validación independiente. Las manifestaciones de interés no son vinculantes y esta web no ofrece valores ni acepta fondos.'},
en:{back:'Project Atlas',sub:'An emerging 10–25 MW AI-infrastructure opportunity supported by a real digital ecosystem and awaiting direct validation with UTE.',status:'CONTINUE VALIDATION',download:'Download full dossier',discuss:'Discuss investment or partnership',honesty:'Atlas has not secured power, land, customers or committed financing in Canelones.',snapshot:'Opportunity snapshot',why:'Why Canelones',corridors:'Three corridors under assessment',verifiedOpen:'What is verified and what remains open',verified:'Verified',open:'Still to validate',path:'Development pathway',cta:'Help validate and advance Canelones.',ctaBody:'Atlas is seeking conversations with investors, data-centre operators, AI-compute companies, energy and fibre providers, land partners and technical developers.',finalDownload:'Download the Gate 1 dossier',legal:'Research-stage opportunity · independent validation required. Expressions of interest are non-binding; this website does not offer securities or accept funds.'}}
const content={es:{
metrics:[['10–25 MW','Capacidad IT inicial bajo evaluación.'],['Route 5','Corredor prioritario de validación.'],['91 fuentes','Evidencia registrada en el dossier de Gate 1.'],['30 días','Sprint de validación recomendado antes de revisar Gate 2.']],
why:[['Ecosistema digital probado','Google está construyendo un gran centro de datos en Canelones y Antel opera y amplía infraestructura crítica en el departamento. Esto valida el territorio, no garantiza capacidad para Atlas.'],['Corredor estratégico Route 5','Route 5 y el área Route 5/48 combinan suelo industrial, transporte y nueva evidencia de acceso estratégico a energía y conectividad. Es la prioridad para validación directa.'],['Sistema eléctrico renovable','Uruguay cuenta con una matriz muy renovable y UTE dispone de un proceso para solicitar estimaciones preliminares. La capacidad local y el coste entregado siguen sin conocerse.'],['Interlocución institucional','La Intendencia y API Canelones respondieron positivamente e identificaron Route 5, Route 101 y Pando para evaluar. Es interlocución, no aprobación.']],
corridors:[['Route 5 — Prioridad',['Suelo industrial y logístico.','Evidencia de infraestructura estratégica en Route 5/48.','Menor concentración directa junto a instalaciones hyperscale.','Capacidad UTE y diversidad de fibra pendientes.']],['Pando — Alternativa técnica',['Precedente de infraestructura crítica y centros de datos.','Ecosistema de conectividad sólido.','La proximidad a Antel valida y añade complejidad competitiva.','Parcela y capacidad residual desconocidas.']],['Route 101 — Corredor de referencia',['Google y Parque de las Ciencias validan el corredor.','Logística y conectividad sólidas.','Mayor competencia por suelo, red e infraestructura.','No es la primera prioridad de validación Atlas.']]],
verified:['Canelones alberga inversión material en centros de datos.','UTE opera un proceso formal de estimación preliminar de conexión.','Existen parques industriales y tecnológicos en los corredores evaluados.','Uruguay ofrece una matriz de generación muy renovable.','El gobierno local está abierto a continuar el diálogo.'],open:['Capacidad disponible para 10 MW y 25 MW.','Tensión, coste, obras y plazo de conexión.','Una parcela controlable de 6–10 hectáreas.','Dos rutas de fibra físicamente diversas.','Demanda de operador o cliente ancla.','Coste eléctrico entregado comercialmente competitivo.'],
steps:[['Ahora — validación Gate 1',['Reunión con actores de Canelones.','Estimación preliminar de conexión de UTE.','Lista corta de parcelas y fibra.','Contacto con operadores.']],['Después — preparación Gate 2',['Solución UTE creíble.','Parcela controlable.','Diversidad de fibra.','Interés comercial inicial.','Presupuesto preliminar de desarrollo.']],['Más adelante — desarrollo potencial',['Control de parcela.','Ingeniería y permisos.','Acuerdos con clientes.','Financiación específica del proyecto.']]]},
en:{metrics:[['10–25 MW','Initial IT capacity under assessment.'],['Route 5','Priority validation corridor.'],['91 sources','Evidence registered in the Gate 1 dossier.'],['30 days','Recommended validation sprint before Gate 2 review.']],why:[['Proven digital-infrastructure ecosystem','Google is constructing a major data centre in Canelones, while Antel operates and expands critical infrastructure in the department. This validates the territory, not capacity for Atlas.'],['Strategic Route 5 corridor','Route 5 and the Route 5/48 area combine industrial land, transport and new evidence of strategic energy and connectivity access. It is the direct-validation priority.'],['Renewable electricity system','Uruguay has a highly renewable electricity mix and UTE provides a preliminary connection-estimate process. Local capacity and delivered cost remain unknown.'],['Institutional engagement','The Intendencia and API Canelones responded positively and identified Route 5, Route 101 and Pando for assessment. This is engagement, not approval.']],corridors:[['Route 5 — Priority',['Industrial and logistics land.','Route 5/48 strategic-infrastructure evidence.','Lower direct concentration beside existing hyperscale facilities.','UTE capacity and fibre diversity still to validate.']],['Pando — Technical alternative',['Critical-infrastructure and data-centre precedent.','Strong connectivity ecosystem.','Antel proximity creates validation and competitive complexity.','Site and residual capacity unknown.']],['Route 101 — Reference corridor',['Google and Parque de las Ciencias validate the corridor.','Strong logistics and connectivity.','Greater competition for land, grid attention and infrastructure.','Not the first Atlas validation priority.']]],verified:['Canelones hosts material data-centre investment.','UTE operates a formal preliminary connection-estimate process.','Industrial and technology parks exist across the assessed corridors.','Uruguay offers a highly renewable generation mix.','The local government is open to continued discussion.'],open:['Available capacity for 10 MW and 25 MW.','Connection voltage, cost, works and delivery time.','A controllable 6–10 hectare site.','Two physically diverse fibre routes.','Operator or anchor-customer demand.','Commercially competitive delivered electricity cost.'],steps:[['Now — Gate 1 validation',['Meeting with Canelones stakeholders.','UTE preliminary connection estimate.','Site and fibre shortlist.','Operator outreach.']],['Next — Gate 2 readiness',['Credible UTE solution.','Controllable site.','Fibre diversity.','Initial commercial interest.','Preliminary development budget.']],['Later — potential project development',['Site control.','Engineering and permits.','Customer agreements.','Project-specific financing.']]]}}
export default function CanelonesCandidatePage(){const [locale,setLocale]=useState<'es'|'en'>('es');const t=copy[locale],c=content[locale];useAtlasMetadata({name:'Canelones',country:'Uruguay',description:'Independent Gate 1 assessment of Canelones as a potential 10–25 MW AI-infrastructure location. Route 5, UTE validation, industrial land, connectivity and partnership opportunities.',route:'/infrastructure/uruguay/canelones'});return <AtlasLocaleProvider locale={locale}><div lang={locale}>
<section className="bg-zinc-950 text-white"><div className="mx-auto max-w-6xl px-6 py-16 md:py-24"><div className="flex items-center justify-between gap-4"><Link to="/atlas" className="text-sm text-zinc-400">← {t.back}</Link><AtlasLanguageSelector locale={locale} localCode="es" onChange={l=>setLocale(l as 'es'|'en')}/></div><p className="mt-12 text-xs font-bold tracking-[.2em] text-amber-200">PROJECT ATLAS · URUGUAY · LATAM-UY-01</p><h1 className="mt-5 text-5xl font-semibold md:text-7xl">Canelones</h1><p className="mt-6 max-w-4xl text-xl leading-relaxed text-zinc-300">{t.sub}</p><div className="mt-7 flex flex-wrap gap-3"><span className="rounded-full border border-amber-300/50 bg-amber-300/10 px-4 py-2 text-xs font-bold">{t.status}</span><span className="rounded-full border border-white/20 px-4 py-2 text-xs font-bold">Gate 1 · Conditional Pass</span></div><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={dossier} download className="rounded-full bg-white px-6 py-3 text-center text-sm font-semibold text-zinc-950" aria-label={`${t.download} — Canelones PDF`}>{t.download}</a><a href={mailto} className="rounded-full border border-white/30 px-6 py-3 text-center text-sm font-semibold">{t.discuss}</a></div><p className="mt-8 max-w-3xl border-l border-amber-300 pl-4 text-sm text-zinc-400">{t.honesty}</p></div></section>
<Section title={t.snapshot}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{c.metrics.map(x=><Card key={x[0]} title={x[0]} body={x[1]}/>)}</div></Section>
<Section title={t.why} soft><div className="grid gap-5 md:grid-cols-2">{c.why.map(x=><Card key={x[0]} title={x[0]} body={x[1]}/>)}</div></Section>
<Section title={t.corridors}><div className="grid gap-5 lg:grid-cols-3">{c.corridors.map(x=><article className="rounded-2xl border border-zinc-200 p-6" key={x[0] as string}><h3 className="text-xl font-semibold">{x[0]}</h3><List items={x[1] as string[]}/></article>)}</div></Section>
<Section title={t.verifiedOpen} soft><div className="grid gap-6 md:grid-cols-2"><article className="rounded-2xl border border-emerald-200 bg-white p-7"><h3 className="text-2xl font-semibold">{t.verified}</h3><List items={c.verified}/></article><article className="rounded-2xl border border-amber-300 bg-white p-7"><h3 className="text-2xl font-semibold">{t.open}</h3><List items={c.open}/></article></div></Section>
<Section title={t.path}><div className="grid gap-5 md:grid-cols-3">{c.steps.map(x=><article className="rounded-2xl border border-zinc-200 p-6" key={x[0] as string}><h3 className="text-xl font-semibold">{x[0]}</h3><List items={x[1] as string[]}/></article>)}</div></Section>
<section className="bg-zinc-950 text-white"><div className="mx-auto max-w-6xl px-6 py-20 md:py-24"><h2 className="text-3xl font-semibold md:text-5xl">{t.cta}</h2><p className="mt-5 max-w-3xl text-zinc-400">{t.ctaBody}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={mailto} className="rounded-full bg-white px-6 py-3 text-center text-sm font-semibold text-zinc-950">{t.discuss}</a><a href={dossier} download className="rounded-full border border-white/30 px-6 py-3 text-center text-sm font-semibold" aria-label={`${t.finalDownload} — Canelones PDF`}>{t.finalDownload}</a></div><p className="mt-8 text-xs leading-relaxed text-zinc-500">{t.legal}</p></div></section>
</div></AtlasLocaleProvider>}
function Section({title,children,soft=false}:{title:string;children:React.ReactNode;soft?:boolean}){return <section className={`border-t border-zinc-200 ${soft?'bg-zinc-50':''}`}><div className="mx-auto max-w-6xl px-6 py-16 md:py-24"><h2 className="mb-9 text-3xl font-semibold md:text-5xl">{title}</h2>{children}</div></section>}
function Card({title,body}:{title:string;body:string}){return <article className="rounded-2xl border border-zinc-200 bg-white p-6"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-zinc-600">{body}</p></article>}
function List({items}:{items:string[]}){return <ul className="mt-5 space-y-3 text-sm text-zinc-600">{items.map(x=><li className="flex gap-3" key={x}><span aria-hidden className="text-amber-600">—</span><span>{x}</span></li>)}</ul>}
