import { useAtlasMetadata } from '../../hooks/useAtlasMetadata'
import KouvolaKotkaLocal from './KouvolaKotkaLocal'
import { useState } from 'react'
import { AtlasCandidateHero,AtlasLanguageSelector,AtlasLocaleProvider,AtlasCandidateNav,AtlasDataTable,AtlasDemandLadder,AtlasDevelopmentPathway,AtlasDossierCTA,AtlasEvidenceBadge,AtlasMetricCard,AtlasScorecard,AtlasSection,AtlasWarning } from '../../components/atlas/AtlasPrimitives'

const dossier='/media/albedo-industries/Project_Atlas_Kouvola_Kotka_Gate1_Full_Dossier.pdf'
const nav=[{id:'overview',label:'Overview'},{id:'decision',label:'Decision'},{id:'power',label:'Power'},{id:'land',label:'Land'},{id:'competition',label:'Competition'},{id:'tax',label:'Tax'},{id:'risks',label:'Risks'},{id:'lessons',label:'Lessons'},{id:'conclusion',label:'Conclusion'}]
const scores=[['Power',4,3,'Excellent national fundamentals; corridor availability unknown.'],['Fiber',4,3,'Strong ecosystem; plot diversity unverified.'],['Land',3,3,'Brownfield supply exists, but major estates are captured.'],['Water / Cooling',4,3,'Strong climate and proven techniques; rights unverified.'],['Climate',5,5,'Strong cold-climate advantage.'],['Construction',4,3,'Capable ecosystem with competing demand.'],['Regulation',2,4,'Material adverse electricity-tax change.'],['Customer Demand',2,1,'No Atlas operator demand validated.'],['Community',4,3,'Industrial and heat-reuse context is supportive.'],['Competition',2,4,'Extremely high opportunity consumption.'],['Capital',3,1,'No Atlas capital or differentiated access.']].map(x=>({dimension:x[0] as string,opportunity:x[1] as number,confidence:x[2] as number,note:x[3] as string}))
const sites=['Myllykoski','Ummeljoki','Koria','Voikkaa','Kuusankoski','Savontalo','Kotka Mussalo','Google Hamina land bank','Loviisa']
const operators=['Google Hamina','atNorth FIN04','Hyperco / Edgnex','DayOne','Novagen','Nebius / Polarnode','Verne','XTX','Nova Complex']
const risks=[['No verified available MW','Likely','Gate-blocking','BLOCKER','Do not progress without written capacity evidence'],['Southern Finland connection restrictions','Likely','Gate-blocking','CONFIRMED','No active application recommended'],['Land substantially pre-empted','Likely','Major','STRONGLY INDICATED','Do not imply site control'],['No Atlas demand','Certain','Gate-blocking','CONFIRMED','Close active origination'],['Adverse electricity taxation','Certain','Major','CONFIRMED','Re-test only if case reopens'],['Competitor saturation','Likely','Major','STRONGLY INDICATED','Retain as reference geography'],['No differentiated access','Certain','Fatal','CONFIRMED','Close active origination'],['Contractor capacity competition','Possible','Moderate','INDICATED','Monitor only'],['Cooling and water rights','Possible','Major','UNVERIFIED','Project-specific rights required'],['Plot-level fiber diversity','Possible','Major','UNVERIFIED','Route audit only if reopened']]
export default function KouvolaKotkaCandidatePage(){
 const [allRisks,setAllRisks]=useState(false)
 const [locale,setLocale]=useState<'en'|'es'|'pt'|'fi'>('en')
 useAtlasMetadata({name:'Kouvola–Kotka',country:'Finland',description:'Project Atlas Gate 1 assessment of the Kouvola–Kotka corridor, Finland. Research complete; recommendation FAIL and active origination closed.',route:'/infrastructure/finland/kouvola-kotka'})
 if(locale==='fi')return <KouvolaKotkaLocal locale={locale} setLocale={setLocale}/>
 return <AtlasLocaleProvider locale="en"><div lang="en" className="bg-white text-zinc-950"><AtlasCandidateHero languageControl={<AtlasLanguageSelector locale={locale} localCode="fi" onChange={setLocale}/>} country="Finland" name="Kouvola–Kotka Corridor" id="EU-FI-02" gate="Gate 1" status="FAIL" date="August 2026" researchState="Research complete · active origination closed" assessment="Kouvola–Kotka is an excellent data-centre geography, but Atlas has no defensible site-origination position because land, grid access and critical relationships are substantially captured." blocker="No verified uncommitted grid capacity combined with heavily pre-empted land." dossier={dossier}/><AtlasCandidateNav items={nav}/>
 <AtlasSection number="02" title="Executive Assessment"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[['Why this location?','Low-carbon power, brownfields, cold climate, logistics, district heat and hyperscale validation.','CONFIRMED'],['What the evidence says','The regional thesis is valid. The opportunity has largely been captured.','STRONGLY INDICATED'],['Primary blocker','Available MW is not verified and large-demand connections face restrictions.','BLOCKER'],['Atlas position','Do not advance toward Gate 2. Retain the learning.','CONFIRMED']].map(x=><article className="rounded-2xl border p-6" key={x[0]}><AtlasEvidenceBadge status={x[2] as 'CONFIRMED'}/><h3 className="mt-5 font-semibold">{x[0]}</h3><p className="mt-3 text-sm text-zinc-600">{x[1]}</p></article>)}</div></AtlasSection>
 <AtlasSection id="decision" number="03" title="Why Atlas Rejected This Candidate"><div className="rounded-3xl bg-zinc-950 p-8 text-white md:p-10"><p className="text-sm font-bold text-red-200">GATE 1 — FAIL · RESEARCH COMPLETE</p><h3 className="mt-5 max-w-4xl text-4xl font-semibold">The corridor can support such a campus. Atlas cannot originate it.</h3><ol className="mt-8 grid gap-4 md:grid-cols-2">{['Land is substantially pre-empted.','Transmission connections are constrained.','Electricity taxation worsened materially from 1 July 2026.','Atlas has no demand, capital or differentiation.'].map((x,i)=><li className="rounded-2xl border border-white/10 p-5 text-zinc-300" key={x}>{i+1}. {x}</li>)}</ol><p className="mt-8 border-l-2 border-amber-300 pl-5 text-xl">A good location is not necessarily an Atlas opportunity.</p><div className="mt-8"><AtlasDossierCTA candidate="Kouvola–Kotka" href={dossier} invert/></div></div></AtlasSection>
 <AtlasSection number="04" title="Candidate Scorecard"><div className="mb-6 grid gap-4 sm:grid-cols-2"><AtlasMetricCard label="Opportunity Score" value="3.6 / 5"/><AtlasMetricCard label="Evidence Confidence" value="2.7 / 5"/></div><AtlasScorecard scores={scores}/><p className="mt-6 rounded-2xl bg-amber-50 p-5 font-medium text-amber-950">An attractive geography can still fail when access is foreclosed.</p></AtlasSection>
 <AtlasSection id="power" number="05" title="Power Access, Not Power Proximity"><AtlasWarning title="AVAILABLE MW NOT VERIFIED">Excellent Finnish fundamentals and nearby 400/110 kV infrastructure do not establish corridor-specific capacity. Southern Finland large-load connections face restrictions.</AtlasWarning><AtlasDataTable headers={['Scale','Indicative architecture','Voltage','Reinforcement','Timeline','Evidence']} rows={['50 MW','100 MW','250 MW','500 MW+'].map((scale,i)=>[scale,i<2?'Dedicated regional connection subject to study':'Transmission-scale connection subject to study',i===0?'110 kV / study required':'110/400 kV / study required','Capacity allocation and reinforcement unknown','Not verified',<AtlasEvidenceBadge status="UNVERIFIED"/>])}/></AtlasSection>
 <AtlasSection id="land" number="06" title="Competitive Capture of Land"><p className="mb-6 max-w-4xl text-zinc-600">The corridor contains industrial and brownfield estates, but Atlas controls none. Proximity to utilities must not be read as an entitlement.</p><AtlasDataTable headers={['Site','Municipality / corridor','Atlas ownership','Status','Evidence']} rows={sites.map(site=>[site,site.includes('Kotka')?'Kotka':site.includes('Hamina')?'Hamina':site==='Loviisa'?'Loviisa':'Kouvola','No Atlas control',site.includes('Google')?'TAKEN':'CONSTRAINED',<AtlasEvidenceBadge status="INDICATED"/>])}/></AtlasSection>
 <AtlasSection id="competition" number="07" title="Market Validation vs Opportunity Consumption"><div className="grid gap-4 md:grid-cols-2"><AtlasMetricCard label="Market validation" value="Exceptionally strong" note="Existing hyperscale and AI projects prove the geography."/><AtlasMetricCard label="Opportunity consumption" value="Extremely high" note="Incumbents have captured sites, grid positions and infrastructure relationships."/></div><div className="mt-8"><AtlasDataTable headers={['Operator / project','Atlas reading','Customer evidence']} rows={operators.map(x=>[x,'Competitive market evidence; capacity and investment detail remain in the dossier.','Not Atlas demand'])}/></div><div className="mt-8"><AtlasDemandLadder level={0} note="NO OPERATOR DEMAND VALIDATED"/></div></AtlasSection>
 <AtlasSection id="tax" number="08" title="Tax, Connectivity & Delivery"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Fact title="CURRENT LAW" status="CONFIRMED">Data centres moved from electricity tax category II to category I on 1 July 2026, materially worsening the previous operating-cost position.</Fact><Fact title="INTERNATIONAL CONNECTIVITY" status="CONFIRMED">C-Lion1 supports Central European connectivity, but lands in Helsinki/Hanko—not Kouvola/Kotka.</Fact><Fact title="PLOT REDUNDANCY" status="UNVERIFIED">Plot-level redundant hyperscale connectivity remains unverified.</Fact><Fact title="COOLING & HEAT" status="INDICATED">Cold climate and waste-heat potential are strong; commercial rights and off-take capacity are not proven.</Fact><Fact title="DELIVERY ECOSYSTEM" status="CONFIRMED">YIT, Caverion, Eltel, HaminaKotka Port, rail/E18 and Xamk support delivery capability.</Fact><Fact title="CONTRACTOR CAPACITY" status="INDICATED">Available capacity may be constrained by competing projects.</Fact></div></AtlasSection>
 <AtlasSection id="risks" number="09" title="Risks & Critical Unknowns"><AtlasDataTable headers={['Risk','Probability','Impact','Evidence','Response']} rows={(allRisks?risks:risks.slice(0,8)).map(x=>[x[0],x[1],x[2],<AtlasEvidenceBadge status={x[3] as 'CONFIRMED'}/>,x[4]])}/>{risks.length>8&&<button className="mt-5 rounded-full border px-5 py-2 text-sm font-semibold" onClick={()=>setAllRisks(v=>!v)}>{allRisks?'Show priority risks':'View full web risk register'}</button>}<h3 className="mt-12 mb-5 text-2xl font-semibold">Critical unknowns retained in the record</h3><AtlasDataTable headers={['Question','Why it matters','Who can answer','Impact if negative']} rows={[["Is any uncommitted node-level MW available?",'Infrastructure proximity is not capacity.','Fingrid and the relevant DSO','No viable connection'],['Is any suitable estate genuinely controllable?','Major brownfields appear captured.','Landowners and municipalities','No origination position'],['Would an operator back an Atlas campus?','Competitor tenants are not Atlas demand.','Operators','No commercial case']]}/></AtlasSection>
 <AtlasSection id="lessons" number="10" title="Reference Geography & Programme Lessons" dark><div className="grid gap-4 md:grid-cols-3"><Lesson title="Research completed">A FAIL is a successful research outcome: the hypothesis was tested and the result retained.</Lesson><Lesson title="No active programme">The dossier explicitly recommends that Atlas does not execute the proposed validation programme.</Lesson><Lesson title="Value to Atlas">Use the corridor as a benchmark for competitive capture, access discipline and the difference between geography and opportunity.</Lesson></div></AtlasSection>
 <AtlasSection id="conclusion" number="11" title="Investment Conclusion"><div className="grid gap-4 md:grid-cols-3"><Case title="Bull Case">The corridor remains an excellent hyperscale geography and can support further campuses.</Case><Case title="Base Case">Incumbents retain stronger land, grid and infrastructure positions; Atlas has no defensible entry.</Case><Case title="Bear Case">Grid constraints, captured sites, tax deterioration and absent demand compound into a non-originatable project.</Case></div><h3 className="mt-12 mb-5 text-2xl font-semibold">Development Pathway</h3><AtlasDevelopmentPathway steps={['Research — COMPLETE','Infrastructure Validation — BLOCKED','Site Control — NOT ACHIEVED','Grid Application — NOT ACHIEVED','Operator Engagement — NOT ACHIEVED','LOI / Demand — NOT ACHIEVED','Partnership — NOT ACHIEVED','Capital — NOT ACHIEVED']}/><div className="mt-10 rounded-3xl border border-red-200 bg-red-50 p-8 text-red-950"><p className="text-xs font-bold">FINAL RECOMMENDATION</p><p className="mt-3 text-3xl font-semibold">FAIL — DO NOT PROGRESS TO GATE 2.</p><p className="mt-4">93 catalogued sources · 116 evidence records · approximately 49 pages. The complete evidence and source registers remain in the dossier.</p><div className="mt-8"><AtlasDossierCTA candidate="Kouvola–Kotka" href={dossier}/></div></div></AtlasSection>
 </div></AtlasLocaleProvider>}
function Fact({title,status,children}:{title:string;status:'CONFIRMED'|'INDICATED'|'UNVERIFIED';children:React.ReactNode}){return <article className="rounded-2xl border p-6"><AtlasEvidenceBadge status={status}/><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-zinc-600">{children}</p></article>}
function Lesson({title,children}:{title:string;children:React.ReactNode}){return <article className="rounded-2xl border border-white/10 p-6"><h3 className="text-xl font-semibold text-amber-200">{title}</h3><p className="mt-3 text-sm leading-relaxed text-zinc-300">{children}</p></article>}
function Case({title,children}:{title:string;children:React.ReactNode}){return <article className="rounded-2xl border p-6"><h3 className="font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-zinc-600">{children}</p></article>}
