import { useAtlasMetadata } from '../../hooks/useAtlasMetadata'
import SinesLocal from './SinesLocal'
import { useState } from 'react'
import { findings,scorecard,sinesDossierUrl,sources } from '../../data/sinesResearch'
import { AtlasCandidateHero,AtlasLanguageSelector,AtlasLocaleProvider,AtlasCandidateNav,AtlasDataTable,AtlasDemandLadder,AtlasDossierCTA,AtlasEvidenceBadge,AtlasScorecard,AtlasSection,AtlasWarning } from '../../components/atlas/AtlasPrimitives'

const nav=[{id:'overview',label:'Overview'},{id:'decision',label:'Decision'},{id:'power',label:'Power'},{id:'connectivity',label:'Subsea Connectivity'},{id:'zils',label:'ZILS'},{id:'market',label:'Market'},{id:'validation',label:'Validation'},{id:'risks',label:'Risks'},{id:'sources',label:'Sources'}]
const scenarios=['20 MW','50 MW','100 MW','200+ MW']
export default function SinesCandidatePage(){
 const [locale,setLocale]=useState<'en'|'es'|'pt'|'fi'>('en')
 useAtlasMetadata({name:'Sines',country:'Portugal',description:'Project Atlas Gate 1 assessment of Sines, Portugal: a conditional pass subject to verified grid capacity, site control and operator demand.',route:'/infrastructure/portugal/sines'})
 if(locale==='pt')return <SinesLocal locale={locale} setLocale={setLocale}/>
 const scores=scorecard.map(x=>({dimension:x[0],opportunity:x[1],confidence:x[2],note:x[3]}))
 return <AtlasLocaleProvider locale="en"><div lang="en" className="bg-white text-zinc-950"><AtlasCandidateHero languageControl={<AtlasLanguageSelector locale={locale} localCode="pt" onChange={setLocale}/>} country="Portugal" name="Sines" id="EU-PT-01" gate="Gate 1" status="CONDITIONAL PASS" date="10 August 2026" researchState="Dossier complete · capped validation active" assessment="Sines is a strategically important AI infrastructure region, but residual grid capacity, a controllable parcel and Atlas-specific customer demand remain unresolved." blocker="Residual demand-side grid capacity on the Sines–Santo André axis is unknown." dossier={sinesDossierUrl}/><AtlasCandidateNav items={nav}/>
 <AtlasSection number="02" title="Executive Assessment"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[['Why Sines?','Atlantic cables, industrial land, port and energy infrastructure.','CONFIRMED'],['What the evidence says','The market is validated, but Atlas would be a second mover.','STRONGLY INDICATED'],['Primary blocker','Residual demand-side grid capacity is unknown.','BLOCKER'],['Atlas position','Run a capped validation programme, not construction.','CONFIRMED']].map(x=><article className="rounded-2xl border p-6" key={x[0]}><AtlasEvidenceBadge status={x[2] as 'CONFIRMED'}/><h3 className="mt-5 font-semibold">{x[0]}</h3><p className="mt-3 text-sm text-zinc-600">{x[1]}</p></article>)}</div></AtlasSection>
 <AtlasSection id="decision" number="03" title="Gate Decision"><div className="rounded-3xl bg-zinc-950 p-8 text-white"><p className="text-sm font-bold text-amber-200">CONDITIONAL PASS</p><h3 className="mt-4 text-3xl font-semibold">Strategically strong. Development not yet proven.</h3><p className="mt-5 max-w-4xl text-zinc-300">Advance only if REN identifies a credible capacity pathway, Atlas can control a financeable parcel and an operator provides a qualified demand signal.</p><div className="mt-8"><AtlasDossierCTA candidate="Sines" href={sinesDossierUrl} invert/></div></div></AtlasSection>
 <AtlasSection number="04" title="Candidate Scorecard"><AtlasScorecard scores={scores}/></AtlasSection>
 <AtlasSection id="power" number="05" title="REN Grid Validation"><AtlasWarning title="RESIDUAL MW NOT VERIFIED">Visible 400 kV infrastructure, previous allocations and a renewable PPA do not establish a physical connection right for Atlas.</AtlasWarning><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{scenarios.map(scale=><article className="rounded-2xl border p-6" key={scale}><h3 className="text-2xl font-semibold">{scale}</h3><p className="mt-3 text-sm text-zinc-600">Research envelope only. Architecture, voltage, reinforcement and energisation timing require REN evidence.</p></article>)}</div></AtlasSection>
 <AtlasSection id="connectivity" number="06" title="Atlantic & Subsea Connectivity"><div className="grid gap-5 md:grid-cols-2"><Feature title="International position" status="CONFIRMED">EllaLink directly connects Sines with South America; existing and planned systems make the regional proposition exceptional.</Feature><Feature title="Parcel-level diversity" status="UNVERIFIED">Cable landings do not prove two physically diverse, commercially available routes to a future parcel.</Feature></div></AtlasSection>
 <AtlasSection id="zils" number="07" title="ZILS, Port & Industrial Land"><p className="max-w-4xl text-zinc-600">ZILS is a major industrial and logistics zone managed by aicep Global Parques. Its surface-right model may support financeable development, but Atlas has not secured or validated a parcel.</p><AtlasDataTable headers={['Dimension','Regional evidence','Atlas position']} rows={[["Industrial land",'Large-scale ZILS context is established.','No parcel control'],['Port infrastructure','Deep-water industrial port and logistics ecosystem.','Regional capability, not site entitlement'],['Planning and tenure','Potentially supportive framework.','Compatibility and lender protections unresolved']]}/></AtlasSection>
 <AtlasSection id="market" number="08" title="Existing Data-Centre Ecosystem"><div className="grid gap-5 md:grid-cols-2"><Feature title="Market validation" status="CONFIRMED">Start Campus and other infrastructure investment validate Sines as a data-centre geography.</Feature><Feature title="Opportunity consumption" status="STRONGLY INDICATED">First movers and industrial projects compete for power, land, supply chain and institutional attention.</Feature></div><div className="mt-8"><AtlasDemandLadder level={0} note="REGIONAL DEMAND PROVEN · ATLAS DEMAND UNPROVEN"/></div></AtlasSection>
 <AtlasSection id="validation" number="09" title="Thirty-Day Validation Programme" dark><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{['Submit formal REN capacity and connection-process enquiry.','Request ZILS parcel and infrastructure data room.','Audit two contractible physically diverse fiber routes.','Consult water and environmental authorities.','Conduct structured operator conversations and seek a written EOI.','Decide advance, hold, partner-only or reject at day 30.'].map((x,i)=><article className="rounded-2xl border border-white/10 p-6" key={x}><p className="text-xs text-amber-200">0{i+1}</p><p className="mt-3 text-sm text-zinc-300">{x}</p></article>)}</div></AtlasSection>
 <AtlasSection id="risks" number="10" title="Risks & Critical Unknowns"><AtlasDataTable headers={['Risk','Effect','Required response']} rows={[["No residual grid capacity",'Gate-blocking','Written REN guidance'],['No financeable parcel','Major','Compare parcels and conditional tenure'],['Shared fiber failure points','Major','Route-level diversity audit'],['No differentiated customer','Gate-blocking','Customer discovery and EOI'],['Environmental cumulative impacts','Major','Early scoping and baselines']]}/><div className="mt-8 grid gap-4 md:grid-cols-2">{findings.map(f=><details className="rounded-2xl border p-5" key={f[0]}><summary className="cursor-pointer font-semibold">{f[0]} · {f[1]}</summary><ul className="mt-4 space-y-2 text-sm text-zinc-600">{f[2].map(x=><li key={x}>— {x}</li>)}</ul></details>)}</div></AtlasSection>
 <AtlasSection id="sources" number="11" title="Evidence & Sources"><div className="grid gap-4 md:grid-cols-2">{sources.map(s=><a className="rounded-2xl border p-5 hover:border-zinc-950" href={s[2]} key={s[1]}><p className="text-xs text-zinc-400">{s[0]}</p><h3 className="mt-2 font-semibold underline">{s[1]}</h3><p className="mt-2 text-sm text-zinc-600">{s[3]}</p></a>)}</div><div className="mt-8"><AtlasDossierCTA candidate="Sines" href={sinesDossierUrl}/></div></AtlasSection>
 </div></AtlasLocaleProvider>}
function Feature({title,status,children}:{title:string;status:'CONFIRMED'|'STRONGLY INDICATED'|'UNVERIFIED';children:React.ReactNode}){return <article className="rounded-2xl border p-6"><AtlasEvidenceBadge status={status}/><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-zinc-600">{children}</p></article>}
