import { Link } from 'react-router-dom'
const contact='mailto:alex@albedo-industries.com?subject=ALBEDO%20Industries%20conversation'
export default function About(){return <article>
 <header className="bg-zinc-950 text-white"><div className="mx-auto max-w-6xl px-5 py-24 sm:px-6 md:py-32"><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-200">About ALBEDO Industries</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold leading-[.98] tracking-[-.04em] md:text-7xl">Build the infrastructure. Test the future.</h1><p className="mt-7 max-w-2xl text-lg text-zinc-300">ALBEDO is an early-stage company developing physical and operational infrastructure for AI, with Project Atlas as its primary commercial initiative.</p></div></header>
 <Section n="01" title="Why ALBEDO"><p className="max-w-3xl text-2xl leading-relaxed text-zinc-600">AI growth is a physical-infrastructure problem: power, land, interfaces and operating systems must work together.</p></Section>
 <Section n="02" title="Four initiatives"><div className="grid gap-px bg-zinc-300 md:grid-cols-2"><Area title="Project Atlas" status="PRIMARY" to="/atlas">Where compute can scale today.</Area><Area title="Albedo Orbital" status="RESEARCH" to="/orbital">Where compute may scale next.</Area><Area title="Albedo Display" status="PRE-PROTOTYPE" to="/display">Persistent physical information infrastructure.</Area><Area title="FastSoftware" status="BUILDING" to="/fastsoftware">Operational systems around real work.</Area></div></Section>
 <Section n="03" title="How we work"><div className="flex flex-wrap gap-x-8 gap-y-4 text-3xl font-semibold"><span>IDENTIFY</span><span>→</span><span>VALIDATE</span><span>→</span><span>BUILD / DECIDE</span></div><p className="mt-7 max-w-2xl text-zinc-600">Claims follow evidence. Work advances only when it earns the next commitment.</p></Section>
 <section className="bg-amber-300"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-20 sm:px-6 md:grid-cols-[.7fr_1.3fr] md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em]">04 · Founder + contact</p><h2 className="mt-4 text-3xl font-semibold">Alex Velasco</h2><p className="mt-2 text-sm">Founder · ALBEDO Industries</p></div><div><h2 className="text-4xl font-semibold tracking-tight md:text-6xl">Start with the opportunity.</h2><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link to="/atlas/partners" className="inline-flex min-h-12 items-center justify-center bg-zinc-950 px-6 text-sm font-semibold text-white">Investment & partnerships</Link><a href={contact} className="inline-flex min-h-12 items-center justify-center border border-zinc-950 px-6 text-sm font-semibold">Contact Alex</a></div></div></div></section>
 </article>}
function Section({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <section className="border-b border-zinc-300"><div className="mx-auto max-w-6xl px-5 py-20 sm:px-6 md:py-28"><p className="text-xs font-bold uppercase tracking-[.16em] text-zinc-500">{n}</p><h2 className="mt-4 text-4xl font-semibold tracking-tight md:text-6xl">{title}</h2><div className="mt-10">{children}</div></div></section>}
function Area({title,status,to,children}:{title:string;status:string;to:string;children:React.ReactNode}){return <Link to={to} className="bg-white p-7 transition-colors hover:bg-zinc-50"><span className="text-[.65rem] font-bold tracking-[.14em] text-zinc-500">{status}</span><h3 className="mt-3 text-2xl font-semibold">{title}</h3><p className="mt-4 text-zinc-600">{children}</p><span className="mt-6 inline-block font-semibold">Explore →</span></Link>}
