import { Link } from 'react-router-dom'
const contact='mailto:alex@albedo-industries.com?subject=ALBEDO%20Industries%20conversation'
const principles=[['Evidence before claims','Important power, land, permit, financing and demand statements retain their evidence status.'],['Start from real constraints','Grid, property, planning, operations and commercial structure shape what is possible.'],['Build where there is a path','Research becomes development work only when the next gate is credible.'],['Keep uncertainty visible','Technical and commercial unknowns are inputs to decisions, not details to hide.'],['Move toward decisions','The purpose of research and software is to advance, pause, restructure or stop with better evidence.'],['Use AI as a tool','Software and AI should reduce operational work without replacing accountable decisions.']]
export default function About(){return <article>
<header className="border-b border-zinc-800 bg-zinc-950 text-white"><div className="mx-auto max-w-6xl px-5 py-24 sm:px-6 md:py-32"><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-200">About ALBEDO Industries</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold leading-[.98] tracking-[-.04em] sm:text-6xl md:text-7xl">Building the physical layer of AI.</h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-zinc-300">ALBEDO is an independent, early-stage company focused primarily on data-center and AI-infrastructure development through Project Atlas, with additional work in persistent infrastructure interfaces and operational software.</p></div></header>
<Section n="01" title="AI infrastructure is more than compute."><div className="max-w-3xl space-y-5 text-lg leading-relaxed text-zinc-600"><p>AI expansion creates physical demand for power, land, compute infrastructure, operations, maintenance, information interfaces, software, people and development capital.</p><p>ALBEDO does not claim to control that entire stack. It builds capabilities around selected physical and operational problems where disciplined development, product engineering or software can move work forward.</p></div></Section>
<Section n="02" title="Why infrastructure"><p className="max-w-3xl text-lg leading-relaxed text-zinc-600">A credible data-center project depends on local evidence: a connection pathway, developable land, fibre, cooling feasibility, planning, permitting, commercial structure, capital and demand. Project Atlas is the current strategic center of ALBEDO because those conditions must be assembled before construction can begin.</p></Section>
<Section n="03" title="Four principal initiatives"><div className="divide-y divide-zinc-300 border-y border-zinc-300"><Area title="Project Atlas" status="PRIMARY INITIATIVE" to="/atlas">Data-center infrastructure origination, validation and early-stage development. Atlas advances selected opportunities through evidence on power, land, connectivity, planning, permitting, control pathways and commercial alignment.</Area><Area title="Albedo Orbital" status="RESEARCH / PRE-DEVELOPMENT" to="/orbital">A long-horizon research initiative mapping the infrastructure required for autonomous compute beyond traditional terrestrial grids. No orbital hardware is under construction.</Area><Area title="Albedo Display" status="PRE-PROTOTYPE" to="/display">A persistent physical information interface designed initially for data-center racks, maintenance, commissioning and critical infrastructure. The engineering architecture remains open.</Area><Area title="FastSoftware" status="SYSTEMS AT DIFFERENT STAGES" to="/fastsoftware">Focused operational software, internal tools and human-reviewed AI-assisted workflows built around real work.</Area></div></Section>
<Section n="04" title="How ALBEDO works"><div className="grid gap-px bg-zinc-300 sm:grid-cols-2 lg:grid-cols-4">{[['01','Identify','Start with a specific physical or operational constraint.'],['02','Validate','Separate assumptions, counterparty statements, documents and verified facts.'],['03','Structure','Define the next technical, commercial or development gate.'],['04','Build / decide','Advance what earns the next commitment; pause or stop what does not.']].map(([n,t,c])=><article className="bg-white p-6" key={n}><span className="text-xs text-zinc-400">{n}</span><h3 className="mt-4 text-sm font-bold uppercase tracking-[.14em]">{t}</h3><p className="mt-3 text-sm text-zinc-600">{c}</p></article>)}</div></Section>
<Section n="05" title="What ALBEDO is today"><div className="grid gap-10 md:grid-cols-[1fr_1.3fr]"><p className="text-2xl font-semibold">Early-stage, selective and explicit about what is not yet established.</p><div className="space-y-4 text-zinc-600"><p>Project Atlas is actively originating and validating infrastructure opportunities. Control status varies by opportunity and is evidence-labelled.</p><p>Albedo Orbital is research / pre-development. Albedo Display is pre-prototype. FastSoftware contains systems and demonstrations at different stages of development.</p><p>ALBEDO does not present itself as a data-center operator, institutional fund, large development balance sheet or manufacturing operation. Project-specific legal structures, partnerships and investment arrangements are established only where appropriate.</p></div></div></Section>
<Section n="06" title="Founder"><div className="grid gap-8 md:grid-cols-[.4fr_1fr]"><div><h3 className="text-2xl font-semibold">Alex Velasco</h3><p className="mt-2 text-sm text-zinc-500">Founder · ALBEDO Industries / Project Atlas</p></div><p className="max-w-2xl text-lg leading-relaxed text-zinc-600">Alex is building ALBEDO as an independent, evidence-led and development-focused company. Project-specific work brings in the relevant utilities, landowners, public institutions, engineers, developers, investors, operators and product partners as opportunities progress.</p></div></Section>
<Section n="07" title="Operating principles"><div className="divide-y divide-zinc-300 border-y border-zinc-300">{principles.map(([title,copy],i)=><div className="grid gap-2 py-5 sm:grid-cols-[3rem_12rem_1fr]" key={title}><span className="text-xs text-zinc-400">0{i+1}</span><h3 className="text-sm font-semibold">{title}</h3><p className="text-sm text-zinc-600">{copy}</p></div>)}</div></Section>
<section className="bg-amber-300"><div className="mx-auto flex max-w-6xl flex-col gap-8 px-5 py-16 sm:px-6 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em]">08 · Contact</p><h2 className="mt-3 max-w-3xl text-3xl font-semibold tracking-tight md:text-5xl">Start with the opportunity, requirement or operating problem.</h2></div><div className="flex shrink-0 flex-col gap-3"><Link to="/atlas/partners" className="inline-flex min-h-12 items-center justify-center bg-zinc-950 px-6 text-sm font-semibold text-white">Investment & development partners</Link><a href={contact} className="inline-flex min-h-12 items-center justify-center border border-zinc-950 px-6 text-sm font-semibold">General ALBEDO conversation</a></div></div></section>
</article>}
function Section({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <section className="border-b border-zinc-300"><div className="mx-auto max-w-6xl px-5 py-20 sm:px-6 md:py-24"><p className="text-xs font-bold uppercase tracking-[.16em] text-zinc-500">{n}</p><h2 className="mt-4 max-w-4xl text-3xl font-semibold tracking-tight sm:text-4xl md:text-5xl">{title}</h2><div className="mt-10">{children}</div></div></section>}
function Area({title,status,to,children}:{title:string;status:string;to:string;children:React.ReactNode}){return <article className="grid gap-4 py-7 md:grid-cols-[13rem_1fr_auto] md:items-start"><div><h3 className="text-xl font-semibold">{title}</h3><p className="mt-2 text-[.65rem] font-bold tracking-[.14em] text-zinc-500">{status}</p></div><p className="max-w-2xl text-sm leading-relaxed text-zinc-600">{children}</p><Link to={to} className="inline-flex min-h-11 items-center text-sm font-semibold underline decoration-amber-500 underline-offset-4">Explore →</Link></article>}
