import { Link } from 'react-router-dom'
import DisplayAssetFigure from '../components/display/DisplayAssetFigure'
import { displayAssets } from '../data/albedoDisplayAssets'
const email='mailto:alex@albedo-industries.com?subject=Albedo%20Display%20investment%20discussion'
const items=[
 ['01','Investment thesis','A phone already carries identity, connectivity, input, internet and AI. If a dedicated endpoint only renders structured information, its hardware could be far simpler than a smart display. The useful and defensible part is unproven.'],
 ['02','Product','A USB-C-powered 4–5 inch non-touch display, connected over BLE to a phone and driven by an ESP32-class controller. No camera, microphone, speaker, battery, local AI or cellular modem in V0.'],
 ['03','Current evidence','Concept architecture complete. Component shortlist and payload design prepared. No physical prototype, validated demand, supplier quote, customer, pilot, partnership or production cost yet.'],
 ['04','Hardware economics','Prototype architecture: $35–70 using retail modules. Planning estimate at 10k units: $11–22 before tooling, certification, logistics, yield and warranty. The $10–15 BOM is an aspirational target—not a confirmed cost.'],
 ['05','Market hypotheses','Start with operational and hospitality workflows where one persistent state matters and a tablet is excessive. Consumer productivity is easy to test but likely harder to distribute profitably.'],
 ['06','Competitive position','TRMNL, Tidbyt, LaMetric, smart displays, tablets, ESL and DIY ESP32 products validate adjacent behaviours and compress differentiation. Albedo must prove lower endpoint economics plus a better AI-to-display workflow.'],
 ['07','Validation roadmap','First €1k: two panel/controller builds, measured BLE latency and power, five workflow prototypes, 15 interviews and three supplier conversations. Stop if no repeated use or credible cost path emerges.'],
 ['08','Funding requirement','Current objective is milestone finance, not a formal venture round. Founder funding, a paid design partner and in-kind manufacturing support are preferred before institutional capital.'],
 ['09','Use of funds','€2k: working prototype. €10k: industrial prototype and quote validation. €25k: pilot units and software. €50k: custom electronics and manufacturing validation. All are planning assumptions.'],
 ['10','Key risks','Commodity hardware, cheap-tablet competition, BLE friction, weak willingness to pay, fragmented use cases, low margins and capital-heavy manufacturing.'],
 ['11','Team & structure','An independent project within Albedo Industries. It remains separate from Project Atlas and should stay internal until technical, demand and financing evidence justify incorporation.'],
]
export default function AlbedoDisplayInvest(){return <article className="ad-page ad-memo"><div className="ad-projectbar"><Link to="/display">← ALBEDO DISPLAY</Link><span className="ad-projectbar__right">Investor brief · 04 September 2026</span></div><header><div className="ad-wrap ad-memo__hero"><div><span className="ad-status">Concept / component validation stage</span><p className="ad-kicker">INVESTMENT BRIEF · PRE-VALIDATION</p><h1>Finance the next answer,<br/>not the whole company.</h1><p className="ad-lede">Albedo Display tests whether AI can live on the phone while the physical interface stays radically simple. This memo states what exists, what does not, and the cheapest route to a decision.</p><div className="ad-actions"><a href={email}>Discuss a milestone</a><Link className="secondary" to="/display">Read project evidence</Link></div></div><DisplayAssetFigure asset={displayAssets.v0Concept} showNotes /></div></header><main className="ad-wrap"><div className="ad-memo__facts"><div><small>CURRENT STATUS</small><b>Concept / component validation</b></div><div><small>INITIAL ASK</small><b>€1k validation</b></div><div><small>VOLUME BOM</small><b>$10–15 target</b></div><div><small>RECOMMENDATION</small><b>Validate first</b></div></div>{items.map(x=><section key={x[0]}><span>{x[0]}</span><h2>{x[1]}</h2><p>{x[2]}</p></section>)}<section className="ad-memo__contact"><span>12</span><h2>Contact</h2><p>Investors should expect a component log, test results, interview evidence and explicit go/no-go gates—not a polished claim of product-market fit.</p><a href={email}>alex@albedo-industries.com ↗</a></section></main></article>}
