import { Link } from 'react-router-dom'
import DisplayAssetFigure from '../components/display/DisplayAssetFigure'
import { displayAssets } from '../data/albedoDisplayAssets'

const contact = (topic:string) => `mailto:alex@albedo-industries.com?subject=${encodeURIComponent(`Albedo Display — ${topic}`)}`
const useCases = [
  ['Personal productivity','Phone notifications; smart displays','A next action can remain visible without unlocking a phone. A tablet may be excessive for one calm surface.','Individual / employer'],
  ['Hospitality','Printed cards; tablets; signage','Guest or room information changes, but rarely needs a full tablet.','Operator / property manager'],
  ['Office operations','TV dashboards; labels; chat','Room state, instructions or one KPI can stay at the point of work.','Facilities / operations'],
  ['Education','Whiteboards; paper; tablets','A teacher-controlled instruction surface could reduce shared-device cost.','School / training provider'],
  ['Retail & service','Paper signs; ESL; digital signage','Small dynamic messages may sit between shelf labels and costly signage.','Store / service operator'],
]
const roadmap = [
  ['0','Component validation','€200–€500','Panel refreshes reliably; measured power and BLE transfer support V0.'],
  ['1','Working Bluetooth prototype','€500–€2,000','Five target users complete setup and update a useful screen.'],
  ['2','Industrial-looking prototype','€2,000–€5,000','Supplier-backed BOM and 10 design-partner commitments.'],
  ['3','10–50 unit pilot','€5,000–€20,000','Paid deployment demonstrates repeated use and acceptable reliability.'],
  ['4','Custom PCB + manufacturing validation','€20,000–€50,000+','Quotes, compliance plan and margin justify a build.'],
]
const risks=['A usable display may cost too much.','A cheap tablet may solve the job better.','Phone dependency and BLE onboarding may create friction.','AI-generated layouts may add little practical value.','Low hardware margins may not support the business.','Manufacturing could require more capital than planned.','Demand may fragment across incompatible niches.','Consumers may not need another device.']
function Status({children}:{children:React.ReactNode}){return <span className="ad-status">{children}</span>}
function Section({id,kicker,title,children,dark=false}:{id:string;kicker:string;title:string;children:React.ReactNode;dark?:boolean}){return <section id={id} className={`ad-section ${dark?'ad-dark':''}`}><div className="ad-wrap"><p className="ad-kicker">{kicker}</p><h2>{title}</h2>{children}</div></section>}
export default function AlbedoDisplay(){
 return <article className="ad-page">
  <div className="ad-projectbar"><span>ALBEDO DISPLAY</span><span className="ad-projectbar__right">Independent project within Albedo Industries · <Link to="/display/invest">Investor brief ↗</Link></span></div>
  <header className="ad-hero"><div className="ad-wrap"><div className="ad-hero__intro"><div><Status>Concept / component validation stage</Status><p className="ad-kicker">ALBEDO DISPLAY</p><h1>The cheapest possible physical interface for AI.</h1></div><div><p className="ad-lede">A simple 4–5 inch display controlled by your phone and AI, designed to remove the expensive parts of conventional smart hardware.</p><div className="ad-flow"><b>Phone / AI</b><span>→ Bluetooth →</span><b>Display</b></div><div className="ad-actions"><a href="#evidence">See the current evidence</a><a className="secondary" href={contact('investment or pilot')}>Discuss investment / pilot</a></div></div></div><DisplayAssetFigure asset={displayAssets.v0Concept} className="ad-hero__asset" showNotes /></div></header>
  <Section id="thesis" kicker="01 / THE THESIS" title="Remove the computer from the smart display."><div className="ad-two"><div><h3>Conventional smart hardware adds</h3><p>Processor, operating system, battery, speakers, microphone, camera, touch, cloud setup and complex electronics.</p></div><div><h3>The phone already provides</h3><p>Internet, AI, microphone, keyboard, identity, processing and connectivity. The endpoint may only need a display, BLE, a simple MCU and power.</p></div></div><div className="ad-callout"><b>Hypothesis being validated</b><p>The intelligence stays on the phone/cloud, allowing the physical AI interface to remain extremely simple and inexpensive. This is not yet proven to be useful, differentiated or manufacturable at the target cost.</p></div></Section>
  <Section id="works" kicker="02 / SYSTEM" title="The device is a physical output layer." dark><div className="ad-architecture">{['User','AI / ChatGPT','Smartphone','BLE','ESP32-class controller','4–5 inch display'].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b>{i<5&&<i>↓</i>}</div>)}</div><p className="ad-widecopy">The phone converts intent into a constrained display description: text, hierarchy, positions, icons, simple graphics, visual states and alerts. V0 tests template + data payloads first; bitmap transfer remains a fallback for layout flexibility.</p></Section>
  <Section id="matter" kicker="03 / BEHAVIOUR" title="Persistent information without another expensive computer."><p className="ad-intro">Phones are excellent for interaction, but poor for information that should remain visible. The project tests whether a calm, dedicated surface improves action and awareness enough to justify another device.</p><div className="ad-tags">{['Next task','Calendar','Room status','Guest information','Production KPI','Classroom instruction','Household status','Operational alert'].map(x=><span key={x}>{x}</span>)}</div></Section>
  <Section id="evidence" kicker="04 / CURRENT EVIDENCE" title="A concept, not yet a product."><div className="ad-evidence"><div className="ad-evidence__reference"><p className="ad-intro">The current visual above is an industrial-design and hardware-architecture hypothesis. Its dimensions, screen technology, enclosure, electronics and displayed BOM are preliminary.</p><a href={displayAssets.v0Concept.src} target="_blank" rel="noreferrer">Review the full concept image ↗</a><ol className="ad-progression"><li className="current">Concept <b>Today</b></li><li>Components</li><li>Working Bluetooth prototype</li><li>Physical enclosure</li><li>Custom PCB</li><li>Pilot units</li><li>Manufacturing validation</li></ol></div><div className="ad-ledger"><div><Status>Selected for testing</Status><h3>Screen candidate</h3><p>4.3-inch 480×272 SPI TFT module. Exact panel and lifecycle remain open.</p></div><div><Status>Selected for testing</Status><h3>Controller candidate</h3><p>ESP32-S3 for the first colour prototype; test ESP32-C3 only if display throughput and RAM remain sufficient.</p></div><div><Status>Concept</Status><h3>Software</h3><p>Android test harness → versioned JSON/template payload → BLE chunks → local renderer.</p></div></div></div><div className="ad-two ad-known"><div><h3>What we know</h3><ul><li>BLE and ESP32-class controllers are technically capable of structured, low-frequency updates.</li><li>A phone can provide the AI and internet layer.</li><li>Off-the-shelf display modules allow a low-cost feasibility prototype.</li></ul></div><div><h3>What we still need to validate</h3><ul><li>Cheapest usable panel and real volume quote</li><li>User value, latency and onboarding</li><li>Power, enclosure and industrial design</li><li>Willingness to pay and best first market</li></ul></div></div></Section>
  <Section id="economics" kicker="05 / HARDWARE ECONOMICS" title="The target is not the cost."><div className="ad-target"><span>Aspirational volume BOM</span><strong>US$10–15</strong><em>TARGET · NOT CONFIRMED</em></div><div className="ad-tablewrap"><table><thead><tr><th>Cost basis</th><th>Prototype</th><th>100 units</th><th>1,000 units</th><th>10,000 units</th></tr></thead><tbody><tr><td>Current architecture</td><td>$35–70</td><td>$22–40</td><td>$15–28</td><td>$11–22</td></tr><tr><td>Evidence class</td><td>Public retail modules</td><td>Planning estimate</td><td>Planning estimate</td><td>Planning estimate</td></tr><tr><td>Confidence</td><td>Medium</td><td>Low</td><td>Low</td><td>Very low</td></tr></tbody></table></div><p className="ad-note">Ranges include display, MCU/PCB, USB-C power, enclosure and assembly, but exclude tooling, certification, freight, duties, yield, warranty and software. Supplier quotes are required before any manufacturing claim.</p></Section>
  <Section id="uses" kicker="06 / USE-CASE HYPOTHESES" title="Five jobs worth testing—not five markets we claim to own.">{useCases.map((u,i)=><div className="ad-use" key={u[0]}><b>0{i+1}</b><h3>{u[0]}</h3><div><small>CURRENT ALTERNATIVE</small><p>{u[1]}</p></div><div><small>WHY TEST IT</small><p>{u[2]}</p></div><div><small>POTENTIAL PAYER</small><p>{u[3]}</p></div><Status>Unvalidated</Status></div>)}</Section>
  <Section id="landscape" kicker="07 / LANDSCAPE" title="The market may already solve this problem." dark><div className="ad-tablewrap"><table><thead><tr><th>Category / example</th><th>What it proves</th><th>Open question for Albedo</th></tr></thead><tbody><tr><td>TRMNL / e-paper dashboards</td><td>Demand for calm, persistent information</td><td>Can colour and lower price outweigh battery life?</td></tr><tr><td>Tidbyt / LaMetric</td><td>People buy compact connected displays</td><td>Is phone-controlled AI materially more useful?</td></tr><tr><td>Seeed / ESP32 display kits</td><td>Hardware is readily prototyped</td><td>Is there value beyond assembled commodity parts?</td></tr><tr><td>Smart displays / cheap tablets</td><td>Broad capability at falling prices</td><td>Can radical simplicity win on TCO or placement?</td></tr><tr><td>Electronic shelf labels</td><td>Low-power fleets can reach scale</td><td>Can Albedo match fleet economics without scale?</td></tr></tbody></table></div><p className="ad-widecopy">The current differentiation thesis is weak until a specific workflow values AI-generated layouts, phone-side intelligence and materially lower endpoint cost. Software workflow, distribution and fleet operations—not commodity hardware—would need to create defensibility.</p></Section>
  <Section id="models" kicker="08 / BUSINESS MODEL" title="Keep the model open until the payer is clear."><div className="ad-models">{[['Consumer hardware','Simple; margin-sensitive','High'],['Hardware + service','Recurring value must be proven','High'],['B2B + fleet SaaS','Best potential workflow lock-in','Medium'],['OEM reference design','Lower capital; partner dependence','Lower'],['Paid pilot','Strong validation signal','Low'],['Strategic subsidy','Could unlock scale; uncertain access','Medium']].map(x=><div key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p><small>CAPITAL INTENSITY · {x[2]}</small></div>)}</div></Section>
  <Section id="roadmap" kicker="09 / LEAN ROADMAP" title="Each cheque must retire a specific risk.">{roadmap.map(x=><div className="ad-phase" key={x[0]}><b>PHASE {x[0]}</b><h3>{x[1]}</h3><strong>{x[2]}</strong><p><small>GO / NO-GO</small>{x[3]}</p></div>)}<p className="ad-note">All budgets are planning assumptions, not supplier-validated forecasts.</p></Section>
  <Section id="capital" kicker="10 / CAPITAL" title="Finance technical and market validation—not premature scale." dark><div className="ad-unlocks">{[['€2k','Working prototype'],['€10k','Industrial prototype + supplier validation'],['€25k','Pilot units + software'],['€50k','Custom electronics + manufacturing validation']].map(x=><div key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span><small>PLANNING ASSUMPTION</small></div>)}</div><p className="ad-widecopy">Preferred order: founder-funded component work → paid design partner or pilot → supplier support → selective grant or accelerator → external equity only when retention, willingness to pay and credible unit economics exist.</p></Section>
  <Section id="partner" kicker="11 / PARTNER WITH US" title="Three practical ways to test the thesis."><div className="ad-partners"><a href={contact('investment')}><span>INVEST</span><h3>Fund a defined validation milestone.</h3><p>For investors in hardware, ambient computing, IoT and AI interfaces.</p><b>Start a conversation →</b></a><a href={contact('pilot')}><span>PILOT</span><h3>Bring one persistent-information workflow.</h3><p>For organisations prepared to measure use, friction and willingness to pay.</p><b>Propose a use case →</b></a><a href={contact('manufacturing')}><span>BUILD</span><h3>Help test cost and manufacturability.</h3><p>For display, PCB, component and ODM/OEM partners.</p><b>Share capability →</b></a></div></Section>
  <Section id="team" kicker="12 / PROJECT" title="Independent by design."><p className="ad-intro">Albedo Display is an independently structured project within Albedo Industries. Its website, evidence, assets, outreach and financing work are separated from Project Atlas and other initiatives. It should remain inside Albedo Industries until evidence supports a standalone company.</p></Section>
  <Section id="risks" kicker="13 / DOWNSIDE" title="Reasons to stop." dark><div className="ad-risks">{risks.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><p>{x}</p></div>)}</div></Section>
  <Section id="contact" kicker="14 / CONTACT" title="Bring evidence, a use case or a manufacturing path."><div className="ad-contact">{['Investment','Pilot','Manufacturing','General'].map(x=><a key={x} href={contact(x)}><span>{x}</span><b>alex@albedo-industries.com ↗</b></a>)}</div><p className="ad-note">No public data room is available. Relevant materials can be shared selectively as evidence develops.</p></Section>
 </article>
}
