import { useEffect } from 'react'
import { Link } from 'react-router-dom'
const discuss='mailto:alex@albedo-industries.com?subject=Albedo%20Display%20strategic%20partner%20discussion'
const unknowns=['Display technology and optical performance','Controller and network architecture','Battery life or wired-power design','Mounting and environmental durability','BOM, tooling and manufacturing yield','Integration workflow and security','Customer willingness to pay']
const models=['Hardware sale','Hardware plus management software','Enterprise fleet deployment','Fleet-management subscription','Integration services','OEM / licensing','Infrastructure partnership']
export default function AlbedoDisplayInvest(){useEffect(()=>{const title='Albedo Display Strategic Brief — Data Center Persistent Displays';const description='Strategic partner brief for Albedo Display, a pre-prototype persistent operational display concept for data centers and critical infrastructure.';document.title=title;document.querySelector('meta[name="description"]')?.setAttribute('content',description);document.querySelector('link[rel="canonical"]')?.setAttribute('href','https://www.albedo-industries.com/display/invest')},[]);return <article className="bg-zinc-950 text-white"><header className="border-b border-zinc-800"><div className="mx-auto max-w-6xl px-5 py-20 sm:px-6 md:py-28"><Link className="inline-flex min-h-11 items-center text-sm text-zinc-400" to="/display">← Albedo Display</Link><p className="mt-10 text-xs font-bold uppercase tracking-[.2em] text-zinc-400">Strategic partner brief · Pre-prototype</p><h1 className="mt-6 max-w-5xl text-4xl font-semibold leading-[1.05] tracking-tight sm:text-5xl md:text-7xl">Validate the infrastructure workflow before scaling the hardware.</h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-zinc-300">Albedo Display explores a persistent, digitally updateable information surface for data-center assets. The opportunity is compelling only if prototype evidence proves operational value, a credible technical architecture and deployable economics.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={discuss} className="inline-flex min-h-12 items-center justify-center bg-white px-6 text-sm font-semibold text-zinc-950">Discuss a strategic partnership</a><Link to="/display" className="inline-flex min-h-12 items-center justify-center border border-zinc-600 px-6 text-sm font-semibold">Review the product concept</Link></div></div></header>
<Memo n="01" eyebrow="Problem and wedge" title="Data centers have a physical information gap."><p>Labels are simple and persistent but cannot update digitally. Full screens are flexible but introduce power, installation and endpoint complexity. The initial thesis is an asset-level display for rack status, maintenance, power paths, commissioning and infrastructure instructions.</p><p>Data centers are the initial wedge because operational information must remain close to physical equipment. Broader critical-infrastructure markets are secondary hypotheses.</p></Memo>
<Memo n="02" eyebrow="Current status" title="Pre-prototype. Engineering architecture open."><div className="grid gap-px bg-zinc-700 md:grid-cols-3"><Truth title="Current" items={['Problem and initial requirements defined','Concept interface and workflow exploration','Pilot and engineering partners sought']}/><Truth title="Proposed" items={['Persistent display endpoint','Managed updates from operational software','Low-power asset-level deployment']}/><Truth title="Not established" items={['Manufactured hardware','Selected display technology','Customers, pilots or commercial demand','Production cost or manufacturing route']}/></div></Memo>
<Memo n="03" eyebrow="Technical thesis" title="Start with existing bistable technology."><p>Phase 1 should use a commercially available e-paper, electrophoretic, cholesteric LCD or another appropriate persistent technology to prove readability, the update workflow, installation and usefulness. No technology is selected today.</p><p>Later engineering may reduce BOM, controller complexity, enclosure cost and power requirements before exploring custom electronics, formats or alternative mechanisms.</p></Memo>
<Memo n="04" eyebrow="Pilot strategy" title="One workflow, one environment, limited units."><p>A credible pilot starts with a data-center operator, developer, colocation provider, commissioning team, facilities team or infrastructure integrator. Together, the parties define one information workflow and measure setup, update reliability, visibility, operator behaviour and whether the concept replaces a current workaround.</p><p>No pilot date or deployment is promised. Prototype evidence comes first.</p></Memo>
<Memo n="05" eyebrow="Capital and strategic support" title="Use resources to answer gated engineering and market questions."><div className="grid border-b border-r border-zinc-700 sm:grid-cols-2 lg:grid-cols-4">{['Component and display evaluation','Electronics and firmware prototype','Enclosure and mounting studies','Pilot units and workflow software','Security and integration design','Supplier and manufacturing validation','Environmental and reliability testing','Customer discovery'].map(x=><div className="border-l border-t border-zinc-700 p-5 text-sm" key={x}>{x}</div>)}</div><p>Any budget, responsibilities, rights and economics would be project-specific and agreed before commitment. This page is not a securities offering.</p></Memo>
<Memo n="06" eyebrow="Key unknowns" title="The project is defined by what still needs validation."><ul className="grid gap-3 sm:grid-cols-2">{unknowns.map(x=><li className="border-t border-zinc-700 py-4 text-sm text-zinc-300" key={x}>— {x}</li>)}</ul></Memo>
<Memo n="07" eyebrow="Models to validate" title="Commercial structure follows pilot evidence."><div className="flex flex-wrap gap-2">{models.map(x=><span className="border border-zinc-600 px-3 py-2 text-sm" key={x}>{x}</span>)}</div><p>None of these models is represented as commercially validated. Customer workflow, deployment volume, integration burden and manufacturing economics will determine whether any is viable.</p></Memo>
<Memo n="08" eyebrow="Manufacturing path" title="Prototype, engineer, pilot—then decide whether to scale."><ol className="grid gap-px bg-zinc-700 md:grid-cols-3"><Truth title="01 · Workflow prototype" items={['Commercially available display','Basic update path','Physical installation study']}/><Truth title="02 · Engineering prototype" items={['Controller and power optimisation','Enclosure and mounting','Supplier and cost validation']}/><Truth title="03 · Pilot deployment" items={['Limited field units','Operational feedback','Go / stop / redesign decision']}/></ol></Memo>
<section className="bg-[#deddd2] text-zinc-950"><div className="mx-auto flex max-w-6xl flex-col gap-8 px-5 py-16 sm:px-6 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em]">Engineering · Manufacturing · Strategic capital</p><h2 className="mt-3 max-w-3xl text-3xl font-semibold tracking-tight md:text-5xl">Help produce the next credible answer.</h2></div><a href={discuss} className="inline-flex min-h-12 shrink-0 items-center justify-center bg-zinc-950 px-6 text-sm font-semibold text-white">Discuss a strategic partnership</a></div></section></article>}
function Memo({n,eyebrow,title,children}:{n:string;eyebrow:string;title:string;children:React.ReactNode}){return <section className="border-b border-zinc-800"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-16 sm:px-6 md:grid-cols-[12rem_1fr] md:py-20"><div><p className="text-xs text-zinc-500">{n}</p><p className="mt-3 text-xs font-bold uppercase tracking-[.15em] text-zinc-400">{eyebrow}</p></div><div><h2 className="max-w-3xl text-3xl font-semibold tracking-tight md:text-4xl">{title}</h2><div className="mt-6 max-w-4xl space-y-5 leading-relaxed text-zinc-400">{children}</div></div></div></section>}
function Truth({title,items}:{title:string;items:string[]}){return <article className="bg-zinc-950 p-6"><h3 className="text-xs font-bold uppercase tracking-[.15em] text-white">{title}</h3><ul className="mt-5 space-y-3 text-sm text-zinc-400">{items.map(x=><li key={x}>— {x}</li>)}</ul></article>}
