import { Link } from 'react-router-dom'
import DisplayAssetFigure from '../components/display/DisplayAssetFigure'
import { displayAssets } from '../data/albedoDisplayAssets'
const pilot='mailto:alex@albedo-industries.com?subject=Albedo%20Display%20pilot'
export default function AlbedoDisplay(){return <article className="bg-[#f4f4ef] text-zinc-950">
 <header><div className="mx-auto grid min-h-[88svh] max-w-7xl items-center gap-10 px-5 py-20 sm:px-6 lg:grid-cols-[.8fr_1.2fr]"><div><span className="bg-zinc-950 px-3 py-2 text-[.68rem] font-bold uppercase tracking-[.15em] text-white">Pre-prototype</span><p className="mt-7 text-xs font-bold uppercase tracking-[.2em]">Albedo Display</p><h1 className="mt-4 text-5xl font-semibold leading-[.96] tracking-[-.04em] md:text-7xl">Information that stays visible.</h1><p className="mt-6 max-w-xl text-lg text-zinc-600">A persistent, software-updateable information interface for data-center racks and critical infrastructure.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#concept" className="ad-button ad-button--primary inline-flex min-h-12 items-center justify-center bg-zinc-950 px-6 text-sm font-semibold text-white">See the concept</a><a href={pilot} className="inline-flex min-h-12 items-center justify-center border border-zinc-950 px-6 text-sm font-semibold">Discuss pilot</a></div></div><DisplayAssetFigure asset={displayAssets.heroConcept} priority/></div></header>
 <Section id="concept" eyebrow="02 · Show the product" title="A label when viewed. A software endpoint when updated."><div className="mx-auto max-w-5xl"><DisplayAssetFigure asset={displayAssets.v0Concept}/></div></Section>
 <Section id="uses" eyebrow="03 · Core use cases" title="Status where physical work happens."><div className="grid gap-6 md:grid-cols-3">{[['RACK / ASSET ID','Identity and ownership at the cabinet.'],['MAINTENANCE / WORK ORDER','The approved task beside the asset.'],['POWER / INCIDENT STATUS','A clear last-confirmed operational state.']].map(([a,b])=><article className="border-t-2 border-zinc-950 pt-5" key={a}><h3 className="text-lg font-semibold">{a}</h3><p className="mt-3 text-zinc-600">{b}</p></article>)}</div><Link to="/display/invest" className="mt-9 inline-flex font-semibold underline decoration-lime-500 underline-offset-4">View more use cases →</Link></Section>
 <Section dark id="workflow" eyebrow="04 · How it works" title="One constrained information path."><ol className="flex flex-col gap-5 text-3xl font-semibold md:flex-row md:items-center md:gap-8 md:text-5xl"><li>SOFTWARE</li><li className="text-lime-300 max-md:rotate-90">→</li><li>UPDATE</li><li className="text-lime-300 max-md:rotate-90">→</li><li>PERSISTENT DISPLAY</li></ol><p className="mt-8 text-sm text-zinc-400">Conceptual architecture. Hardware, protocols and integrations remain to be validated.</p></Section>
 <section className="bg-lime-300"><div className="mx-auto flex max-w-6xl flex-col gap-8 px-5 py-20 sm:px-6 md:flex-row md:items-center md:justify-between"><h2 className="max-w-3xl text-4xl font-semibold tracking-tight md:text-6xl">Test one workflow in one real environment.</h2><a href={pilot} className="inline-flex min-h-12 shrink-0 items-center justify-center bg-zinc-950 px-6 text-sm font-semibold text-white">Discuss a pilot</a></div></section>
 </article>}
function Section({id,eyebrow,title,children,dark=false}:{id:string;eyebrow:string;title:string;children:React.ReactNode;dark?:boolean}){return <section id={id} className={`border-t ${dark?'border-zinc-800 bg-zinc-950 text-white':'border-zinc-300'}`}><div className="mx-auto max-w-6xl px-5 py-20 sm:px-6 md:py-28"><p className={`text-xs font-bold uppercase tracking-[.18em] ${dark?'text-lime-300':'text-zinc-500'}`}>{eyebrow}</p><h2 className="mt-4 max-w-4xl text-4xl font-semibold tracking-tight md:text-6xl">{title}</h2><div className="mt-12">{children}</div></div></section>}
