import { useEffect } from 'react'
import { Link } from 'react-router-dom'
import { asPontesPublication as publication } from '../data/asPontesResearch'

export default function AsPontesResearch() {
  useEffect(() => { const previous = document.title; document.title = 'As Pontes Evidence Review | Albedo Atlas'; return () => { document.title = previous } }, [])
  return <main>
    <section className="bg-zinc-950 text-white"><div className="mx-auto max-w-6xl px-6 py-20 md:py-28">
      <Link to="/infrastructure/spain/as-pontes" className="text-sm text-zinc-400 hover:text-white">← As Pontes candidate record</Link>
      <p className="mt-12 text-xs font-medium uppercase tracking-[.2em] text-amber-300">Atlas publication · {publication.edition}</p>
      <h1 className="mt-5 max-w-4xl text-4xl font-semibold tracking-tight md:text-6xl">{publication.title}</h1>
      <p className="mt-7 max-w-3xl text-lg leading-relaxed text-zinc-400">A source-led review separating verified regional context from the evidence still required for a development decision.</p>
      <div className="mt-10 flex flex-wrap gap-3"><a href={publication.pdf} download={publication.downloadName} className="rounded-lg bg-white px-5 py-3 text-sm font-medium text-zinc-950">As Pontes Full Research Report — Gate 1</a><a href="#findings" className="rounded-lg border border-zinc-700 px-5 py-3 text-sm font-medium">Read the findings</a></div>
      <p className="mt-6 text-xs text-zinc-500">Published <time dateTime={publication.published}>{publication.published}</time> · EU-ES-01 · No investment offering</p>
    </div></section>
    <section className="border-b border-amber-200 bg-amber-50"><div className="mx-auto max-w-6xl px-6 py-16"><p className="eyebrow text-amber-800">Executive conclusion</p><p className="max-w-4xl text-2xl font-medium leading-relaxed text-zinc-900">{publication.conclusion}</p></div></section>
    <section className="border-b border-zinc-200"><div className="mx-auto max-w-6xl px-6 py-20 md:py-28"><p className="eyebrow">Verified baseline</p><h2 className="section-title">What the reviewed sources support</h2><dl className="grid gap-px overflow-hidden rounded-xl border border-zinc-200 bg-zinc-200 md:grid-cols-2">{publication.verifiedFacts.map((fact) => <div key={fact.label} className="bg-white p-6"><dt className="text-xs font-medium uppercase tracking-wider text-zinc-400">{fact.label}</dt><dd className="mt-3 text-sm leading-relaxed text-zinc-700">{fact.value} <span className="font-medium text-zinc-950">[{fact.source}]</span></dd></div>)}</dl></div></section>
    <section id="findings" className="bg-zinc-50"><div className="mx-auto max-w-6xl px-6 py-20 md:py-28"><p className="eyebrow">Atlas assessment</p><h2 className="section-title">Decision-relevant findings</h2><div className="space-y-4">{publication.findings.map((item) => <article key={item.area} className="rounded-xl border border-zinc-200 bg-white p-6 md:grid md:grid-cols-[12rem_1fr] md:gap-8"><div><h3 className="font-semibold">{item.area}</h3><p className="mt-2 text-xs text-amber-700">{item.state}</p></div><div><p className="text-sm leading-relaxed text-zinc-600">{item.finding}</p><p className="mt-4 text-sm leading-relaxed"><strong>Next evidence:</strong> {item.next}</p></div></article>)}</div></div></section>
    <section className="border-t border-zinc-200"><div className="mx-auto max-w-6xl px-6 py-20 md:py-28"><p className="eyebrow">Method and sources</p><h2 className="section-title">Traceable, bounded research</h2><p className="section-copy">This desk review prioritises public primary sources. “Verified” means only that the cited source supports the stated regional fact; it does not verify site feasibility, current grid headroom or commercial availability.</p><ol className="space-y-4">{publication.sources.map((source) => <li key={source.id} className="rounded-xl border border-zinc-200 p-5"><span className="mr-3 text-xs font-semibold text-zinc-400">{source.id}</span><a href={source.url} target="_blank" rel="noreferrer" className="font-medium underline underline-offset-4">{source.title}<span className="sr-only"> (opens in a new tab)</span></a><p className="mt-2 pl-12 text-sm text-zinc-500">{source.publisher}</p></li>)}</ol><div className="mt-10 rounded-xl bg-zinc-950 p-6 text-white"><p className="font-semibold">Research boundary</p><p className="mt-2 max-w-3xl text-sm leading-relaxed text-zinc-400">No site, grid capacity, permit, financing, customer commitment or construction programme is represented as secured. The publication is research, not engineering, legal or investment advice.</p></div></div></section>
  </main>
}
