import { useEffect } from 'react'
import ComputeInterestForm from '../components/ComputeInterestForm'
import { developmentGates, projectUpdates, regions, services } from '../data/computeInfrastructure'

const thesis = [
  ['Energy first', 'The location must be selected around credible access to power, not land alone.'],
  ['Modular deployment', 'Repeatable infrastructure blocks can be added as verified demand grows.'],
  ['Demand before expansion', 'Customer requirements should determine the scale and configuration of each phase.'],
  ['Transparent development', 'Verified milestones, open dependencies and material changes will be published.'],
]
const audiences = [
  ['AI startups', 'Flexible capacity for training, inference and product validation.'], ['Software companies', 'Managed infrastructure without building a private facility.'],
  ['Research groups & universities', 'Regional capacity for data-intensive research.'], ['Industrial companies', 'Private compute near operational data and facilities.'],
  ['Private-cloud customers', 'Controlled infrastructure and data-residency options.'], ['Regional institutions', 'Potential sovereign and public-interest workloads.'],
  ['Infrastructure investors', 'Participation in a gated, asset-led development process.'], ['Energy & technology partners', 'Power, engineering, equipment and operations collaboration.'],
]

export default function ComputeInfrastructure() {
  useEffect(() => {
    const title = document.title
    const description = document.querySelector('meta[name="description"]')?.getAttribute('content')
    const canonical = document.querySelector<HTMLLinkElement>('link[rel="canonical"]')
    const oldCanonical = canonical?.href
    document.title = 'Albedo Compute Infrastructure — Modular AI Data Center Project'
    document.querySelector('meta[name="description"]')?.setAttribute('content', 'Albedo Industries is evaluating a modular, energy-first AI compute facility in northern Spain, developed through verified demand and phased deployment.')
    canonical?.setAttribute('href', 'https://www.albedo-industries.com/#/compute-infrastructure')
    const ogTitle = document.querySelector('meta[property="og:title"]')
    const ogDescription = document.querySelector('meta[property="og:description"]')
    const oldOgTitle = ogTitle?.getAttribute('content'); const oldOgDescription = ogDescription?.getAttribute('content')
    ogTitle?.setAttribute('content', 'Albedo Compute Infrastructure — Modular AI Data Center Project')
    ogDescription?.setAttribute('content', 'A demand-led, modular AI data-center project for northern Spain.')
    return () => { document.title = title; if (description) document.querySelector('meta[name="description"]')?.setAttribute('content', description); if (oldCanonical) canonical?.setAttribute('href', oldCanonical); if (oldOgTitle) ogTitle?.setAttribute('content', oldOgTitle); if (oldOgDescription) ogDescription?.setAttribute('content', oldOgDescription) }
  }, [])
  return <div>
    <section className="bg-zinc-950 text-white overflow-hidden"><div className="max-w-5xl mx-auto px-6 pt-24 pb-20 md:pt-36 md:pb-28">
      <span className="inline-flex rounded-full border border-amber-300/30 bg-amber-300/10 px-3 py-1 text-xs text-amber-200 mb-8">Current stage: site, energy and demand assessment</span>
      <p className="uppercase tracking-[.22em] text-xs text-zinc-500 mb-5">Albedo Compute Infrastructure · Northern Spain</p>
      <h1 className="text-4xl md:text-7xl font-semibold tracking-tight max-w-4xl">Infrastructure for the next generation of AI.</h1>
      <p className="mt-7 text-lg md:text-xl text-zinc-400 leading-relaxed max-w-3xl">Albedo Industries is evaluating a modular compute facility designed to combine reliable power, efficient infrastructure and phased expansion. The first deployment will proceed only when the location, energy route, demand and financing satisfy defined project gates.</p>
      <div className="flex flex-wrap gap-3 mt-10"><a href="#capacity-interest" className="rounded-lg bg-white text-zinc-950 px-6 py-3 text-sm font-medium">Register capacity interest</a><a href="#partner-interest" className="rounded-lg border border-zinc-700 px-6 py-3 text-sm font-medium">Register investor or partner interest</a></div>
    </div></section>

    <Section eyebrow="Why this project" title="Scale infrastructure after demand—not ahead of it."><div className="grid md:grid-cols-2 gap-5">{['AI workloads are increasing demand for computing infrastructure.','Power availability, deployment time and capital intensity constrain new facilities.','Traditional projects can require large commitments before demand is demonstrated.','A smaller first phase allows later blocks to be triggered by verified demand.'].map((x,i)=><div className="border-t border-zinc-300 pt-4 text-zinc-600" key={x}><span className="text-xs text-zinc-400">0{i+1}</span><p className="mt-2">{x}</p></div>)}</div></Section>
    <Section eyebrow="Core thesis" title="Four principles guide every development gate." tone="soft"><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{thesis.map(([a,b])=><article className="rounded-xl border border-zinc-200 bg-white p-6" key={a}><h3 className="font-semibold mb-3">{a}</h3><p className="text-sm text-zinc-600 leading-relaxed">{b}</p></article>)}</div></Section>
    <Section id="candidate-locations" eyebrow="Potential locations" title="Candidate regions, not selected sites."><p className="text-zinc-600 max-w-3xl mb-10">No parcel, grid connection or planning consent is represented as secured. Candidate regions are compared on infrastructure feasibility before site control is pursued.</p><div className="grid md:grid-cols-2 gap-6">{regions.map(r=><article className="rounded-xl border border-zinc-200 p-6" key={r.name}><span className="text-xs text-amber-700">Candidate region — not yet selected</span><h3 className="text-2xl font-semibold mt-3">{r.name}</h3><p className="text-sm text-zinc-500 mt-1 mb-5">{r.note}</p><ul className="grid gap-2 text-sm text-zinc-600">{r.criteria.map(c=><li key={c}>— {c}</li>)}</ul></article>)}</div></Section>
    <Section eyebrow="Energy strategy" title="Power is the first design constraint." tone="dark"><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-px bg-zinc-800 border border-zinc-800">{['Grid connection','Existing industrial capacity','Renewable contracts or PPAs','Battery storage where justified','Backup power and resilience','Future heat reuse','Continuous energy monitoring'].map((x,i)=><div key={x} className="bg-zinc-950 p-5"><span className="text-xs text-zinc-600">0{i+1}</span><h3 className="text-sm mt-5">{x}</h3></div>)}</div><p className="mt-8 text-zinc-400 max-w-3xl">The final energy architecture will depend on the selected site, confirmed connection capacity, regulatory requirements and contracted supply. On-site generation or storage would complement—not replace—the resilient supply needed for continuous operation.</p></Section>
    <Section eyebrow="Modular infrastructure" title="Repeatable blocks. Integrated systems."><div className="grid md:grid-cols-3 gap-4 mb-8">{[['Phase 1','Core power, cooling, network and initial compute capacity'],['Phase 2','Additional data hall or compute block'],['Phase 3','Further capacity and supporting infrastructure']].map(([a,b],i)=><article key={a} className="relative rounded-xl border border-zinc-300 p-6"><div className="h-2 bg-zinc-900 mb-8" style={{width:`${45+i*25}%`}}/><p className="text-xs text-zinc-400">{a}</p><h3 className="mt-2 text-sm font-medium">{b}</h3></article>)}</div><div className="flex flex-wrap gap-2">{['Core Infrastructure Block','Compute Block','Cooling Block','Power Block','Network','Controls','Security'].map(x=><span className="border border-zinc-300 rounded-md px-3 py-2 text-xs" key={x}>{x}</span>)}</div><p className="mt-7 text-zinc-600 max-w-3xl">Modular means standardized, repeatable and maintainable deployment—not improvised shipping containers. Every phase must integrate power, cooling, IT space, network, controls and security.</p></Section>
    <Section eyebrow="Potential services" title="What could be offered" tone="soft"><p className="text-sm text-zinc-500 mb-8">Planned service categories — final offering subject to demand and technical design.</p><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{services.map(x=><div className="bg-white border border-zinc-200 rounded-lg p-4 text-sm" key={x}>{x}</div>)}</div></Section>
    <Section eyebrow="Who it is for" title="Infrastructure shaped around concrete workloads."><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-x-6 gap-y-8">{audiences.map(([a,b])=><article key={a}><h3 className="font-medium">{a}</h3><p className="text-sm text-zinc-500 mt-2 leading-relaxed">{b}</p></article>)}</div></Section>
    <Section id="development-gates" eyebrow="Development gates" title="A conservative path to a construction decision." tone="dark"><div className="divide-y divide-zinc-800 border-y border-zinc-800">{developmentGates.map(([name,status],i)=><div className="grid grid-cols-[2rem_1fr_auto] gap-4 py-4 items-center" key={name}><span className="text-xs text-zinc-600">{String(i+1).padStart(2,'0')}</span><span className="text-sm">{name}</span><span className={status==='In progress'?'text-xs text-amber-300':'text-xs text-zinc-500'}>{status}</span></div>)}</div></Section>
    <Section eyebrow="Project updates" title="What has changed—and what has not."><div className="space-y-4">{projectUpdates.map((update)=><article className="rounded-xl border border-zinc-200 p-6 md:p-8" key={update.title}><div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-zinc-500"><span>{update.status}</span><span aria-hidden="true">·</span><time dateTime={update.dateTime}>{update.date}</time></div><h3 className="mt-4 text-xl font-semibold">{update.title}</h3><p className="mt-3 max-w-3xl text-zinc-600 leading-relaxed">{update.body}</p></article>)}</div></Section>
    <Section eyebrow="Funding model" title="Staged capital, subject to legal structure."><p className="text-zinc-600 text-lg leading-relaxed max-w-3xl">The project is exploring a staged financing model combining sponsor capital, strategic partners, commercial commitments and potentially regulated community participation.</p><aside className="mt-8 rounded-xl border border-zinc-300 bg-zinc-50 p-6 text-sm text-zinc-600 max-w-3xl"><strong className="text-zinc-900">Important notice.</strong> No investment product, security or guaranteed return is currently being offered through this website. Any future investment opportunity would be subject to the appropriate legal, financial and regulatory structure.</aside></Section>
    <section id="capacity-interest" className="border-t border-zinc-200"><div className="max-w-5xl mx-auto px-6 py-20 md:py-28"><p className="eyebrow">Demand registration</p><h2 className="section-title">Register future capacity interest</h2><p className="section-copy">Tell us what a useful first deployment would need to support. This is not a reservation or payment.</p><ComputeInterestForm kind="capacity" /></div></section>
    <section id="partner-interest" className="border-t border-zinc-200 bg-zinc-50"><div className="max-w-5xl mx-auto px-6 py-20 md:py-28"><p className="eyebrow">Investor & partner interest</p><h2 className="section-title">Help test the development route.</h2><p className="section-copy">For capital, energy, land, engineering, equipment, operations and institutional partners. Expressions are non-binding.</p><ComputeInterestForm kind="investor" /></div></section>
  </div>
}

function Section({ children, eyebrow, title, tone='light', id }: { children: React.ReactNode; eyebrow: string; title: string; tone?: 'light'|'soft'|'dark'; id?: string }) {
  return <section id={id} className={`border-t ${tone==='dark'?'bg-zinc-950 text-white border-zinc-800':tone==='soft'?'bg-zinc-50 border-zinc-200':'bg-white border-zinc-200'}`}><div className="max-w-5xl mx-auto px-6 py-20 md:py-28"><p className={tone==='dark'?'eyebrow text-zinc-500':'eyebrow'}>{eyebrow}</p><h2 className="section-title">{title}</h2>{children}</div></section>
}
