import { Link } from 'react-router-dom'
const contact='mailto:alex@albedo-industries.com?subject=FastSoftware%20workflow'
export default function FastSoftware(){return <article>
 <header className="bg-zinc-950 text-white"><div className="mx-auto flex min-h-[82svh] max-w-6xl flex-col justify-center px-5 py-24 sm:px-6"><p className="text-xs font-bold uppercase tracking-[.22em] text-zinc-400">FastSoftware</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold leading-[.96] tracking-[-.04em] md:text-7xl">Operational software built around real work.</h1><p className="mt-7 max-w-2xl text-lg text-zinc-300">Focused systems that connect fragmented workflows, operational data and human-reviewed automation.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#systems" className="inline-flex min-h-12 items-center justify-center bg-white px-6 text-sm font-semibold text-zinc-950">See what we built</a><a href={contact} className="inline-flex min-h-12 items-center justify-center border border-zinc-600 px-6 text-sm font-semibold">Discuss a workflow</a></div></div></header>
 <Section id="systems" eyebrow="02 · Real systems" title="Proof you can see."><div className="grid gap-6 lg:grid-cols-2"><System name="Foreman" status="Building" to="/foreman" video="/media/foreman/foreman-po-workflow.mp4">Construction purchasing and site operations in one working interface.</System><System name="Purchasing Agent" status="Demonstration" to="/fastsoftware/purchasing-agent" video="/media/foreman/foreman-invoice-workflow.mp4">Structured supplier comparison with human review kept in control.</System></div></Section>
 <Section dark id="method" eyebrow="03 · Method" title="Start with the work."><ol className="flex flex-col gap-5 text-4xl font-semibold md:flex-row md:items-center md:gap-8 md:text-6xl">{['UNDERSTAND','BUILD','INTEGRATE'].map((x,i)=><li className="contents" key={x}><span>{x}</span>{i<2&&<span className="text-amber-300 max-md:rotate-90">→</span>}</li>)}</ol><p className="mt-8 text-sm text-zinc-400">Measure and expand after use.</p></Section>
 <Section id="capabilities" eyebrow="04 · Capabilities" title="Systems, integrations and useful automation."><div className="grid gap-8 md:grid-cols-3"><Cap title="Operational systems">Dashboards and workflows shaped around operators.</Cap><Cap title="Integration">Connect documents, email, databases and existing tools.</Cap><Cap title="AI assistance">Extract, compare and surface exceptions for human review.</Cap></div><Link to="/projects" className="mt-9 inline-flex font-semibold underline decoration-amber-400 underline-offset-4">Explore deeper proof →</Link></Section>
 <section className="bg-amber-300"><div className="mx-auto flex max-w-6xl flex-col gap-8 px-5 py-20 sm:px-6 md:flex-row md:items-center md:justify-between"><h2 className="max-w-3xl text-4xl font-semibold tracking-tight md:text-6xl">Bring the workflow that should work better.</h2><a href={contact} className="inline-flex min-h-12 shrink-0 items-center justify-center bg-zinc-950 px-6 text-sm font-semibold text-white">Discuss a workflow</a></div></section>
 </article>}
function Section({id,eyebrow,title,children,dark=false}:{id:string;eyebrow:string;title:string;children:React.ReactNode;dark?:boolean}){return <section id={id} className={`border-b ${dark?'border-zinc-800 bg-zinc-950 text-white':'border-zinc-300 bg-white'}`}><div className="mx-auto max-w-6xl px-5 py-20 sm:px-6 md:py-28"><p className="text-xs font-bold uppercase tracking-[.18em] text-zinc-500">{eyebrow}</p><h2 className="mt-4 max-w-4xl text-4xl font-semibold tracking-tight md:text-6xl">{title}</h2><div className="mt-12">{children}</div></div></section>}
function System({name,status,to,video,children}:{name:string;status:string;to:string;video:string;children:React.ReactNode}){return <article className="overflow-hidden bg-zinc-950 text-white"><video className="aspect-[16/10] w-full object-cover" muted loop autoPlay playsInline preload="metadata"><source src={video} type="video/mp4"/></video><div className="p-7"><span className="text-xs font-bold uppercase tracking-[.14em] text-amber-200">{status}</span><h3 className="mt-3 text-3xl font-semibold">{name}</h3><p className="mt-3 text-zinc-400">{children}</p><Link to={to} className="mt-6 inline-flex min-h-11 items-center font-semibold underline underline-offset-4">Review system →</Link></div></article>}
function Cap({title,children}:{title:string;children:React.ReactNode}){return <article className="border-t-2 border-zinc-950 pt-5"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 text-zinc-600">{children}</p></article>}
