import { Link } from 'react-router-dom'
import HeroVideo from '../components/HeroVideo'
import DisplayAssetFigure from '../components/display/DisplayAssetFigure'
import { displayAssets } from '../data/albedoDisplayAssets'
import { atlasPipeline } from '../data/atlasPipeline'

const opportunity=atlasPipeline.find(item=>item.publication.homepageFeatured)
const partner='mailto:alex@albedo-industries.com?subject=ALBEDO%20investment%20or%20partnership'

export default function Home(){return <article>
  <section className="hero-video-section relative isolate flex min-h-[94svh] items-center overflow-hidden bg-[radial-gradient(circle_at_72%_28%,#3f3f46_0%,#18181b_42%,#09090b_78%)] text-white">
    <HeroVideo src="/media/ALBEDO - INDUSTRIES/weryai_5bb6aefbba19268f1e7c90c34015e82f.mp4" className="object-[60%_50%] sm:object-center"/>
    <div className="absolute inset-0 bg-gradient-to-r from-black/90 via-black/60 to-black/25"/><div className="absolute inset-0 bg-gradient-to-t from-black/55 via-transparent to-black/35"/>
    <div className="relative mx-auto w-full max-w-6xl px-5 py-28 sm:px-6"><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-200">ALBEDO Industries · AI infrastructure</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold leading-[.96] tracking-[-.045em] sm:text-6xl md:text-8xl">Building the physical layer of AI.</h1><p className="mt-7 max-w-2xl text-lg leading-relaxed text-zinc-200">ALBEDO develops data-center infrastructure through Project Atlas, alongside physical systems, software and frontier research for future compute.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/atlas" className="inline-flex min-h-12 items-center justify-center bg-white px-6 text-sm font-semibold text-zinc-950">Explore Project Atlas</Link><Link to="/atlas/partners" className="inline-flex min-h-12 items-center justify-center border border-amber-300 px-6 text-sm font-semibold text-amber-100">Invest / Partner</Link></div><div className="mt-12 flex flex-wrap gap-x-6 gap-y-2 text-[.68rem] font-bold uppercase tracking-[.14em] text-zinc-300"><span>Atlas · Today</span><span>Orbital · Next</span><span>Display · Interface</span><span>Software · Operations</span></div></div>
  </section>

  <section className="bg-zinc-950 text-white"><div className="mx-auto max-w-6xl px-5 py-20 sm:px-6 md:py-28"><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-200">Project Atlas · Primary initiative</p><h2 className="mt-4 max-w-5xl text-4xl font-semibold tracking-tight sm:text-5xl md:text-6xl">From infrastructure opportunity to investable data-center project.</h2><p className="mt-6 max-w-2xl text-lg text-zinc-400">Atlas advances selected opportunities through power, land, development evidence and aligned capital.</p>{opportunity&&<article className="mt-12 grid gap-8 bg-white p-6 text-zinc-950 md:grid-cols-[1fr_1.4fr] md:p-10"><div><span className="text-xs font-bold uppercase tracking-[.15em] text-zinc-500">Featured opportunity</span><h3 className="mt-3 text-4xl font-semibold">{opportunity.name}</h3><p className="mt-2 text-zinc-500">{opportunity.market}</p></div><div className="grid gap-6 sm:grid-cols-3"><Fact label="Scale" value={opportunity.scale}/><Fact label="Stage" value={opportunity.stage}/><Fact label="Next gate" value={opportunity.nextMilestone}/></div></article>}<div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/atlas" className="inline-flex min-h-12 items-center justify-center bg-white px-6 text-sm font-semibold text-zinc-950">Explore Atlas</Link><Link to="/atlas?section=pipeline" className="inline-flex min-h-12 items-center justify-center border border-zinc-600 px-6 text-sm font-semibold">View opportunities</Link></div></div></section>

  <section className="relative overflow-hidden bg-[#101114] text-white"><div className="pointer-events-none absolute left-[65%] top-1/2 h-[38rem] w-[38rem] -translate-y-1/2 rounded-full border border-zinc-700"/><div className="relative mx-auto grid max-w-6xl gap-14 px-5 py-24 sm:px-6 md:py-32 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-zinc-400">Albedo Orbital · Research / pre-development</p><h2 className="mt-4 text-5xl font-semibold tracking-tight md:text-7xl">Compute beyond Earth.</h2><p className="mt-6 max-w-xl text-lg text-zinc-400">Researching how autonomous compute could operate progressively further from terrestrial grids.</p><div className="mt-9 flex gap-5"><Link to="/orbital" className="font-semibold underline decoration-amber-300 underline-offset-4">Explore Orbital</Link><Link to="/orbital/research" className="text-zinc-400 underline underline-offset-4">Research the bottlenecks</Link></div></div><ol className="space-y-2 text-xl font-semibold"><li>EARTH</li><li className="text-amber-300">↓</li><li>AUTONOMOUS COMPUTE</li><li className="text-amber-300">↓</li><li>EXTREME INFRASTRUCTURE</li><li className="text-amber-300">↓</li><li>ORBIT</li></ol></div></section>

  <section className="bg-[#f1f1eb]"><div className="mx-auto grid max-w-7xl gap-5 px-5 py-20 sm:px-6 md:py-28 lg:grid-cols-2"><Tile title="Information that stays visible." eyebrow="Albedo Display · Pre-prototype" copy="A persistent physical information interface for infrastructure." to="/display" cta="Explore Display"><DisplayAssetFigure asset={displayAssets.heroConcept} priority/></Tile><Tile dark title="Operational software built around real work." eyebrow="FastSoftware · Foreman" copy="Focused systems for physical operations and human-reviewed workflows." to="/fastsoftware" cta="Explore Software"><video className="aspect-[16/10] w-full bg-zinc-900 object-cover" muted loop autoPlay playsInline preload="metadata" aria-label="Foreman purchasing workflow interface"><source src="/media/foreman/foreman-po-workflow.mp4" type="video/mp4"/></video></Tile></div></section>

  <section className="bg-amber-300"><div className="mx-auto max-w-6xl px-5 py-20 sm:px-6 md:py-24"><h2 className="max-w-4xl text-4xl font-semibold tracking-tight md:text-6xl">Build the infrastructure for what comes next.</h2><div className="mt-9 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><Link to="/atlas/partners" className="inline-flex min-h-12 items-center justify-center bg-zinc-950 px-6 text-sm font-semibold text-white">Investment / co-development</Link><a href="mailto:alex@albedo-industries.com?subject=Infrastructure%20opportunity" className="inline-flex min-h-12 items-center justify-center border border-zinc-950 px-6 text-sm font-semibold">Bring an opportunity</a><a href={partner} className="inline-flex min-h-12 items-center justify-center px-4 text-sm font-semibold underline underline-offset-4">Strategic / technical partnership</a></div></div></section>
</article>}

function Fact({label,value}:{label:string;value:string}){return <div><p className="text-[.65rem] font-bold uppercase tracking-[.15em] text-zinc-500">{label}</p><p className="mt-2 text-sm font-semibold leading-relaxed">{value}</p></div>}
function Tile({title,eyebrow,copy,to,cta,children,dark=false}:{title:string;eyebrow:string;copy:string;to:string;cta:string;children:React.ReactNode;dark?:boolean}){return <article className={`flex flex-col p-6 md:p-9 ${dark?'bg-zinc-950 text-white':'bg-white'}`}><div className="mb-8">{children}</div><p className={`text-xs font-bold uppercase tracking-[.16em] ${dark?'text-zinc-400':'text-zinc-500'}`}>{eyebrow}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight md:text-5xl">{title}</h2><p className={`mt-4 text-sm ${dark?'text-zinc-400':'text-zinc-600'}`}>{copy}</p><Link to={to} className="mt-7 inline-flex min-h-11 items-center font-semibold underline decoration-amber-400 underline-offset-4">{cta} →</Link></article>}
