import { Link } from 'react-router-dom'

const activities=[
  {title:'FastSoftware',body:'Focused internal tools, operational systems and practical AI agents delivered around real company workflows.',to:'/fastsoftware'},
  {title:'Mobility Infrastructure',body:'Parking, access, EV charging and vehicle-security systems for operators, communities and private sites.',to:'/projects/alb-parking'},
  {title:'Local AI & Compute',body:'Private local AI systems and distributed-compute research for controlled workloads and company data.',to:'/projects/albedo-nodes'},
]

export default function Home(){return <div>
  <section className="hero-video-section relative flex min-h-[560px] items-center overflow-hidden md:min-h-[680px]"><video className="hero-video absolute inset-0 size-full object-cover" autoPlay muted loop playsInline preload="metadata"><source src={`${import.meta.env.BASE_URL || '/'}media/ALBEDO - INDUSTRIES/weryai_5bb6aefbba19268f1e7c90c34015e82f.mp4`} type="video/mp4" /></video><div className="absolute inset-0 bg-black/65"/><div className="relative z-10 mx-auto w-full max-w-5xl px-6 py-24"><p className="text-xs font-semibold tracking-[.2em] text-amber-200">ALBEDO INDUSTRIES</p><h1 className="mt-5 max-w-4xl text-4xl font-semibold leading-[1.08] tracking-tight text-white md:text-6xl lg:text-7xl">Building practical systems—and originating the infrastructure behind tomorrow’s compute.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-zinc-300">Albedo works across software, mobility and compute infrastructure, turning operational questions into focused products and evidence-led opportunities.</p></div></section>

  <section className="bg-zinc-950 text-white"><div className="mx-auto grid max-w-5xl gap-10 px-6 py-16 md:grid-cols-[1.35fr_.65fr] md:items-end md:py-20"><div><p className="text-xs font-semibold tracking-[.2em] text-amber-200">PROJECT ATLAS · AI INFRASTRUCTURE</p><h2 className="mt-4 text-3xl font-semibold tracking-tight md:text-5xl">Finding viable locations for the next generation of AI infrastructure.</h2><p className="mt-5 max-w-2xl text-lg leading-relaxed text-zinc-300">Project Atlas originates and validates selected international opportunities through evidence on power, land, connectivity, permitting and demand.</p></div><div className="flex flex-col gap-3"><Link to="/infrastructure/atlas" className="inline-flex min-h-12 items-center justify-center rounded-full bg-white px-6 text-sm font-semibold text-zinc-950 hover:bg-zinc-100">Explore Project Atlas</Link><Link to="/infrastructure/atlas/partners" className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/30 px-6 text-center text-sm font-semibold hover:bg-white/10">Discuss investment or partnership</Link></div></div></section>

  <section className="border-t border-zinc-200"><div className="mx-auto max-w-5xl px-6 py-16 md:py-20"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Other Albedo activities</p><h2 className="max-w-2xl text-3xl font-semibold tracking-tight md:text-4xl">Focused systems for software, mobility and local compute.</h2></div><Link to="/projects" className="text-sm font-semibold underline decoration-amber-500 underline-offset-4">View the complete portfolio</Link></div><div className="mt-10 grid gap-5 md:grid-cols-3">{activities.map(activity=><Link to={activity.to} className="group rounded-2xl border border-zinc-200 p-6 transition-colors hover:border-zinc-400" key={activity.title}><h3 className="text-xl font-semibold">{activity.title}</h3><p className="mt-3 text-sm leading-relaxed text-zinc-600">{activity.body}</p><span className="mt-6 inline-flex text-sm font-semibold group-hover:translate-x-1 motion-safe:transition-transform">Learn more →</span></Link>)}</div></div></section>

  <section className="border-t border-zinc-800 bg-zinc-950 text-white"><div className="mx-auto flex max-w-5xl flex-col gap-6 px-6 py-14 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-semibold">Start with the opportunity or requirement.</h2><p className="mt-2 max-w-2xl text-sm text-zinc-400">Talk to Albedo about Atlas, operational software, mobility infrastructure or local AI systems.</p></div><a href="mailto:alex@albedo-industries.com?subject=Albedo%20Industries%20conversation" className="inline-flex min-h-12 shrink-0 items-center justify-center rounded-full bg-white px-6 text-sm font-semibold text-zinc-950">Start a conversation</a></div></section>
</div>}
