import { Link } from 'react-router-dom'
import { useAtlasMetadata } from '../hooks/useAtlasMetadata'

const contact='mailto:alex@albedo-industries.com?subject=Project%20Atlas%20%E2%80%94%20investment%20or%20partnership&body=Hello%20Atlas%2C%0A%0AI%20am%20contacting%20you%20as%20an%20investor%20%2F%20operator%20%2F%20energy%20or%20fibre%20partner%20%2F%20land%20or%20development%20partner%20%2F%20public%20institution%20%2F%20other.%0A%0AOrganization%3A%0ARequirements%20or%20opportunity%3A'
export default function InfrastructureFunding(){useAtlasMetadata({name:'Investment & Partnerships',country:'International',title:'Project Atlas — Investment & Partnerships | Albedo Industries',description:'Investment, operating and infrastructure partnerships for evidence-led validation and development of selected Project Atlas locations.',route:'/infrastructure/atlas/partners'});return <div>
<section className="bg-zinc-950 text-white"><div className="mx-auto max-w-6xl px-6 py-24 md:py-32"><Link to="/infrastructure/atlas" className="text-sm text-zinc-400">← Project Atlas</Link><p className="mt-10 eyebrow text-amber-200">INVESTMENT &amp; PARTNERSHIPS</p><h1 className="max-w-5xl text-4xl font-semibold tracking-tight md:text-6xl">Capital and partnerships for evidence-led AI infrastructure development.</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-zinc-300">Atlas is seeking conversations with investors, operators and infrastructure partners who can help validate and advance selected locations. No investment offer is currently open through this website.</p><a href={contact} className="mt-9 inline-flex min-h-12 items-center rounded-full bg-white px-6 text-sm font-semibold text-zinc-950">Start a confidential conversation</a></div></section>
<Section eyebrow="What Atlas is seeking now" title="The inputs that turn research into evidence"><div className="grid gap-5 sm:grid-cols-2">{[['Validation capital','Funding for grid studies, site screening, fibre validation, legal work and preliminary engineering.'],['Development partners','Experienced partners in data centres, energy, engineering, construction and site development.'],['Operators and customers','Data-centre, GPU cloud and AI-compute companies willing to define requirements or assess candidates.'],['Local infrastructure','Utilities, industrial parks, landowners and fibre providers able to validate specific opportunities.']].map(x=><article className="rounded-2xl border border-zinc-200 p-6" key={x[0]}><h3 className="text-xl font-semibold">{x[0]}</h3><p className="mt-3 text-zinc-600">{x[1]}</p></article>)}</div></Section>
<Section eyebrow="How capital follows evidence" title="Three phases, each earned"><ol className="grid gap-4 md:grid-cols-3">{['Research and validation','Site control and preliminary development','Project financing and delivery'].map((x,i)=><li className="rounded-2xl bg-zinc-950 p-6 text-white" key={x}><span className="text-xs text-amber-200">0{i+1}</span><h3 className="mt-4 text-xl font-semibold">{x}</h3></li>)}</ol><p className="mt-6 text-zinc-600">Each phase proceeds only when the evidence and counterparties justify it. Later development and delivery are not guaranteed.</p></Section>
<Section eyebrow="Current position" title="Published research; no public offer"><ul className="grid gap-3 md:grid-cols-2">{['Atlas has published candidate research.','Institutional and market outreach is active.','No public investment offer is open.','Expressions of interest are non-binding.','Project-specific structures would be defined before accepting capital.'].map(x=><li className="rounded-xl border border-zinc-200 p-4" key={x}>✓ {x}</li>)}</ul></Section>
<section className="bg-zinc-950 text-white"><div className="mx-auto max-w-6xl px-6 py-20 md:py-24"><h2 className="max-w-4xl text-3xl font-semibold md:text-5xl">Help advance evidence-backed AI infrastructure opportunities.</h2><p className="mt-5 max-w-3xl text-zinc-300">Atlas is speaking with investors, operators and infrastructure partners able to validate requirements, fund early development work or contribute location-specific capabilities.</p><a href={contact} className="mt-8 inline-flex min-h-12 items-center rounded-full bg-white px-6 text-sm font-semibold text-zinc-950">Start a confidential conversation</a><p className="mt-6 text-xs text-zinc-500">This website does not offer securities or accept investor funds.</p></div></section></div>}
function Section({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <section className="border-t border-zinc-200"><div className="mx-auto max-w-6xl px-6 py-20 md:py-28"><p className="eyebrow">{eyebrow}</p><h2 className="section-title">{title}</h2>{children}</div></section>}
