import { Link } from 'react-router-dom'
import { atlasCandidateRegistry } from '../data/atlasCandidates'
import { infrastructureCandidates } from '../data/infrastructureCandidates'
import { useAtlasMetadata } from '../hooks/useAtlasMetadata'

const featuredIds=['LATAM-UY-01','EU-ES-04','EU-PT-01','EU-ES-01']
const publicStatus=(id:string)=>id==='EU-FI-02'?'Closed After Research':featuredIds.includes(id)?'Continue Validation':'Early Research'

export default function InfrastructureEurope({country}:{country?:string}){
  useAtlasMetadata({name:country?`${country} Atlas Research`:'Project Atlas',country:country??'International',description:'Independent site origination and validation for AI infrastructure across selected international locations.',route:country?`/infrastructure/${country.toLowerCase()}`:'/infrastructure/atlas'})
  const registry=new Map(atlasCandidateRegistry.map(c=>[c.id,c]))
  const all=[...registry.values(),...infrastructureCandidates.filter(c=>!registry.has(c.id)).map(c=>({id:c.id,route:c.route,country:c.country,name:c.name,summary:c.summary,primaryBlocker:c.topBlocker}))]
  const scoped=country?all.filter(c=>c.country===country):all
  const featured=featuredIds.map(id=>all.find(c=>c.id===id)).filter((c):c is NonNullable<typeof c>=>Boolean(c)).filter(c=>!country||c.country===country)
  const archive=scoped.filter(c=>!featuredIds.includes(c.id))
  return <div>
    <section className="bg-zinc-950 text-white"><div className="mx-auto max-w-6xl px-6 py-24 md:py-32"><p className="eyebrow text-amber-200">PROJECT ATLAS</p><h1 className="max-w-4xl text-4xl font-semibold tracking-tight md:text-7xl">Originating and validating locations for AI infrastructure.</h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-zinc-300">Atlas identifies potential data-centre and AI-compute locations, tests the evidence behind them and works with local stakeholders, operators and capital partners to determine which opportunities deserve to advance.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to={{hash:'#opportunities'}} className="inline-flex min-h-12 items-center justify-center rounded-full bg-white px-6 text-sm font-semibold text-zinc-950">View active opportunities</Link><Link to="/infrastructure/atlas/partners" className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/30 px-6 text-sm font-semibold">Investor or partner enquiry</Link></div><p className="mt-8 max-w-3xl border-l border-amber-300 pl-4 text-sm text-zinc-400">Atlas candidates are research-stage opportunities. Power, land, customers and financing are not secured unless explicitly stated.</p></div></section>
    <Section eyebrow="What Atlas does" title="Independent site origination and validation for AI infrastructure."><div className="grid gap-5 md:grid-cols-3">{[['01','Originate','Identify locations where energy, industrial land and connectivity may create an opportunity.'],['02','Validate','Test grid access, site control, fibre, permitting, risk and customer demand.'],['03','Advance','Build the partnerships, technical evidence and financing required for the strongest candidates.']].map(x=><article className="rounded-2xl border border-zinc-200 p-6" key={x[1]}><p className="text-xs text-zinc-400">{x[0]}</p><h3 className="mt-4 text-xl font-semibold">{x[1]}</h3><p className="mt-3 text-sm leading-relaxed text-zinc-600">{x[2]}</p></article>)}</div></Section>
    <section id="opportunities" className="scroll-mt-24 border-t border-zinc-200 bg-zinc-50"><div className="mx-auto max-w-6xl px-6 py-20 md:py-28"><p className="eyebrow">Active opportunities</p><h2 className="section-title">Research ready for the next conversation.</h2><div className="grid gap-5 md:grid-cols-2">{featured.map(c=><CandidateCard key={c.id} candidate={c}/>)}</div></div></section>
    <Section eyebrow="Research archive" title="Earlier hypotheses and retained research"><div className="divide-y divide-zinc-200 border-y border-zinc-200">{archive.map(c=><Link to={c.route} key={c.id} className="grid gap-2 py-5 hover:text-zinc-600 sm:grid-cols-[8rem_1fr_11rem]"><span className="text-xs text-zinc-500">{c.id}</span><span><strong>{c.name}</strong><span className="ml-2 text-sm text-zinc-500">{c.country}</span></span><span className="text-sm">{publicStatus(c.id)}</span></Link>)}</div></Section>
    <Section eyebrow="Why work with Atlas" title="Bring requirements, evidence or capital."><div className="grid gap-6 md:grid-cols-3">{[['For operators','Discover researched locations and define infrastructure requirements.'],['For investors','Support evidence-led origination and early development work.'],['For local partners','Contribute land, energy, fibre, engineering or institutional knowledge.']].map(x=><div key={x[0]}><h3 className="text-xl font-semibold">{x[0]}</h3><p className="mt-3 text-zinc-600">{x[1]}</p></div>)}</div></Section>
    <section className="bg-zinc-950 text-white"><div className="mx-auto max-w-6xl px-6 py-20 md:py-24"><h2 className="text-3xl font-semibold md:text-5xl">Help advance the next viable Atlas location.</h2><p className="mt-5 max-w-2xl text-zinc-400">We are speaking with infrastructure investors, operators, utilities, land partners and local institutions.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/infrastructure/atlas/partners" className="rounded-full bg-white px-6 py-3 text-center text-sm font-semibold text-zinc-950">Discuss investment or partnership</Link><a href="mailto:alex@albedo-industries.com?subject=Project%20Atlas%20enquiry" className="rounded-full border border-white/30 px-6 py-3 text-center text-sm font-semibold">Contact Project Atlas</a></div></div></section>
  </div>
}
function CandidateCard({candidate:c}:{candidate:{id:string;route:string;country:string;name:string;summary:string;primaryBlocker:string}}){return <article className="rounded-2xl border border-zinc-200 bg-white p-6 md:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-bold tracking-wider text-zinc-500">{c.id} · {c.country}</p><span className="rounded-full border border-amber-300 bg-amber-50 px-3 py-1 text-xs font-semibold">Status: {publicStatus(c.id)}</span></div><h3 className="mt-5 text-3xl font-semibold">{c.name}</h3><p className="mt-4 text-zinc-600">{c.summary}</p><p className="mt-4 text-sm"><strong>Key unresolved condition:</strong> {c.primaryBlocker}</p><Link className="mt-7 inline-flex font-semibold underline decoration-amber-400 underline-offset-4" to={c.route}>View opportunity →</Link></article>}
function Section({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <section className="border-t border-zinc-200"><div className="mx-auto max-w-6xl px-6 py-20 md:py-28"><p className="eyebrow">{eyebrow}</p><h2 className="section-title">{title}</h2>{children}</div></section>}
