import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ResearchIndicators } from '../components/ResearchIndicators'
import { infrastructureCandidates } from '../data/infrastructureCandidates'
import { atlasCandidateRegistry, atlasCandidateRegistryByRoute } from '../data/atlasCandidates'
import { useAtlasMetadata } from '../hooks/useAtlasMetadata'

export default function InfrastructureEurope({ country }: { country?: string }) {
  const [countryFilter,setCountryFilter]=useState(country || 'all'); const [classification,setClassification]=useState('all'); const [power,setPower]=useState('all'); const [fiber,setFiber]=useState('all'); const [demand,setDemand]=useState('all'); const [updated,setUpdated]=useState('all'); const [sort,setSort]=useState('updated')
  const countries=[...new Set(infrastructureCandidates.map(c=>c.country))].sort()
  const registrationEnabled=Boolean((import.meta.env.VITE_COMPUTE_INTEREST_ENDPOINT as string|undefined)?.trim())
  const countrySlugs:Record<string,string>={Spain:'spain',Portugal:'portugal',Germany:'germany',France:'france',Sweden:'sweden',Finland:'finland',Norway:'norway',Poland:'poland'}
  const results=infrastructureCandidates.filter(c=>(countryFilter==='all'||c.country===countryFilter)&&(classification==='all'||c.classification===classification)&&(power==='all'||c.categories[0].state===power)&&(fiber==='all'||c.categories[1].state===fiber)&&(demand==='all'||(registrationEnabled?'registration_open':'not_started')===demand)&&(updated==='all'||c.lastUpdated>='2026-07-01')).sort((a,b)=>sort==='coverage'?b.categories.filter(item=>item.sourceIds.length>0).length-a.categories.filter(item=>item.sourceIds.length>0).length:sort==='country'?a.country.localeCompare(b.country):sort==='gate'?a.currentGate.localeCompare(b.currentGate):b.lastUpdated.localeCompare(a.lastUpdated))
  useEffect(()=>{const old=document.title;const title=country?`${country} AI Infrastructure Research | Albedo Industries`:'European AI Infrastructure Research | Albedo Industries';document.title=title;return()=>{document.title=old}},[country])
  const spanish = country === 'Spain'
  const showElBierzo=(!country||country==='Spain')&&(countryFilter==='all'||countryFilter==='Spain')
  const candidateCount=new Set([...infrastructureCandidates.map(c=>c.id),...atlasCandidateRegistry.map(c=>c.id)]).size
  useAtlasMetadata({name:country?`${country} Atlas Research`:'Europe',country:country??'Europe',description:country?`Project Atlas research candidates in ${country}, assessed through evidence-led infrastructure and demand gates.`:'Project Atlas maps European AI infrastructure research candidates across power, fibre, land, permitting and validated demand.',route:country?`/infrastructure/${country.toLowerCase()}`:'/infrastructure/europe'})
  return <div><section className="bg-zinc-950 text-white"><div className="max-w-6xl mx-auto px-6 py-24 md:py-32"><p className="eyebrow text-zinc-500">{spanish ? 'Atlas España · ubicaciones en estudio' : 'Atlas Europe · Research programme'}</p><h1 className="max-w-4xl text-4xl font-semibold tracking-tight md:text-6xl">{spanish ? 'Computación avanzada donde la energía y el territorio encajan.' : 'Mapping Europe’s next AI infrastructure opportunities'}</h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-zinc-400">{spanish ? 'Atlas estudia ubicaciones con legado industrial, red eléctrica, conectividad y capacidad de ejecución. Ninguna avanza sin comprobar potencia, suelo, permisos y demanda real.' : 'Albedo Industries is researching candidate locations across Europe using a common evidence framework covering power, connectivity, land, permitting, climate, construction and verified demand. A candidate advances only when objective development gates are passed.'}</p><div className="mt-8 flex flex-wrap gap-3"><Link to={{hash:'#candidates'}} className="rounded-lg bg-white px-5 py-3 text-sm font-medium text-zinc-950">{spanish ? 'Ver ubicaciones' : 'Explore candidates'}</Link><Link to="/compute-infrastructure#capacity-interest" className="rounded-lg border border-zinc-700 px-5 py-3 text-sm font-medium">{registrationEnabled?(spanish?'Registrar necesidad de capacidad':'Register Europe-wide demand'):(spanish?'Registro de capacidad próximamente':'Capacity registration opening soon')}</Link><Link to="/infrastructure/funding" className="rounded-lg border border-zinc-700 px-5 py-3 text-sm font-medium">{spanish ? 'Transparencia financiera' : 'Funding transparency'}</Link></div></div></section>
  <section aria-label="Programme status" className="border-b border-zinc-200 bg-zinc-50"><dl className="max-w-6xl mx-auto grid grid-cols-2 gap-px bg-zinc-200 px-6 py-px md:grid-cols-5"><Status label={spanish ? 'Ubicaciones' : 'Candidate records'} value={String(candidateCount)}/><Status label={spanish ? 'Países' : 'Countries'} value={String(countries.length)}/><Status label={spanish ? 'Fase actual' : 'Current research'} value={spanish ? 'Gates mixtos' : 'Mixed gates · outcomes retained'}/><Status label={spanish ? 'Última revisión' : 'Latest update'} value="2026-08-12"/><Status label={spanish ? 'Demanda' : 'Demand validation'} value={registrationEnabled ? (spanish ? 'Registro abierto' : 'Registration open') : (spanish ? 'Próximamente' : 'Opening soon')}/></dl></section>
  <section className="border-b border-zinc-200"><div className="max-w-6xl mx-auto px-6 py-20"><div className="relative h-72 overflow-hidden rounded-xl border border-zinc-800 bg-zinc-950"><div aria-hidden className="absolute inset-0 opacity-20" style={{backgroundImage:'linear-gradient(#71717a 1px,transparent 1px),linear-gradient(90deg,#71717a 1px,transparent 1px)',backgroundSize:'36px 36px'}}/>{atlasCandidateRegistry.filter(x=>x.id==='EU-ES-04').map(c=><Link aria-label="Open El Bierzo research" title="El Bierzo research geography" key={c.id} to={c.route} className="absolute flex size-11 items-center justify-center" style={{left:'18%',top:'61%'}}><span aria-hidden="true" className="size-3 rounded-full bg-sky-300 ring-4 ring-sky-300/20" /></Link>)}{infrastructureCandidates.map((c,i)=><Link aria-label={`Open ${c.name} research`} title={c.name} key={c.id} to={c.route} className="absolute flex size-11 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full focus-visible:bg-white/10" style={{left:`${12+((c.coordinates.longitude+10)/32)*76}%`,top:`${75-((c.coordinates.latitude-37)/29)*60 + (i%2)}%`}}><span aria-hidden="true" className="size-3 rounded-full bg-amber-300 ring-4 ring-amber-300/20" /></Link>)}<p className="absolute bottom-5 left-5 text-xs text-zinc-400">{spanish ? 'Contexto territorial esquemático · los marcadores no son parcelas' : 'Schematic regional context · markers are not parcels'}</p></div></div></section>
  <section id="candidates"><div className="max-w-6xl mx-auto px-6 py-20 md:py-28">{atlasCandidateRegistry.filter(x=>x.id==='EU-ES-04'&&showElBierzo).map(x=><article key={x.id} className="mb-10 rounded-2xl border border-amber-300 bg-amber-50 p-6 md:p-8"><p className="text-xs font-bold tracking-widest">{x.id} · {x.country} · {x.gate}</p><h2 className="mt-3 text-3xl font-semibold">{x.name}</h2><p className="mt-3 text-sm font-semibold">{x.recommendation} · {x.researchStatus}</p><p className="mt-4 text-zinc-700"><strong>{spanish?'Oportunidad principal':'Primary opportunity'}:</strong> {x.summary}</p><p className="mt-2 text-zinc-700"><strong>{spanish?'Bloqueo principal':'Primary blocker'}:</strong> {x.primaryBlocker}</p><Link className="mt-6 inline-flex rounded-full bg-zinc-950 px-5 py-3 text-sm font-semibold text-white" to={x.route}>{spanish?'Abrir investigación':'Open research'}</Link></article>)}<div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">{spanish ? 'Ubicaciones en fase inicial' : 'Eleven transparent hypotheses'}</p><h2 className="section-title mb-0">{spanish ? 'Mapa Atlas en España' : 'European research candidates'}</h2></div><p className="max-w-md text-sm text-zinc-500">{spanish ? 'Los filtros ordenan el trabajo pendiente; no son una recomendación de inversión ni selección de emplazamiento.' : 'No candidate is ranked by quality. Filters organize evidence; they do not recommend a location.'}</p></div><nav aria-label="Country research pages" className="mt-8 flex flex-wrap gap-2">{countries.map(name=><Link key={name} to={`/infrastructure/${countrySlugs[name]}`} className="rounded-full border border-zinc-300 px-3 py-1.5 text-xs hover:border-zinc-500">{name}</Link>)}</nav>
  <div className="my-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Filter label={spanish ? 'País' : 'Country'} value={countryFilter} set={setCountryFilter} options={countries}/><Filter label={spanish ? 'Fase actual' : 'Current gate'} value="All gates" set={()=>{}} options={[]} disabled/><Filter label={spanish ? 'Tipo' : 'Classification'} value={classification} set={setClassification} options={['research_candidate','control_candidate']}/><Filter label={spanish ? 'Potencia' : 'Power evidence'} value={power} set={setPower} options={['evidence_required','hypothesis','verified']}/><Filter label={spanish ? 'Fibra' : 'Fibre evidence'} value={fiber} set={setFiber} options={['evidence_required','hypothesis','verified']}/><Filter label={spanish ? 'Demanda' : 'Demand status'} value={demand} set={setDemand} options={['registration_open','not_started']}/><Filter label={spanish ? 'Actualización' : 'Last updated'} value={updated} set={setUpdated} options={['recent']}/><Filter label={spanish ? 'Orden' : 'Sort'} value={sort} set={setSort} options={['updated','coverage','country','gate']} noAll/></div>
  <p className="mb-5 text-sm text-zinc-500" role="status">{spanish ? `Mostrando ${results.length+(showElBierzo?1:0)} de ${candidateCount} ubicaciones` : `Showing ${results.length+(showElBierzo?1:0)} of ${candidateCount} candidates`}</p><div className="grid gap-5 lg:grid-cols-2">{results.map(c=><article key={c.id} className="group overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><div className="relative min-h-48 bg-zinc-950 p-6 text-white md:p-8"><div aria-hidden className="absolute inset-0 opacity-25" style={{backgroundImage:'radial-gradient(circle at 20% 20%,#fbbf24 0 2px,transparent 3px),linear-gradient(135deg,rgba(251,191,36,.25),transparent 45%)',backgroundSize:'28px 28px,100% 100%'}}/><div className="relative"><div className="flex flex-wrap items-center justify-between gap-3"><span className="rounded-full border border-white/15 bg-white/10 px-3 py-1 text-xs">{c.id} · {c.region}</span><span className="rounded-full bg-amber-300 px-3 py-1 text-xs font-semibold text-zinc-950">{atlasCandidateRegistryByRoute.get(c.route)?.recommendation??c.visual.metric}</span></div><p className="mt-8 text-xs uppercase tracking-[.2em] text-amber-200">{c.country}</p><h3 className="mt-2 text-3xl font-semibold tracking-tight">{c.visual.localName}</h3><p className="mt-4 max-w-xl text-sm leading-relaxed text-zinc-300">{c.visual.localPitch}</p><div className="mt-5 flex flex-wrap gap-2">{c.visual.tags.map(tag=><span key={tag} className="rounded-full border border-white/10 bg-white/10 px-2.5 py-1 text-xs text-zinc-200">{tag}</span>)}</div></div></div><div className="p-6 md:p-8"><dl className="grid gap-3 sm:grid-cols-2"><VisualStat label={spanish ? 'Interés' : 'Opportunity'} value={c.visual.localOpportunity}/><VisualStat label={spanish ? 'Punto crítico' : 'Blocker'} value={c.visual.localBlocker}/><VisualStat label="Gate" value={c.currentGate}/><VisualStat label={spanish ? 'Investigación' : 'Research state'} value={c.publicStatus}/></dl><div className="mt-6"><ResearchIndicators candidate={c} compact/></div><div className="mt-7 flex flex-wrap items-center justify-between gap-4 border-t border-zinc-100 pt-5"><time className="text-xs text-zinc-400" dateTime={c.lastUpdated}>{spanish ? 'Revisión' : 'Updated'} {c.lastUpdated}</time><div className="flex flex-wrap justify-end gap-3"><Link className="rounded-lg bg-zinc-950 px-4 py-2 text-sm font-medium text-white" to={c.route}>{spanish ? 'Ver ficha' : 'Open summary'}</Link><Link className="rounded-lg border border-zinc-300 px-4 py-2 text-sm font-medium" to={`${c.route}/funding`}>{spanish ? 'Financiación' : 'Funding'}</Link></div></div></div></article>)}</div></div></section></div>
}
function VisualStat({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-zinc-200 bg-zinc-50 p-4"><dt className="text-xs uppercase tracking-wide text-zinc-400">{label}</dt><dd className="mt-2 text-sm font-semibold capitalize text-zinc-900">{value}</dd></div>}

function Filter({label,value,set,options,disabled=false,noAll=false}:{label:string;value:string;set:(value:string)=>void;options:string[];disabled?:boolean;noAll?:boolean}){return <label className="text-xs font-medium text-zinc-500">{label}<select disabled={disabled} value={value} onChange={e=>set(e.target.value)} className="mt-2 w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 disabled:bg-zinc-100">{!noAll&&<option value="all">All</option>}{options.map(x=><option value={x} key={x}>{x.replaceAll('_',' ')}</option>)}</select></label>}

function Status({label,value}:{label:string;value:string}){return <div className="bg-zinc-50 px-4 py-5"><dt className="text-xs text-zinc-400">{label}</dt><dd className="mt-2 text-sm font-semibold">{value}</dd></div>}
