import { Link } from 'react-router-dom'
import { useAtlasMetadata } from '../hooks/useAtlasMetadata'

const contact=(intent:string)=>`mailto:alex@albedo-industries.com?subject=${encodeURIComponent(`Project Atlas — ${intent}`)}&body=${encodeURIComponent('Hello Atlas,\n\nOrganization:\nRole / requirements / opportunity:\nRelevant market or project:\nPreferred next step:\n')}`
const privateOverview=`mailto:alex@albedo-industries.com?subject=${encodeURIComponent('Project Atlas — private investor overview')}&body=${encodeURIComponent('Hello Atlas,\n\nOrganization:\nName and role:\nInvestment focus:\nMarkets or opportunities of interest:\nPreferred next step:\n\nI would like to request the private Project Atlas overview.')}`
export default function InfrastructureFunding(){useAtlasMetadata({name:'Investment & Partnerships',country:'International',title:'Project Atlas — Investment & Partnerships | ALBEDO Industries',description:'Engage Project Atlas on development capital, capacity requirements and infrastructure partnerships for selected AI infrastructure opportunities.',route:'/atlas/partners'});return <div>
<section className="bg-zinc-950 text-white"><div className="mx-auto max-w-6xl px-6 py-20 md:py-28"><Link to="/atlas" className="inline-flex min-h-11 items-center text-sm text-zinc-400">← Project Atlas</Link><p className="mt-8 eyebrow text-amber-200">CAPITAL · OPERATORS · INFRASTRUCTURE</p><h1 className="max-w-5xl text-4xl font-semibold tracking-tight md:text-6xl">Advance selected opportunities with evidence, requirements and aligned capital.</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-zinc-300">Atlas is engaging selected capital, operator and infrastructure partners to validate and advance evidence-backed AI infrastructure opportunities. No investment offer is open through this website.</p></div></section>
<Section eyebrow="Choose the relevant pathway" title="Focused conversations for each partner role"><div className="grid gap-5 md:grid-cols-3"><article className="flex flex-col rounded-2xl border border-zinc-300 p-6 shadow-sm"><h3 className="text-xl font-semibold">Capital Partners</h3><p className="mt-3 flex-1 text-zinc-600">Advance selected opportunities through grid studies and applications, site control, diligence, engineering, permitting, legal structuring and commercial validation.</p><a href={privateOverview} className="mt-6 inline-flex min-h-11 items-center font-semibold underline decoration-amber-400 underline-offset-4">Request the private Atlas overview →</a><a href={contact('capital partnership')} className="inline-flex min-h-11 items-center text-sm text-zinc-600 underline underline-offset-4">Discuss a capital partnership</a></article>{[['Operators & Capacity Partners','Share deployment requirements covering power, scale, phasing, resilience, network, cooling, geography and delivery timing.','capacity requirements'],['Site & Infrastructure Partners','Bring a credible land, power, utility, fibre, industrial-park or institutional pathway for structured Atlas screening.','site or infrastructure opportunity']].map(x=><article className="flex flex-col rounded-2xl border border-zinc-200 p-6" key={x[0]}><h3 className="text-xl font-semibold">{x[0]}</h3><p className="mt-3 flex-1 text-zinc-600">{x[1]}</p><a href={contact(x[2])} className="mt-6 inline-flex min-h-11 items-center font-semibold underline decoration-amber-400 underline-offset-4">Discuss {x[2]} →</a></article>)}</div></Section>
<Section eyebrow="How capital follows evidence" title="Three phases, each earned"><ol className="grid gap-4 md:grid-cols-3">{['Research and validation','Site control and preliminary development','Project financing and delivery'].map((x,i)=><li className="rounded-2xl bg-zinc-950 p-6 text-white" key={x}><span className="text-xs text-amber-200">0{i+1}</span><h3 className="mt-4 text-xl font-semibold">{x}</h3></li>)}</ol><p className="mt-6 text-zinc-600">Each phase proceeds only when the evidence and counterparties justify it. Later development and delivery are not guaranteed.</p></Section>
<Section eyebrow="Current position" title="Published research; no public offer"><ul className="grid gap-3 md:grid-cols-2">{['Atlas has published candidate research.','Institutional and market outreach is active.','No public investment offer is open.','Expressions of interest are non-binding.','Project-specific structures would be defined before accepting capital.'].map(x=><li className="rounded-xl border border-zinc-200 p-4" key={x}>✓ {x}</li>)}</ul></Section>
<section className="bg-zinc-950 text-white"><div className="mx-auto max-w-6xl px-6 py-20"><h2 className="text-3xl font-semibold">Discuss investment, development or operating requirements.</h2><p className="mt-4 text-sm text-zinc-400">This website does not offer securities or accept investor funds.</p><a href={contact('partnership conversation')} className="mt-7 inline-flex min-h-12 items-center rounded-full bg-white px-6 text-sm font-semibold text-zinc-950">Start a confidential conversation</a></div></section></div>}
function Section({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <section className="border-t border-zinc-200"><div className="mx-auto max-w-6xl px-6 py-20 md:py-28"><p className="eyebrow">{eyebrow}</p><h2 className="section-title">{title}</h2>{children}</div></section>}
