import { Link, useLocation } from 'react-router-dom'
import HeroVideo from '../components/HeroVideo'
import { atlasPipeline } from '../data/atlasPipeline'
import { useAtlasMetadata } from '../hooks/useAtlasMetadata'

const partner='mailto:alex@albedo-industries.com?subject=Project%20Atlas%20%E2%80%94%20investment%20or%20co-development'
const stages=['ORIGINATE','VALIDATE','STRUCTURE','DEVELOP','CAPITAL / DEMAND']

export default function InfrastructureEurope({country}:{country?:string}){
 const pathname=useLocation().pathname
 useAtlasMetadata({name:country?`${country} Atlas Research`:'Project Atlas',country:country??'International',title:country?undefined:'Project Atlas — Data Center Development & Infrastructure Origination',description:'Project Atlas advances selected data-center opportunities through power, land, development evidence and aligned capital.',route:country?`/infrastructure/${country.toLowerCase()}`:'/atlas'})
 const opportunities=atlasPipeline.filter(x=>(!country||x.market===country)&&(x.publication.visibility==='featured'||x.publication.visibility==='public'))
 return <article>
  <section className={`hero-video-section relative isolate flex overflow-hidden bg-[radial-gradient(circle_at_70%_30%,#3f3f46_0%,#18181b_45%,#09090b_80%)] text-white ${pathname==='/atlas'?'min-h-[92svh]':'min-h-[70svh]'}`}><HeroVideo src="/media/ALBEDO - INDUSTRIES/weryai_5bb6aefbba19268f1e7c90c34015e82f.mp4" className="object-[58%_50%] md:object-center"/><div className="absolute inset-0 bg-gradient-to-r from-black/90 via-black/68 to-black/35"/><div className="relative mx-auto flex w-full max-w-6xl flex-col justify-center px-5 py-24 sm:px-6"><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-200">Project Atlas · Data-center development</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold leading-[.98] tracking-[-.04em] md:text-7xl">From infrastructure opportunity to investable data-center project.</h1><p className="mt-7 max-w-2xl text-lg text-zinc-200">Atlas validates power, land and delivery pathways, then aligns the capital and demand needed to advance selected projects.</p><div className="mt-8 flex flex-wrap gap-2 text-[.68rem] font-bold uppercase tracking-[.14em]"><span className="bg-white px-3 py-2 text-zinc-950">10–25 MW typical initial phase</span><span className="border border-zinc-500 px-3 py-2">International</span><span className="border border-zinc-500 px-3 py-2">Early-stage development</span></div><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#opportunities" className="inline-flex min-h-12 items-center justify-center bg-white px-6 text-sm font-semibold text-zinc-950">Current opportunities</a><Link to="/atlas/partners" className="inline-flex min-h-12 items-center justify-center border border-amber-300 px-6 text-sm font-semibold text-amber-100">Investment / co-development</Link></div></div></section>

  <Section id="opportunities" eyebrow="02 · Current opportunities" title="A defined next gate, not a vanity pipeline." intro="Public opportunities show only what is supported and what must happen next."><div className="divide-y divide-zinc-300 border-y border-zinc-300">{opportunities.map(x=><article className="grid gap-6 py-8 lg:grid-cols-[1fr_2fr_auto] lg:items-start" key={x.id}><div><p className="text-xs font-bold uppercase tracking-[.14em] text-zinc-500">{x.market} · {x.evidence}</p><h3 className="mt-2 text-3xl font-semibold">{x.name}</h3></div><div className="grid gap-5 sm:grid-cols-3"><Fact label="Scale" value={x.scale}/><Fact label="Stage" value={x.stage}/><Fact label="Next gate" value={x.nextMilestone}/></div><Link to={x.researchRoute??'/atlas/research'} className="inline-flex min-h-11 items-center font-semibold underline decoration-amber-400 underline-offset-4">View opportunity →</Link></article>)}</div></Section>

  <Section id="model" dark eyebrow="03 · Development model" title="Move uncertainty toward a decision."><ol className="mt-4 grid gap-3 md:grid-cols-5">{stages.map((x,i)=><li className="flex min-h-32 flex-col justify-between border-t border-zinc-700 py-5" key={x}><span className="text-xs text-amber-300">0{i+1}</span><strong className="text-sm tracking-[.12em]">{x}</strong></li>)}</ol><Link to="/atlas/partners" className="mt-7 inline-flex min-h-11 items-center text-sm font-semibold underline decoration-amber-300 underline-offset-4">See full development process →</Link></Section>

  <Section id="capital" eyebrow="04 · Investment / co-development" title="Capital tied to a defined development gate."><div className="grid gap-8 md:grid-cols-3"><Path title="Development capital">Fund evidence, rights and project formation.</Path><Path title="Co-development">Share work, risk and project economics.</Path><Path title="Principal developer / investor">Advance a suitable project following diligence.</Path></div><Link to="/atlas/partners" className="mt-9 inline-flex min-h-12 items-center bg-zinc-950 px-6 text-sm font-semibold text-white">Investment & co-development</Link></Section>

  <Section id="evidence" dark eyebrow="05 · Evidence + research" title="Evidence before claims." intro="Power, land and control are labelled by what is actually supported."><div className="flex flex-col gap-3 sm:flex-row"><Link to="/atlas/research" className="inline-flex min-h-12 items-center justify-center bg-white px-6 text-sm font-semibold text-zinc-950">Review Atlas evidence standard</Link><Link to="/atlas/research" className="inline-flex min-h-12 items-center justify-center border border-zinc-600 px-6 text-sm font-semibold">Explore research</Link></div></Section>

  <section className="bg-amber-300"><div className="mx-auto flex max-w-6xl flex-col gap-8 px-5 py-20 sm:px-6 md:flex-row md:items-center md:justify-between"><h2 className="max-w-3xl text-4xl font-semibold tracking-tight md:text-6xl">Advance the next credible project.</h2><a href={partner} className="inline-flex min-h-12 shrink-0 items-center justify-center bg-zinc-950 px-6 text-sm font-semibold text-white">Discuss an opportunity</a></div></section>
 </article>
}
function Section({id,eyebrow,title,intro,children,dark=false}:{id:string;eyebrow:string;title:string;intro?:string;children:React.ReactNode;dark?:boolean}){return <section id={id} className={`border-b ${dark?'border-zinc-800 bg-zinc-950 text-white':'border-zinc-300 bg-white'}`}><div className="mx-auto max-w-6xl px-5 py-20 sm:px-6 md:py-28"><p className={`text-xs font-bold uppercase tracking-[.18em] ${dark?'text-amber-200':'text-zinc-500'}`}>{eyebrow}</p><h2 className="mt-4 max-w-4xl text-4xl font-semibold tracking-tight md:text-6xl">{title}</h2>{intro&&<p className={`mt-6 max-w-2xl text-lg ${dark?'text-zinc-400':'text-zinc-600'}`}>{intro}</p>}<div className="mt-10">{children}</div></div></section>}
function Fact({label,value}:{label:string;value:string}){return <div><p className="text-[.65rem] font-bold uppercase tracking-[.14em] text-zinc-500">{label}</p><p className="mt-2 text-sm leading-relaxed">{value}</p></div>}
function Path({title,children}:{title:string;children:React.ReactNode}){return <article className="border-t-2 border-zinc-950 pt-5"><h3 className="text-sm font-bold uppercase tracking-[.14em]">{title}</h3><p className="mt-3 text-zinc-600">{children}</p></article>}
