import { Link } from 'react-router-dom'
const discuss='mailto:alex@albedo-industries.com?subject=Albedo%20Orbital%20research%20and%20partnership'
export default function Orbital(){return <article className="bg-zinc-950 text-white">
 <header className="relative overflow-hidden border-b border-zinc-800"><div className="absolute left-[65%] top-1/2 h-[42rem] w-[42rem] -translate-y-1/2 rounded-full border border-zinc-700"/><div className="absolute left-[65%] top-1/2 h-[20rem] w-[60rem] -translate-x-1/2 -translate-y-1/2 rotate-[-12deg] rounded-[50%] border border-zinc-700"/><div className="relative mx-auto flex min-h-[88svh] max-w-6xl flex-col justify-center px-5 py-24 sm:px-6"><span className="w-fit bg-white px-3 py-2 text-[.68rem] font-bold uppercase tracking-[.15em] text-zinc-950">Research / pre-development</span><h1 className="mt-7 max-w-5xl text-6xl font-semibold leading-[.94] tracking-[-.045em] md:text-8xl">Compute beyond Earth.</h1><p className="mt-7 max-w-2xl text-lg text-zinc-300">Albedo Orbital researches autonomous compute infrastructure beyond conventional terrestrial-grid constraints. Progress depends on measured engineering evidence.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/orbital/research" className="inline-flex min-h-12 items-center justify-center bg-white px-6 text-sm font-semibold text-zinc-950">Explore the research</Link><a href={discuss} className="inline-flex min-h-12 items-center justify-center border border-zinc-600 px-6 text-sm font-semibold">Discuss Orbital</a></div></div></header>
 <Section eyebrow="02 · Earth vs orbit" title="The bottleneck does not disappear. It moves."><div className="grid items-center gap-8 md:grid-cols-[1fr_auto_1fr]"><Constraint title="Earth" items={['GRID','LAND','COOLING','TIME-TO-POWER']}/><span className="text-5xl text-amber-300 max-md:rotate-90">→</span><Constraint title="Orbit" items={['MASS','THERMAL','POWER','COMMUNICATIONS','AUTONOMY']}/></div></Section>
 <Section eyebrow="03 · What must become true" title="Six coupled constraints."><div className="flex flex-wrap gap-x-8 gap-y-5 text-2xl font-semibold md:text-4xl">{['POWER','THERMAL','LAUNCH','COMPUTE','NETWORK','AUTONOMY'].map(x=><span key={x}>{x}</span>)}</div><Link to="/orbital/research" className="mt-10 inline-flex min-h-12 items-center bg-white px-6 text-sm font-semibold text-zinc-950">Research the bottlenecks</Link></Section>
 <Section eyebrow="04 · Experiment 01" title="Autonomous compute node."><article className="max-w-4xl border border-zinc-700 p-7 md:p-10"><span className="text-xs font-bold uppercase tracking-[.14em] text-amber-200">Experiment design</span><p className="mt-5 text-xl leading-relaxed text-zinc-300">Testing whether useful compute can continue with minimal human intervention under constrained and changing conditions.</p><Link to="/orbital/experiment-01" className="mt-7 inline-flex min-h-12 items-center border border-white px-6 text-sm font-semibold">Review Experiment 01</Link></article></Section>
 <section id="partners" className="bg-[#deddd2] text-zinc-950"><div className="mx-auto flex max-w-6xl flex-col gap-8 px-5 py-20 sm:px-6 md:flex-row md:items-center md:justify-between"><h2 className="max-w-3xl text-4xl font-semibold tracking-tight md:text-6xl">Help test what becomes possible.</h2><a href={discuss} className="inline-flex min-h-12 shrink-0 items-center justify-center bg-zinc-950 px-6 text-sm font-semibold text-white">Discuss research or partnership</a></div></section>
 </article>}
function Section({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <section className="border-b border-zinc-800"><div className="mx-auto max-w-6xl px-5 py-20 sm:px-6 md:py-28"><p className="text-xs font-bold uppercase tracking-[.18em] text-zinc-500">{eyebrow}</p><h2 className="mt-4 max-w-4xl text-4xl font-semibold tracking-tight md:text-6xl">{title}</h2><div className="mt-12">{children}</div></div></section>}
function Constraint({title,items}:{title:string;items:string[]}){return <article><h3 className="text-5xl font-semibold text-amber-200">{title}</h3><div className="mt-7 space-y-3 text-xl text-zinc-300">{items.map(x=><p key={x}>{x}</p>)}</div></article>}
