import { Link } from 'react-router-dom'
import { orbitalResearch, orbitalSources, type OrbitalEvidence } from '../data/orbitalResearch'
import { computeLoadsKw, launchMassesTonnes, launchPricesUsdKg, powerScenario, radiatorAreaM2, radiatorTemperaturesK } from '../data/orbitalModel'

const contact='mailto:alex@albedo-industries.com?subject=Albedo%20Orbital%20technical%20research'
const scorecard=[
  ['Power','Open research question','Array technologies exist; no ALBEDO architecture selected.','Continuous delivered MW-scale power system.','Delivered W/m² and W/kg','Orbit-specific generation, storage and distribution model'],
  ['Thermal','Engineering gap','Radiative heat rejection is first-order modelled.','Integrated MW-scale compute thermal system.','Radiator m²/kW and kg/kW','Close heat transport, view factors, structures and redundancy'],
  ['Compute','System-integration gap','Spaceflight compute exists as a category; no source is published here yet.','Data-center-class workload economics in orbit.','Useful workload/W and /kg','Comparable workload benchmark and lifecycle definition'],
  ['Radiation','Engineering gap','Mitigation approaches require source review.','Economical commercial-accelerator survival.','Dose, error rate, capacity overhead','Select orbit and test hardware/mitigation stack'],
  ['Launch','Economic gap','Scenario arithmetic only.','Delivered system cost including integration and replacement.','Delivered $/kg and cadence','Source current services; define destination and packaging'],
  ['Network','Open research question','Optical and RF evidence requires source review.','Commercial service availability for intended workloads.','Delivered Gbit/s, availability, $/bit','Model weather, stations, pointing, latency and locality'],
  ['Autonomy','System-integration gap','Autonomy is a research domain, not an ALBEDO deployment.','Compute-facility recovery with low intervention.','MTBF, MTTR, intervention rate','Define failure model and terrestrial test'],
  ['Servicing','Engineering gap','No ALBEDO servicing architecture exists.','Repeatable upgrade, repair and disposal system.','Replacement time and cost','Resolve modularity against accelerator obsolescence'],
  ['Regulation','Regulatory gap','A research map exists; no legal conclusion.','Jurisdiction-specific compliant architecture.','Licences and lifecycle obligations','Review launch, spectrum, debris, re-entry and data rules'],
  ['Economics','Open research question','Cost-stack and sensitivity variables are defined.','Comparable lifecycle cost for one workload.','$/useful workload over life','Source subsystem costs and define utilization'],
] as const
const workloads=[
  ['Space-native image processing','Orbit','Reduced products','Variable','High','Plausible; demand not validated'],
  ['Satellite data reduction','Orbit','Reduced products','Variable','Medium','Plausible; demand not validated'],
  ['Space-station compute','Orbit / local','Local + selective','Operational','Medium','Requires customer and platform evidence'],
  ['In-space inference','Orbit','Results / actions','Operational','Medium','Research candidate'],
  ['Scientific batch compute','Mixed','Inputs and results','Low','High','Depends on data origin'],
  ['Distributed inference','Earth','Inputs + outputs','Medium','High','Link economics may dominate'],
  ['Model training','Earth','Very large datasets','Low','Very high','No orbital advantage established'],
  ['Real-time Earth services','Earth','Bidirectional','High','Variable','Latency and availability sensitive'],
] as const
const gates=[['0','Thesis','Identify a workload with a structural orbital advantage.'],['1','First-order physics','Close mass, power, thermal and communications arithmetic.'],['2','Subsystem economics','Reach plausible subsystem mass and cost thresholds.'],['3','Terrestrial precursor','Validate autonomy and remote operation on Earth.'],['4','Orbital compute demonstrator','Operate a small payload—not a data center.'],['5','Serviceable multi-node system','Demonstrate modular orchestration and replacement.'],['6','Commercial orbital compute','Proceed only for justified workload economics.'],['7','Large-scale orbital data center','Long-term gate, not a current program.']] as const

export default function OrbitalResearch(){return <article className="bg-[#f3f2ec] text-zinc-950">
  <header className="border-b border-zinc-700 bg-zinc-950 text-white"><div className="mx-auto max-w-6xl px-5 py-24 sm:px-6 md:py-32"><p className="text-xs font-bold uppercase tracking-[.2em] text-zinc-400">Albedo research note · ORB-R01 · v0.1</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold leading-[.96] tracking-[-.04em] sm:text-6xl md:text-7xl">What must become true?</h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-zinc-300">Large-scale orbital compute becomes credible only if several coupled technical and economic thresholds improve enough simultaneously. This note maps those thresholds; it does not assume a positive conclusion.</p><div className="mt-8 flex flex-wrap gap-2 text-[.65rem] font-bold uppercase tracking-[.13em]"><span className="bg-white px-3 py-2 text-zinc-950">Gate 0 / early Gate 1</span><span className="border border-zinc-600 px-3 py-2">Reviewed 13 September 2026</span><span className="border border-amber-300 px-3 py-2 text-amber-200">External source verification pending</span></div></div></header>
  <RSection n="01" eyebrow="Current conclusion" title="The system case is not closed."><div className="grid gap-8 lg:grid-cols-[1fr_.75fr]"><div className="space-y-4 text-lg leading-relaxed text-zinc-700"><p>The current ALBEDO model supports only a narrower conclusion: power generation and thermal rejection both scale with area and mass, while launch, radiation, communications, autonomy, servicing and end-of-life add coupled penalties.</p><p>No sourced evidence in this repository yet establishes hyperscale orbital economics, an appropriate orbit, a qualified compute stack, or a first commercial workload. The immediate work is source verification and first-order system closure—not spacecraft construction.</p></div><Note evidence="OPEN QUESTION">A technically possible subsystem is not evidence of an investable integrated system.</Note></div></RSection>
  <RSection n="02" eyebrow="Bottleneck scorecard" title="Ten constraints, no readiness theatre." intro="Qualitative labels describe the research gap. They are not technology-readiness levels."><div className="divide-y divide-zinc-300 border-y border-zinc-300">{scorecard.map(([area,state,demonstrated,missing,metric,improve])=><details className="group py-5" key={area}><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-4"><span className="font-semibold">{area}</span><span className="text-right text-xs font-bold uppercase tracking-[.12em] text-zinc-500">{state} · +</span></summary><dl className="mt-5 grid gap-5 text-sm sm:grid-cols-2 lg:grid-cols-4"><Fact label="Current evidence">{demonstrated}</Fact><Fact label="Not demonstrated">{missing}</Fact><Fact label="Key metric">{metric}</Fact><Fact label="What must improve">{improve}</Fact></dl></details>)}</div></RSection>
  <RSection n="03" eyebrow="First-order system model" title="Power area and thermal area grow with load." intro="All values below are scenario assumptions or derived estimates—not designs, forecasts or feasibility claims."><div className="grid gap-px bg-zinc-300 md:grid-cols-2"><div className="bg-white p-6"><p className="text-xs font-bold uppercase tracking-[.14em]">Illustrative power scenario</p><p className="mt-3 text-sm text-zinc-600">250 W/m² delivered array density, 100 W/kg array specific power and 1.5× nameplate overhead. Storage, structure, pointing, wiring and distribution are excluded.</p></div><div className="bg-zinc-950 p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.14em] text-zinc-400">First-order thermal physics</p><p className="mt-3 font-mono text-sm">Q = ε σ A (T<sub>rad</sub>⁴ − T<sub>sink</sub>⁴)</p><p className="mt-3 text-sm text-zinc-400">ε=0.9 and a 3 K idealized sink. Solar/Earth view, transport, structures, redundancy and degradation are excluded.</p></div></div><ScenarioTable/></RSection>
  <RSection n="04" eyebrow="Power" title="Nameplate generation is not delivered compute power." intro="Orbit selection determines eclipse, pointing and storage requirements. No continuous-sun architecture or battery-free claim is made."><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{computeLoadsKw.map(load=>{const x=powerScenario(load);return <FactBox key={load} title={formatPower(load)} status="SCENARIO ASSUMPTION"><strong>{formatArea(x.arrayAreaM2)}</strong> array area<br/><strong>{formatMass(x.arrayMassKg)}</strong> array-only mass<br/><span>at {formatPower(x.nameplateKw)} nameplate</span></FactBox>})}</div><p className="mt-6 text-sm text-zinc-600">The 100 MW row is arithmetic scale illustration only. It is not represented as technically feasible.</p></RSection>
  <RSection n="05" eyebrow="Thermal rejection" title="Higher compute density does not make heat disappear." intro="Nearly all electrical input ultimately becomes heat that must leave the system. The table is idealized one-sided emitting area; a spacecraft design would require non-ideal allowances."><ThermalTable/><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{['Solar and Earth view factors','Heat transport and pumping','Structure, deployment and shadowing','Redundancy, degradation and debris protection'].map(x=><div className="border-l-2 border-zinc-400 pl-4 text-sm text-zinc-600" key={x}>{x}</div>)}</div></RSection>
  <RSection n="06" eyebrow="Compute and radiation" title="Spaceflight compute is not data-center-class AI compute." intro="Radiation-tolerant processors can establish relevant reliability approaches; they do not establish accelerator throughput, mass or economics. Commercial accelerators require orbit-specific evidence for dose, single-event effects, shielding, correction, redundancy and replacement."><div className="grid gap-px bg-zinc-300 md:grid-cols-2"><Note evidence="OPEN QUESTION">Comparable workload/W, workload/kg and useful-life evidence is required. FLOPS and TOPS from unlike architectures are not compared here.</Note><Note evidence="RESEARCH HYPOTHESIS">Accelerator obsolescence may be faster than spacecraft life, making modular replacement a central economic variable.</Note></div><Link to="/orbital/experiment-01" className="mt-7 inline-flex min-h-11 items-center font-semibold underline underline-offset-4">Experiment 01 · Compute resilience and recovery →</Link></RSection>
  <RSection n="07" eyebrow="Launch threshold scenarios" title="$/kg is an input, not the launch architecture." intro="These prices are sensitivity cases, not provider quotes or forecasts. Integration, destination, volume, deployment, cadence and replacement are excluded."><LaunchTable/></RSection>
  <RSection n="08" eyebrow="Communications and data locality" title="The first viable workload may begin in orbit."><div className="grid gap-px bg-zinc-300 md:grid-cols-2"><FactBox title="Orbit-native data" status="POTENTIAL STRUCTURAL FIT">Earth observation, satellite sensing, space science and future in-space systems may process data near its source and transmit reduced products.</FactBox><FactBox title="Earth-native workloads" status="UNPROVEN FIT">Training and serving terrestrial datasets may require substantial Earth-to-orbit and orbit-to-Earth movement, with availability, latency and cost penalties.</FactBox></div><p className="mt-7 text-sm text-zinc-600">Optical communications can only be described quantitatively after primary demonstration evidence is reviewed. A demonstration data rate would not equal guaranteed commercial service.</p></RSection>
  <RSection n="09" eyebrow="Autonomy, servicing and assembly" title="Remote infrastructure must fail predictably—and remain upgradeable."><div className="grid gap-5 md:grid-cols-2"><FactBox title="Autonomy research" status="SOURCE REQUIRED">Fault diagnosis, safe modes, workload rescheduling, secure updates, degraded operation and measured MTBF/MTTR need a terrestrial test plan.</FactBox><FactBox title="Serviceability research" status="SOURCE REQUIRED">Module isolation, spares, robotic replacement, assembly, disposal and accelerator upgrade cadence need one lifecycle architecture.</FactBox></div><Link to="/orbital/experiment-01" className="mt-7 inline-flex min-h-11 items-center font-semibold underline underline-offset-4">Experiment 01 · Autonomy and communications →</Link></RSection>
  <RSection n="10" eyebrow="Orbit and sustainability" title="No orbit recommendation yet." intro="LEO, SSO and higher orbits change eclipses, drag, radiation, debris exposure, latency, disposal and communications. Selection must follow evidence, not branding."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{['Launch licensing','Spectrum and optical links','Space-object registration','Collision avoidance','Debris mitigation','Re-entry and disposal','Jurisdiction','Data sovereignty','Export controls and cybersecurity'].map(x=><div className="border border-zinc-300 p-4 text-sm" key={x}>{x}</div>)}</div><p className="mt-5 text-xs text-zinc-500">Regulatory research map only; not legal advice.</p></RSection>
  <RSection n="11" eyebrow="Lifecycle economics" title="A crossover cannot be calculated honestly yet." intro="The comparison unit must follow a defined workload—not generic $/MW. Candidate units include cost per accelerator-year or cost per delivered workload over useful life."><div className="grid gap-8 lg:grid-cols-2"><FactBox title="Orbital cost stack" status="MODEL STRUCTURE">Compute · power · thermal · structure · communications · radiation/redundancy · launch · deployment · ground segment · operations · servicing · replacement · end of life</FactBox><FactBox title="Terrestrial comparison stack" status="COMPARISON REQUIRED">Hardware · land · grid connection · substation · power · cooling · building · network · permitting · operations · time-to-power</FactBox></div><div className="mt-8"><h3 className="text-sm font-bold uppercase tracking-[.14em]">Dominant sensitivity candidates</h3><div className="mt-4 flex flex-wrap gap-2">{['Delivered launch $/kg','Array W/kg','Radiator kg/kW','Useful compute/W','Hardware useful life','Link availability and cost','Servicing and utilization'].map(x=><span className="border border-zinc-400 px-3 py-2 text-sm" key={x}>{x}</span>)}</div></div></RSection>
  <RSection n="12" eyebrow="Workload priorities" title="Do not assume model training is first."><ResponsiveRows headers={['Workload','Data origin','Downlink','Latency','Compute','Current view']} rows={workloads}/></RSection>
  <RSection n="13" eyebrow="Development gates" title="Evidence before orbital scale." intro="ALBEDO is at Gate 0 / early Gate 1. These are decision gates, not dates."><ol className="grid gap-px bg-zinc-300 sm:grid-cols-2 lg:grid-cols-4">{gates.map(([n,title,copy])=><li className="bg-white p-5" key={n}><span className="text-xs text-zinc-400">GATE {n}</span><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-3 text-sm text-zinc-600">{copy}</p></li>)}</ol></RSection>
  <RSection n="14" eyebrow="Terrestrial precursor" title="What can ALBEDO test before orbit?" intro="Remote renewable generation, mines, islands, off-grid industrial sites, telecom infrastructure, harsh environments and temporary infrastructure could test autonomy, low-touch operation, fault recovery, modularity, variable power, thermal limits and constrained communications. This is a research bridge, not a new commercial project."><Link to="/atlas" className="inline-flex min-h-11 items-center font-semibold underline underline-offset-4">How this connects to Project Atlas →</Link></RSection>
  <RSection n="15" eyebrow="Industry signals" title="Demonstrated and announced are not interchangeable." intro="Candidate programs—including NASA computing and communications work, ASCEND, AWS/Axiom activities, Axiom programs and Starcloud claims—remain SOURCE REQUIRED in this note. No demonstration or roadmap is published as evidence until its primary source has been reviewed."><Note evidence="OPEN QUESTION">Industry activity may establish that a subsystem or payload was demonstrated. It cannot independently prove ALBEDO's architecture, scalability or economics.</Note></RSection>
  <RSection n="16" eyebrow="Source registry" title={orbitalSources.length ? 'Primary evidence reviewed.' : 'Primary-source verification remains open.'} intro="Rather than publish unverified report titles, links, dates or figures, v0.1 contains no external source record. Statements requiring external support remain explicitly open.">{orbitalSources.length?<ul>{orbitalSources.map(s=><li key={s.id}><a href={s.url}>{s.organisation} — {s.title}</a></li>)}</ul>:<p className="border-l-2 border-amber-500 pl-4 text-sm text-zinc-600">Priority review queue: NASA spaceflight computing, small-spacecraft power and thermal guidance, optical communications and autonomy; ESA debris guidance; current launch-provider pricing; and primary industry demonstration records.</p>}</RSection>
  <RSection n="17" eyebrow="Open questions" title="The next work is falsifiable."><div className="divide-y divide-zinc-300 border-y border-zinc-300">{orbitalResearch.map(item=><article className="grid gap-3 py-5 md:grid-cols-[6rem_12rem_1fr_10rem]" key={item.id}><span className="text-xs font-bold">{item.id}</span><h3 className="font-semibold">{item.topic}</h3><p className="text-sm text-zinc-600">{item.question}</p><div className="text-xs text-zinc-500"><Evidence value={item.evidence}/><p className="mt-2">{item.status}</p></div></article>)}</div></RSection>
  <section className="bg-zinc-950 text-white"><div className="mx-auto flex max-w-6xl flex-col gap-8 px-5 py-16 sm:px-6 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-zinc-500">Technical collaboration</p><h2 className="mt-3 text-3xl font-semibold md:text-5xl">Challenge the model.</h2></div><div className="flex flex-col gap-3 sm:flex-row"><a href={contact} className="inline-flex min-h-12 items-center justify-center bg-white px-6 text-sm font-semibold text-zinc-950">Discuss Albedo Orbital</a><Link to="/orbital" className="inline-flex min-h-12 items-center justify-center border border-zinc-600 px-6 text-sm font-semibold">Orbital overview</Link></div></div></section>
</article>}

function RSection({n,eyebrow,title,intro,children}:{n:string;eyebrow:string;title:string;intro?:string;children:React.ReactNode}){return <section className="border-b border-zinc-300"><div className="mx-auto max-w-6xl px-5 py-18 sm:px-6 md:py-24"><p className="text-xs font-bold uppercase tracking-[.16em] text-zinc-500">{n} · {eyebrow}</p><h2 className="mt-4 max-w-4xl text-3xl font-semibold tracking-tight sm:text-4xl md:text-5xl">{title}</h2>{intro&&<p className="mt-6 max-w-4xl text-lg leading-relaxed text-zinc-600">{intro}</p>}<div className="mt-10">{children}</div></div></section>}
function Evidence({value}:{value:OrbitalEvidence}){return <span className="inline-flex border border-zinc-400 px-2 py-1 text-[.6rem] font-bold uppercase tracking-[.1em]">{value}</span>}
function Note({evidence,children}:{evidence:OrbitalEvidence;children:React.ReactNode}){return <div className="bg-white p-6"><Evidence value={evidence}/><p className="mt-4 leading-relaxed text-zinc-700">{children}</p></div>}
function Fact({label,children}:{label:string;children:React.ReactNode}){return <div><dt className="text-[.65rem] font-bold uppercase tracking-[.12em] text-zinc-500">{label}</dt><dd className="mt-2 text-zinc-700">{children}</dd></div>}
function FactBox({title,status,children}:{title:string;status:string;children:React.ReactNode}){return <article className="border border-zinc-300 bg-white p-5"><p className="text-[.62rem] font-bold uppercase tracking-[.12em] text-zinc-500">{status}</p><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-4 text-sm leading-relaxed text-zinc-600">{children}</p></article>}
function ScenarioTable(){return <div className="mt-7 grid gap-px bg-zinc-300 sm:grid-cols-2 lg:grid-cols-4">{computeLoadsKw.map(load=>{const p=powerScenario(load);return <div className="bg-[#f3f2ec] p-5" key={load}><p className="text-xs font-bold">{formatPower(load)} compute</p><p className="mt-4 text-2xl font-semibold">{formatArea(p.arrayAreaM2)}</p><p className="text-xs text-zinc-500">power collection area</p><p className="mt-4 text-2xl font-semibold">{formatArea(radiatorAreaM2(load,350))}</p><p className="text-xs text-zinc-500">ideal radiator at 350 K</p></div>})}</div>}
function ThermalTable(){return <div className="mt-7"><div className="grid grid-cols-4 border-b border-zinc-400 pb-3 text-xs font-bold uppercase tracking-[.1em]"><span>Heat</span>{radiatorTemperaturesK.map(t=><span className="text-right" key={t}>{t} K</span>)}</div>{computeLoadsKw.map(load=><div className="grid grid-cols-4 border-b border-zinc-300 py-4 text-sm" key={load}><strong>{formatPower(load)}</strong>{radiatorTemperaturesK.map(t=><span className="text-right" key={t}>{formatArea(radiatorAreaM2(load,t))}</span>)}</div>)}</div>}
function LaunchTable(){return <div><div className="grid grid-cols-4 border-b border-zinc-400 pb-3 text-xs font-bold uppercase tracking-[.08em]"><span>Scenario $/kg</span>{launchMassesTonnes.map(m=><span className="text-right" key={m}>{formatMass(m*1000)}</span>)}</div>{launchPricesUsdKg.map(price=><div className="grid grid-cols-4 border-b border-zinc-300 py-4 text-sm" key={price}><strong>${price.toLocaleString()}/kg</strong>{launchMassesTonnes.map(m=><span className="text-right" key={m}>{formatUsd(m*1000*price)}</span>)}</div>)}</div>}
function ResponsiveRows({headers,rows}:{headers:readonly string[];rows:readonly (readonly string[])[]}){return <div className="divide-y divide-zinc-300 border-y border-zinc-300"><div className="hidden grid-cols-6 gap-3 py-3 text-[.65rem] font-bold uppercase tracking-[.1em] lg:grid">{headers.map(x=><span key={x}>{x}</span>)}</div>{rows.map(row=><div className="grid gap-3 py-5 text-sm sm:grid-cols-2 lg:grid-cols-6" key={row[0]}>{row.map((cell,i)=><div key={headers[i]}><span className="text-[.6rem] font-bold uppercase tracking-[.1em] text-zinc-500 lg:hidden">{headers[i]}</span><p className={i===0?'font-semibold':''}>{cell}</p></div>)}</div>)}</div>}
const formatPower=(kw:number)=>kw>=1000?`${kw/1000} MW`:`${kw} kW`
const formatArea=(m2:number)=>m2>=10000?`${(m2/1e6).toFixed(2)} km²`:`${Math.round(m2).toLocaleString()} m²`
const formatMass=(kg:number)=>kg>=1000?`${(kg/1000).toLocaleString()} t`:`${Math.round(kg)} kg`
const formatUsd=(usd:number)=>usd>=1e9?`$${(usd/1e9).toFixed(1)}bn`:`$${(usd/1e6).toFixed(0)}m`
