import { Link } from 'react-router-dom'
import { autonomousComputeNode as experiment } from '../data/orbitalExperiments'
import { computeCandidates, gateA, requirements, workloads } from '../data/orbitalExperimentEngineering'

const contact='mailto:alex@albedo-industries.com?subject=Albedo%20Orbital%20Experiment%2001'
const phases=[['A0','Baseline','Run repeatable workloads; measure power, temperature, valid work and errors.'],['A1','Software recovery','Inject process, container and service failures.'],['A2','Communications','Constrain bandwidth, add latency and interrupt connectivity.'],['A3','Power','Use safe controlled interruptions, reduced budgets, transitions and load shedding.'],['A4','Thermal','Test awareness, throttling, safe shutdown and recovery within manufacturer limits.'],['A5','Combined conditions','Run representative combinations only after isolated tests are understood.'],['A6','Long-duration run','Operate continuously with autonomous monitoring; duration follows the baseline.']] as const
const faults=[['Workload','Process crash','Restart, validate output and resume'],['Orchestration','Container or service failure','Recreate service and restore workload state'],['Network','Loss, latency, bandwidth limit','Continue locally; prioritize health telemetry'],['Storage','Read-only state or filesystem pressure','Protect data; checkpoint or enter safe mode'],['Memory','Safe synthetic pressure','Shed load or restart affected workload'],['Accelerator','Process failure or supported driver reset','Recover workload without unsafe hardware action'],['Node','Controlled reboot','Watchdog restart and state restoration'],['Input','Corrupted non-critical test input','Reject input and preserve known-good state']] as const
const architecture=['Power input','Power monitoring / control','Compute node','Workload orchestrator','Health / telemetry agent','Remote control layer','Logging / experiment database']
const stageBMeasurements=['Radiation-related events','Reboots and unexpected resets','Memory, processor and storage errors','Temperature and electrical power','Workload performance and valid output','Communications interruptions','Automatic recovery and intervention burden','Useful compute uptime against ground baseline']

export default function OrbitalExperiment(){return <article className="bg-[#f3f2ec] text-zinc-950">
  <header className="border-b border-zinc-700 bg-zinc-950 text-white"><div className="mx-auto max-w-6xl px-5 py-24 sm:px-6 md:py-32"><p className="text-xs font-bold uppercase tracking-[.2em] text-zinc-400">Albedo Orbital — Experiment 01</p><h1 className="mt-6 max-w-5xl text-5xl font-semibold leading-[.96] tracking-[-.04em] sm:text-6xl md:text-7xl">Autonomous Compute Node.</h1><p className="mt-7 max-w-4xl text-lg leading-relaxed text-zinc-300">{experiment.subtitle}</p><div className="mt-8 flex flex-wrap gap-2 text-[.65rem] font-bold uppercase tracking-[.13em]"><span className="bg-white px-3 py-2 text-zinc-950">Experiment design</span><span className="border border-zinc-600 px-3 py-2">No measured results</span><span className="border border-zinc-600 px-3 py-2">Reviewed 13 September 2026</span></div></div></header>
  <ESection n="01" eyebrow="Research question" title={experiment.researchQuestion}><div className="grid gap-5 md:grid-cols-2"><p className="text-lg leading-relaxed text-zinc-700">The experiment asks how often intervention is required, how quickly valid work recovers, which failures cannot be recovered remotely, and how much telemetry is necessary when power, thermal headroom and communications vary.</p><Panel label="Technical risk retired">Whether a small compute node can demonstrate credible low-intervention operation before ALBEDO considers space-environment testing.</Panel></div></ESection>
  <ESection n="02" eyebrow="Why Earth first" title="Test autonomy before adding spacecraft complexity." intro="The immediate objective is reliability, recovery and remote operations—not maximum AI performance. A terrestrial node can expose software and operational failures without launch, spacecraft or mission-operations dependencies."><div className="grid gap-px bg-zinc-300 md:grid-cols-2"><Panel label="Stage A · Immediate">Terrestrial autonomous compute node. Hardware class remains open until requirements and instrumentation are defined.</Panel><Panel label="Stage B · Conditional">Hosted low-Earth-orbit demonstrator only if Stage A produces evidence that earns progression.</Panel></div></ESection>
  <ESection n="03" eyebrow="Conceptual architecture" title="Independent supervision around a replaceable compute node." intro="No component has been purchased. Consumer or workstation GPUs, edge accelerators, server CPUs, ARM systems and embedded accelerators remain candidates."><div role="img" aria-label="Conceptual experiment blocks from power input through logging, with an independent watchdog supervising power, compute and control" className="grid gap-px bg-zinc-400 md:grid-cols-7">{architecture.map((item,i)=><div className="relative bg-zinc-950 p-5 text-white" key={item}><span className="text-[.62rem] text-zinc-500">0{i+1}</span><p className="mt-4 text-sm font-semibold">{item}</p>{i<architecture.length-1&&<span aria-hidden="true" className="absolute -bottom-4 left-1/2 z-10 md:-right-3 md:bottom-auto md:left-auto md:top-1/2">↓</span>}</div>)}</div><div className="mt-5 border border-amber-600 bg-amber-50 p-5"><p className="text-xs font-bold uppercase tracking-[.14em]">Independent watchdog path</p><p className="mt-2 text-sm text-zinc-700">Separate heartbeat, local fallback and remotely switchable power capability should supervise the main compute and control stack. Exact implementation remains a requirement decision.</p></div></ESection>
  <ESection n="03A" eyebrow="Ground node design" title="Engineering freeze in progress." intro="The detailed requirements, BOM, instrumentation and review package remain internal to the repository. This public summary shows the decision logic without presenting unverified procurement details."><div className="grid gap-5 lg:grid-cols-3"><Panel label="Recommended baseline">{computeCandidates[0].exampleClass}. Conditional on exact SKU, official specification, price and availability verification. Selected for measurability and low-power accelerated evidence—not headline TOPS.</Panel><Panel label="Fallback">{computeCandidates[2].exampleClass}. Conventional Linux tooling reduces software risk, but power and remote-control interfaces vary by model.</Panel><Panel label="Design guidance">A compute-module envelope around or below 25 W may preserve more hosted options. It is guidance, not a fixed requirement or flight qualification.</Panel></div><div className="mt-7 grid gap-px bg-zinc-300 sm:grid-cols-2 lg:grid-cols-4">{['Requirements',`${requirements.filter(x=>x.priority==='MUST').length} MUST requirements`,'Workloads',`${workloads.length} validity-checkable workloads`,'Gate A',gateA.threshold,'Procurement','DO NOT ORDER before review'].map((x,i)=><div className="bg-white p-4 text-sm" key={`${x}-${i}`}>{x}</div>)}</div></ESection>
  <ESection n="04" eyebrow="Experimental sequence" title="Isolate faults before combining them."><ol className="grid gap-px bg-zinc-300 sm:grid-cols-2 lg:grid-cols-4">{phases.map(([id,title,copy])=><li className="bg-white p-5" key={id}><span className="text-xs text-zinc-400">PHASE {id}</span><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-3 text-sm text-zinc-600">{copy}</p></li>)}</ol></ESection>
  <ESection n="05" eyebrow="Safe fault injection" title="Recoverable software and operating conditions—not destructive testing." intro="Every test must remain within manufacturer operating limits and include a rollback or safe-state procedure."><Rows headers={['Domain','Injected condition','Expected response']} rows={faults}/></ESection>
  <ESection n="06" eyebrow="Power, thermal and communications" title="Constrain the environment safely."><div className="grid gap-5 md:grid-cols-3"><TestBlock title="Variable power" items={['Normal operation','Reduced power budget','Controlled interruption','Repeated short interruption','Slow restart','Battery-supported transition','Forced load shedding']}/><TestBlock title="Thermal response" items={['Restricted airflow within safe limits','Elevated safe ambient temperature','Fan-degradation simulation','Compute-load changes','Throttling','Safe shutdown and recovery','No vacuum simulation']}/><TestBlock title="Communications" items={['High latency','Limited bandwidth','Temporary loss','Intermittent connection','Telemetry prioritization','Local fallback','Workload data separated from health data']}/></div></ESection>
  <ESection n="07" eyebrow="Repeatable workloads" title="Useful work must be countable."><div className="grid gap-px bg-zinc-300 md:grid-cols-2"><Panel label="Workload A · Continuous inference / compute">Measure valid work per watt, uninterrupted operation, throttling and recovery. The exact model and platform remain unselected.</Panel><Panel label="Workload B · Batch processing">Measure checkpointing, restart, duplicate-work prevention and task continuation following interruption.</Panel></div></ESection>
  <ESection n="08" eyebrow="Planned metrics" title="Baseline first. Targets second." intro="No metric below contains a measured value. Thresholds remain undefined until the baseline establishes variance and measurement quality."><div className="divide-y divide-zinc-300 border-y border-zinc-300">{experiment.metrics.map(metric=><article className="grid gap-3 py-5 md:grid-cols-[13rem_1fr_12rem]" key={metric.id}><div><h3 className="font-semibold">{metric.name}</h3><p className="mt-1 text-xs text-zinc-500">{metric.unit}</p></div><p className="text-sm text-zinc-600">{metric.definition}</p><p className="text-xs font-bold uppercase tracking-[.1em] text-zinc-500">{metric.target}</p></article>)}</div><div className="mt-8 bg-zinc-950 p-7 text-white"><p className="text-xs font-bold uppercase tracking-[.15em] text-amber-200">Headline metric</p><h3 className="mt-3 text-3xl font-semibold">Intervention burden</h3><p className="mt-4 max-w-3xl text-zinc-400">Human physical or remote manual interventions per 1,000 operating hours. No target is claimed before baseline evidence exists.</p></div></ESection>
  <ESection n="09" eyebrow="Gate A" title="Does the architecture demonstrate credible low-intervention operation?" intro="The decision considers recovery, workload continuity, data integrity, intervention burden, telemetry requirements and energy efficiency. The outcome is not forced."><div className="grid gap-px bg-zinc-300 md:grid-cols-3"><Panel label="Pass">Proceed to space-environment feasibility only if evidence and independent review justify it.</Panel><Panel label="Partial">Redesign and repeat the terrestrial experiment.</Panel><Panel label="Fail">Stop progression or select a materially different architecture.</Panel></div></ESection>
  <ESection n="10" eyebrow="Stage B · Conditional" title="A hosted orbital test—not a standalone satellite." intro="Stage B would ask whether a compact node can execute useful workloads, recover from faults and be remotely managed in the actual space environment. Hosted infrastructure is preferred to reduce spacecraft, launch integration, power, communications and mission-operations scope."><div className="grid gap-8 lg:grid-cols-[1fr_.8fr]"><div><h3 className="font-semibold">Hosted paths requiring primary-source research</h3><ul className="mt-4 grid gap-2 text-sm text-zinc-600 sm:grid-cols-2">{['ISS National Laboratory internal facilities','ISS external payload facilities','ICE Cubes internal infrastructure','Commercial station providers','Commercial orbital platforms','CubeSat hosted-payload services'].map(x=><li className="border border-zinc-300 p-3" key={x}>{x} · SOURCE REQUIRED</li>)}</ul></div><Panel label="Stage B hardware requirements">Low mass and volume · measurable power · thermal telemetry · remote reset · error logging · ECC where possible · watchdog · checkpointing · radiation monitoring where feasible.</Panel></div></ESection>
  <ESection n="11" eyebrow="Ground versus orbit" title="Measure environment-dependent behavior."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{stageBMeasurements.map(x=><div className="border border-zinc-300 bg-white p-4 text-sm" key={x}>{x}</div>)}</div><p className="mt-6 text-sm text-zinc-600">Stage B would investigate observed errors and mitigation behavior. It would not fully qualify commercial hardware because results depend on orbit, shielding, duration and the selected platform.</p></ESection>
  <ESection n="12" eyebrow="What this does not prove" title="One node is not an orbital data center."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[...experiment.notRetired,'Qualification of hardware for space','Commercial orbital economics','A provider, payload acceptance or launch commitment'].map(x=><div className="border-l-2 border-zinc-500 pl-4 text-sm text-zinc-700" key={x}>{x}</div>)}</div></ESection>
  <ESection n="13" eyebrow="Partners and first capital" title="First capital should buy evidence." intro="Potential uses are Stage A hardware, instrumentation, software, test infrastructure, engineering and independent review. Stage B design, environmental testing, integration and a flight opportunity remain conditional; no amount or commitment is claimed."><div className="grid gap-px bg-zinc-300 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(experiment.partnerNeeds).map(([name,items])=><TestBlock title={name} items={items} key={name}/>)}</div></ESection>
  <ESection n="14" eyebrow="Preliminary work packages" title="Ground evidence before flight scope."><div className="divide-y divide-zinc-300 border-y border-zinc-300">{experiment.workPackages.map(wp=><div className="grid grid-cols-[4rem_1fr_auto] gap-4 py-4 text-sm" key={wp.id}><strong>{wp.id}</strong><span>{wp.name}</span><span className="text-xs font-bold text-zinc-500">{wp.status}</span></div>)}</div></ESection>
  <ESection n="15" eyebrow="Current status" title="Design only."><div className="grid gap-px bg-zinc-300 sm:grid-cols-2 lg:grid-cols-5"><Status label="Current status" value="EXPERIMENT DESIGN"/><Status label="Ground hardware" value="NOT YET ASSEMBLED"/><Status label="Flight hardware" value="NOT YET DESIGNED"/><Status label="Flight provider" value="NOT SELECTED"/><Status label="Launch" value="NOT BOOKED"/></div></ESection>
  <section className="bg-zinc-950 text-white"><div className="mx-auto flex max-w-6xl flex-col gap-8 px-5 py-16 sm:px-6 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-zinc-500">Experiment 01</p><h2 className="mt-3 text-3xl font-semibold md:text-5xl">Help define the baseline.</h2></div><div className="flex flex-col gap-3 sm:flex-row"><a href={contact} className="inline-flex min-h-12 items-center justify-center bg-white px-6 text-sm font-semibold text-zinc-950">Discuss technical collaboration</a><Link to="/orbital/research" className="inline-flex min-h-12 items-center justify-center border border-zinc-600 px-6 text-sm font-semibold">Review Orbital research</Link></div></div></section>
</article>}

function ESection({n,eyebrow,title,intro,children}:{n:string;eyebrow:string;title:string;intro?:string;children:React.ReactNode}){return <section className="border-b border-zinc-300"><div className="mx-auto max-w-6xl px-5 py-20 sm:px-6 md:py-24"><p className="text-xs font-bold uppercase tracking-[.16em] text-zinc-500">{n} · {eyebrow}</p><h2 className="mt-4 max-w-4xl text-3xl font-semibold tracking-tight sm:text-4xl md:text-5xl">{title}</h2>{intro&&<p className="mt-6 max-w-4xl text-lg leading-relaxed text-zinc-600">{intro}</p>}<div className="mt-10">{children}</div></div></section>}
function Panel({label,children}:{label:string;children:React.ReactNode}){return <article className="bg-white p-6"><p className="text-[.65rem] font-bold uppercase tracking-[.13em] text-zinc-500">{label}</p><p className="mt-4 leading-relaxed text-zinc-700">{children}</p></article>}
function TestBlock({title,items}:{title:string;items:readonly string[]}){return <article className="bg-white p-5"><h3 className="text-sm font-bold uppercase tracking-[.13em]">{title}</h3><ul className="mt-4 space-y-2 text-sm text-zinc-600">{items.map(x=><li key={x}>— {x}</li>)}</ul></article>}
function Status({label,value}:{label:string;value:string}){return <div className="bg-zinc-950 p-5 text-white"><p className="text-[.62rem] uppercase tracking-[.12em] text-zinc-500">{label}</p><p className="mt-4 text-sm font-semibold">{value}</p></div>}
function Rows({headers,rows}:{headers:readonly string[];rows:readonly (readonly string[])[]}){return <div className="divide-y divide-zinc-300 border-y border-zinc-300">{rows.map(row=><div className="grid gap-3 py-5 text-sm md:grid-cols-3" key={row[0]+row[1]}>{row.map((cell,i)=><div key={headers[i]}><span className="text-[.6rem] font-bold uppercase tracking-[.1em] text-zinc-500 md:hidden">{headers[i]}</span><p className={i===0?'font-semibold':''}>{cell}</p></div>)}</div>)}</div>}
