const email='alex@albedo-industries.com'
export default function Terms(){return <article className="mx-auto max-w-5xl px-6 py-24 md:py-32"><header className="max-w-3xl"><p className="eyebrow">Website notice</p><h1 className="mt-4 text-4xl font-semibold tracking-tight md:text-6xl">Website terms</h1><p className="mt-5 text-zinc-500">Last reviewed: 13 September 2026</p></header><div className="mt-14 max-w-3xl space-y-10 border-t border-zinc-200 pt-10 text-zinc-600 leading-relaxed">
<section><h2 className="text-xl font-semibold text-zinc-900">Informational website</h2><p className="mt-3">This website presents ALBEDO Industries initiatives, research records, concepts and demonstrations. It is not an offer of securities, a promise of returns, professional advice or a representation that any infrastructure opportunity is available for investment.</p></section>
<section><h2 className="text-xl font-semibold text-zinc-900">Evidence and development status</h2><p className="mt-3">Research may change as evidence develops. Unless a page expressly documents otherwise, publication does not establish control of land, grid capacity, permits, financing, customers, operators or commercial rights. Visitors must conduct their own technical, legal, commercial and financial diligence before acting.</p></section>
<section><h2 className="text-xl font-semibold text-zinc-900">Acceptable use</h2><p className="mt-3">You may use public pages and linked materials for lawful evaluation and reference. Do not interfere with the site, attempt unauthorized access, introduce harmful code, misrepresent ALBEDO material or remove source and status context from research.</p></section>
<section><h2 className="text-xl font-semibold text-zinc-900">Content and third-party sources</h2><p className="mt-3">ALBEDO-created text, design and materials remain subject to applicable intellectual-property rights. Source links are provided for transparency; third parties control their own content and availability. The site may be corrected, updated or withdrawn without notice.</p></section>
<section><h2 className="text-xl font-semibold text-zinc-900">No website warranty</h2><p className="mt-3">The public website is provided on an informational, as-available basis. ALBEDO does not guarantee uninterrupted availability, completeness or suitability for a particular decision. Nothing here creates a partnership, agency, fiduciary relationship or transaction.</p></section>
<section><h2 className="text-xl font-semibold text-zinc-900">Contact</h2><p className="mt-3">Questions about these website terms may be sent to <a className="font-semibold text-zinc-900 underline" href={`mailto:${email}?subject=Website%20terms`}>{email}</a>. Any project or product engagement will require its own agreed scope and, where appropriate, separate terms.</p></section>
</div></article>}
