import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import CandidateMap from './CandidateMap'
import ComputeInterestForm from './ComputeInterestForm'
import { EvidenceBadge } from './ResearchIndicators'
import type { AtlasCandidatePublication, AtlasLanguage } from '../data/candidatePublications'
import type { InfrastructureCandidate } from '../data/infrastructureCandidates'

export default function AtlasCandidatePage({ candidate, publication }: { candidate: InfrastructureCandidate; publication: AtlasCandidatePublication }) {
  const [language, setLanguage] = useState<AtlasLanguage>(publication.localLanguage)
  const copy = useMemo(() => (publication.copy[language] ?? publication.copy[publication.localLanguage])!, [language, publication])
  const languages = [publication.localLanguage, publication.secondaryLanguage].filter((item, index, list) => list.indexOf(item) === index)
  const tag = { id: candidate.id, slug: candidate.slug, name: candidate.name, country: candidate.country, countryCode: candidate.countryCode }

  useEffect(() => {
    const oldTitle = document.title
    const meta = document.querySelector('meta[name="description"]')
    const canonical = document.querySelector('link[rel="canonical"]')
    const oldDescription = meta?.getAttribute('content')
    const oldCanonical = canonical?.getAttribute('href')
    document.title = `${publication.locationName} · Atlas Candidate | Albedo Industries`
    meta?.setAttribute('content', copy.proposition)
    canonical?.setAttribute('href', `https://www.albedo-industries.com${candidate.route}`)
    return () => { document.title = oldTitle; if (oldDescription) meta?.setAttribute('content', oldDescription); if (oldCanonical) canonical?.setAttribute('href', oldCanonical) }
  }, [candidate.route, copy.proposition, publication.locationName])

  return <div className="bg-white text-zinc-950">
    <section className="relative isolate overflow-hidden bg-zinc-950 text-white">
      <HeroVisual publication={publication} />
      <div className="mx-auto grid min-h-[76vh] max-w-7xl gap-10 px-6 py-10 md:grid-cols-[1fr_.82fr] md:items-center md:py-16">
        <div>
          <div className="flex flex-wrap items-center gap-3"><Link to="/infrastructure/europe" className="text-sm text-zinc-300 hover:text-white">{copy.backLabel}</Link><div className="rounded-full border border-white/15 bg-white/10 p-1 text-xs">{languages.map((item) => <button key={item} onClick={() => setLanguage(item)} className={`rounded-full px-3 py-1 ${language === item ? 'bg-white text-zinc-950' : 'text-zinc-300'}`}>{item.toUpperCase()}</button>)}</div></div>
          <div className="mt-10 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-amber-300 px-3 py-1 font-medium text-zinc-950">{copy.statusLabel}</span><span className="rounded-full border border-white/15 px-3 py-1 text-zinc-200">{publication.gate} · {publication.publicStatus}</span></div>
          <p className="mt-8 text-sm uppercase tracking-[.25em] text-amber-200">{publication.locationName} · {publication.region}</p><h1 className="mt-4 max-w-4xl text-5xl font-semibold tracking-tight md:text-7xl">{copy.headline}</h1><p className="mt-6 max-w-2xl text-xl leading-relaxed text-zinc-200">{copy.proposition}</p>
          <p className="mt-6 max-w-3xl border-l border-amber-300 pl-4 text-sm text-zinc-300">{copy.boundaryDisclaimer}</p>
          <div className="mt-9 flex flex-wrap gap-3"><a href="#decisive-question" className="inline-flex min-h-12 items-center rounded-full bg-white px-6 text-sm font-semibold text-zinc-950">{copy.primaryCta}</a><a href={publication.report.href} download={publication.report.downloadName} className="inline-flex min-h-12 items-center rounded-full border border-white/25 px-6 text-sm font-semibold text-white">{copy.secondaryCta}</a></div><p className="mt-5 text-xs text-zinc-400">{copy.reviewed}</p>
        </div>
        <div className="rounded-[2rem] border border-white/10 bg-white/10 p-4 shadow-2xl backdrop-blur"><VisualBlock alt={publication.media.heroAlt}><div className="absolute bottom-10 left-8 right-8 rounded-2xl border border-amber-200/30 bg-zinc-950/80 p-6 backdrop-blur"><p className="text-xs uppercase tracking-[.2em] text-amber-200">{publication.gate}</p><p className="mt-3 text-3xl font-semibold">{copy.decisiveQuestion.question}</p><p className="mt-3 text-amber-200">{copy.decisiveQuestion.currentAnswer}</p></div></VisualBlock></div>
      </div>
    </section>

    <section className="mx-auto max-w-7xl px-6 py-10"><div className="grid gap-4 md:grid-cols-4">{copy.metrics.map((metric) => <article key={metric.label} className="rounded-3xl border border-zinc-200 bg-zinc-50 p-6"><div className="flex items-start justify-between gap-3"><p className="text-4xl font-semibold tracking-tight">{metric.value}</p><EvidenceBadge state={metric.evidenceStatus} locale={language === 'es' ? 'es' : 'en'} /></div><h2 className="mt-3 text-sm font-semibold uppercase tracking-[.16em] text-zinc-500">{metric.label}</h2>{metric.explanation && <p className="mt-4 text-sm leading-relaxed text-zinc-600">{metric.explanation}</p>}</article>)}</div></section>
    <section className="mx-auto grid max-w-7xl gap-5 px-6 py-8 md:grid-cols-3">{copy.opportunityCards.map((card) => <article key={card.title} className="rounded-[2rem] bg-zinc-950 p-7 text-white"><div className="flex items-center justify-between"><div className="text-4xl">{card.icon}</div><EvidenceBadge state={card.evidenceClassification} locale={language === 'es' ? 'es' : 'en'} /></div><h2 className="mt-8 text-2xl font-semibold">{card.title}</h2><p className="mt-4 text-sm leading-relaxed text-zinc-300">{card.explanation}</p></article>)}</section>
    <section id="decisive-question" className="mx-auto max-w-7xl px-6 py-12"><div className="rounded-[2.5rem] bg-amber-300 p-8 md:p-12"><div className="flex flex-wrap items-center gap-3"><p className="text-sm font-semibold uppercase tracking-[.18em] text-zinc-700">{publication.gate}</p><EvidenceBadge state={copy.decisiveQuestion.status} locale={language === 'es' ? 'es' : 'en'} /></div><h2 className="mt-4 max-w-4xl text-4xl font-semibold tracking-tight md:text-6xl">{copy.decisiveQuestion.question}</h2><p className="mt-6 text-3xl font-semibold text-zinc-950">{copy.decisiveQuestion.currentAnswer}</p><p className="mt-4 max-w-3xl text-lg leading-relaxed text-zinc-800">{copy.decisiveQuestion.explanation}</p><p className="mt-5 rounded-2xl bg-white/60 p-4 text-sm text-zinc-800"><strong>{language === 'es' ? 'Próxima comprobación:' : 'Evidence needed:'}</strong> {copy.decisiveQuestion.evidenceNeeded}</p></div></section>
    <section className="mx-auto max-w-7xl px-6 py-10"><h2 className="text-3xl font-semibold">{copy.audienceTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-3 lg:grid-cols-5">{copy.ctas.map((cta) => <a key={cta.kind} href={cta.href} download={cta.kind === 'download' ? publication.report.downloadName : undefined} className="rounded-3xl border border-zinc-200 p-6 transition hover:-translate-y-1 hover:border-zinc-950"><h3 className="text-lg font-semibold">{cta.label}</h3><p className="mt-3 text-sm leading-relaxed text-zinc-600">{cta.description}</p></a>)}</div></section>
    <section className="mx-auto grid max-w-7xl gap-6 px-6 py-10 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-[2rem] border border-zinc-200 p-6"><h2 className="text-2xl font-semibold">{copy.boundariesTitle}</h2><div className="mt-5 flex flex-wrap gap-2">{copy.boundaries.map((item) => <span key={item} className="rounded-full bg-zinc-100 px-4 py-2 text-sm text-zinc-700">{item}</span>)}</div><a href={publication.report.href} download={publication.report.downloadName} className="mt-8 inline-flex min-h-12 items-center rounded-full bg-zinc-950 px-6 text-sm font-semibold text-white">{copy.ctas.find((cta) => cta.kind === 'download')?.label}</a></div>{publication.media.mapEnabled ? <CandidateMap candidate={candidate}/> : <VisualBlock alt="Regional visual fallback" lazy />}</section>
    <section className="mx-auto max-w-7xl px-6 py-8"><details className="rounded-3xl border border-zinc-200 bg-zinc-50 p-6"><summary className="cursor-pointer text-xl font-semibold">{copy.technicalTitle}</summary><p className="mt-5 max-w-3xl text-sm leading-relaxed text-zinc-600">{copy.technicalSummary}</p><TechnicalList title={language === 'es' ? 'Hechos comprobados' : 'Verified facts'} items={copy.verifiedFacts}/><TechnicalList title={language === 'es' ? 'Pendiente de comprobar' : 'Evidence required'} items={copy.evidenceRequired}/><TechnicalList title={language === 'es' ? 'Riesgos principales' : 'Major risks'} items={copy.majorRisks}/><p className="mt-6 rounded-2xl bg-white p-4 text-sm font-medium text-zinc-800">{copy.gateDecision}</p><TechnicalList title={copy.sourcesTitle} items={candidate.sources.map((source) => `${source.id}: ${source.title} — ${source.publisher}`)}/><TechnicalList title={copy.updatesTitle} items={candidate.updates.map((update) => `${update.date}: ${update.title}`)}/></details></section>
    <section id="candidate-demand" className="border-t border-zinc-200"><div className="mx-auto max-w-6xl px-6 py-16"><p className="eyebrow">Atlas</p><h2 className="section-title">{copy.ctas.find((cta) => cta.kind === 'capacity')?.label}</h2><ComputeInterestForm kind="capacity" candidate={tag} locale={language === 'es' ? 'es' : 'en'}/></div></section>
    <section id="partner-context" className="border-t border-zinc-200 bg-zinc-50"><div className="mx-auto max-w-6xl px-6 py-16"><p className="eyebrow">Atlas</p><h2 className="section-title">{copy.ctas.find((cta) => cta.kind === 'partner')?.label}</h2><ComputeInterestForm kind="investor" candidate={tag} locale={language === 'es' ? 'es' : 'en'}/></div></section>
    <section id="follow-project" className="border-t border-zinc-200"><div className="mx-auto max-w-6xl px-6 py-16"><p className="eyebrow">Updates</p><h2 className="section-title">{copy.ctas.find((cta) => cta.kind === 'follow')?.label}</h2><a className="section-copy underline underline-offset-4" href="mailto:alex@albedo-industries.com?subject=Atlas%20candidate%20updates">alex@albedo-industries.com</a></div></section>
  </div>
}

function HeroVisual({ publication }: { publication: AtlasCandidatePublication }) { return publication.media.heroImage ? <img className="absolute inset-0 -z-10 h-full w-full object-cover opacity-45" src={publication.media.heroImage} alt="" aria-hidden="true" /> : <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_20%_20%,rgba(251,191,36,.35),transparent_26%),radial-gradient(circle_at_80%_10%,rgba(14,165,233,.28),transparent_24%),linear-gradient(135deg,#09090b_0%,#18181b_45%,#3f2f12_100%)]" /> }
function VisualBlock({ children, alt, lazy = false }: { children?: React.ReactNode; alt: string; lazy?: boolean }) { return <div className="relative min-h-[420px] overflow-hidden rounded-[1.5rem] bg-zinc-900 p-6" role="img" aria-label={alt} data-loading={lazy ? 'lazy' : 'eager'}><div className="absolute inset-0 bg-[linear-gradient(120deg,rgba(251,191,36,.18),transparent_40%),repeating-linear-gradient(90deg,rgba(255,255,255,.08)_0_1px,transparent_1px_54px),repeating-linear-gradient(0deg,rgba(255,255,255,.07)_0_1px,transparent_1px_54px)]" />{children}</div> }
function TechnicalList({ title, items }: { title: string; items: string[] }) { return <div className="mt-6"><h3 className="text-sm font-semibold uppercase tracking-[.16em] text-zinc-500">{title}</h3><ul className="mt-3 grid gap-3 md:grid-cols-2">{items.map((item) => <li key={item} className="rounded-2xl bg-white p-4 text-sm text-zinc-700">{item}</li>)}</ul></div> }
