import { useState, useEffect } from 'react'

interface AudioDemo {
  name: string
  file: string
}

export default function BeatFlowListen() {
  const [demos, setDemos] = useState<AudioDemo[]>([])
  const [loading, setLoading] = useState(true)
  const [currentPlaying, setCurrentPlaying] = useState<string | null>(null)

  useEffect(() => {
    const checkAudioFiles = async () => {
      const basePath = import.meta.env.BASE_URL || '/'
      const demoFiles = [
        { name: 'Ambient Flow', file: 'ambient-flow.mp3' },
        { name: 'Rhythmic Evolution', file: 'rhythmic-evolution.mp3' },
        { name: 'Harmonic Journey', file: 'harmonic-journey.mp3' },
      ]

      const availableDemos: AudioDemo[] = []

      for (const demo of demoFiles) {
        try {
          const response = await fetch(`${basePath}audio/beatflow/${demo.file}`, { method: 'HEAD' })
          if (response.ok) {
            availableDemos.push(demo)
          }
        } catch {
          // File not available
        }
      }

      setDemos(availableDemos)
      setLoading(false)
    }

    checkAudioFiles()
  }, [])

  if (loading) {
    return (
      <div className="border border-zinc-200 rounded-lg p-8">
        <div className="flex items-center justify-center">
          <div className="animate-pulse flex space-x-2">
            <div className="h-2 w-2 bg-zinc-300 rounded-full"></div>
            <div className="h-2 w-2 bg-zinc-300 rounded-full"></div>
            <div className="h-2 w-2 bg-zinc-300 rounded-full"></div>
          </div>
        </div>
      </div>
    )
  }

  if (demos.length === 0) {
    return (
      <div className="border border-zinc-200 rounded-lg p-8 bg-zinc-50/50">
        <div className="text-center">
          <div className="w-12 h-12 mx-auto mb-4 bg-zinc-100 rounded-full flex items-center justify-center">
            <svg className="w-6 h-6 text-zinc-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zM9 10l12-3" />
            </svg>
          </div>
          <h3 className="text-lg font-medium text-zinc-900 mb-2">Audio demos coming soon</h3>
          <p className="text-sm text-zinc-500 max-w-sm mx-auto">
            We're preparing sample sessions to showcase BeatFlow's evolving generation. Check back soon.
          </p>
        </div>
      </div>
    )
  }

  const basePath = import.meta.env.BASE_URL || '/'

  return (
    <div className="border border-zinc-200 rounded-lg overflow-hidden">
      <div className="bg-zinc-50 border-b border-zinc-200 px-6 py-4">
        <h4 className="font-medium text-zinc-900">Sample Sessions</h4>
        <p className="text-sm text-zinc-500 mt-1">
          Each recording captures a unique BeatFlow session—no two are alike.
        </p>
      </div>
      <div className="divide-y divide-zinc-100">
        {demos.map((demo) => (
          <div key={demo.file} className="p-4">
            <div className="flex items-center justify-between mb-3">
              <span className="font-medium text-zinc-900">{demo.name}</span>
              {currentPlaying === demo.file && (
                <span className="text-xs text-blue-600 bg-blue-50 px-2 py-0.5 rounded-full">
                  Playing
                </span>
              )}
            </div>
            <audio
              controls
              className="w-full h-10"
              onPlay={() => setCurrentPlaying(demo.file)}
              onPause={() => setCurrentPlaying(null)}
              onEnded={() => setCurrentPlaying(null)}
            >
              <source src={`${basePath}audio/beatflow/${demo.file}`} type="audio/mpeg" />
              Your browser does not support the audio element.
            </audio>
          </div>
        ))}
      </div>
      <div className="bg-zinc-50 border-t border-zinc-200 px-6 py-3">
        <p className="text-xs text-zinc-400">
          All audio is generated by BeatFlow. No copyrighted material.
        </p>
      </div>
    </div>
  )
}
