import { fundingGates, fundingLedger, useOfFundsCategories, emptyFundingSnapshot, fundingRisks, disclosureFields } from '../data/fundingTransparency'

export function FundingStatusPanel(){const snapshot=emptyFundingSnapshot;const values=[['Non-binding investment interest',snapshot.nonBindingInterest],['Legally committed amount',snapshot.verifiedCommitments],['Funds received',snapshot.fundsReceived],['Funds deployed',snapshot.fundsDeployed]];const reporting=[['Last financial update','Not applicable — funding has not opened'],['Last project update','See dated candidate research record'],['Current funding gate','F0 — illustrative research model'],['Remaining cash','Not applicable — no funds received'],['Gate deliverables','Research scope and evidence requirements only'],['Delayed deliverables','No funded deliverables exist'],['Budget changes and corrections','No financial ledger exists'],['Material risks','Published in the risk section below'],['Next decision date','Decision pending']];return <div><div className="rounded-xl border border-amber-200 bg-amber-50 p-5"><p className="font-semibold text-amber-950">Funding has not opened.</p><p className="mt-2 text-sm text-amber-900">Current state: Research funding model. No targets, commitments, receipts or expenditure are published because no regulated offer or funding structure exists.</p></div><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{values.map(([label,value])=><div className="rounded-xl border border-zinc-200 p-5" key={label}><dt className="text-xs text-zinc-500">{label}</dt><dd className="mt-3 font-semibold">{value===null?'Not reported — funding has not opened':value}</dd></div>)}</dl><dl className="mt-5 grid gap-x-8 gap-y-4 border-y border-zinc-200 py-6 text-sm md:grid-cols-3">{reporting.map(([label,value])=><div key={label}><dt className="text-zinc-400">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>)}</dl></div>}
export function FundingGates(){return <div className="space-y-4">{fundingGates.map(gate=><article className="rounded-xl border border-zinc-200 p-5 md:p-7" key={gate.id}><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">Funding Gate {gate.id} — {gate.name}</h3><span className="rounded-full bg-zinc-100 px-3 py-1 text-xs capitalize">{gate.status} · {gate.classification.replace('_',' ')}</span></div><div className="mt-5 grid gap-5 md:grid-cols-3"><List title="Potential purposes" values={gate.purpose}/><List title="Prerequisites" values={gate.prerequisites}/><List title="Would unlock" values={gate.unlocks}/></div><p className="mt-5 text-xs text-zinc-500">Minimum, maximum, deadline, consequences and refund policy: Decision pending. No amount is currently open or accepted.</p></article>)}</div>}
export function UseOfFunds(){return <div><p className="rounded-xl border border-zinc-200 bg-zinc-50 p-5 font-medium">No investor funds have been received or deployed.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{useOfFundsCategories.map(item=><div className="rounded-lg border border-zinc-200 p-4" key={item.name}><p className="text-sm font-medium">{item.name}</p><p className="mt-2 text-xs text-zinc-500">Budget and expenditure: Not established</p></div>)}</div></div>}
export function FundingLedger(){return <div className="rounded-xl border border-zinc-200 bg-zinc-50 p-6">{fundingLedger.length===0?<><p className="font-semibold">No project funds have been received or spent.</p><p className="mt-2 text-sm text-zinc-600">The future ledger will report approved budgets, commitments, receipts, paid invoices, refunds, reallocations and corrections. It is a conventional public reporting ledger—not a blockchain.</p></>:null}</div>}
export function FundingRisks(){return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{fundingRisks.map(risk=><div className="rounded-lg border border-red-900/50 bg-red-950/20 p-4 text-sm text-red-100" key={risk}>{risk}</div>)}</div>}
export function LegalPlaceholders(){return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{disclosureFields.map(field=><div className="rounded-lg border border-zinc-200 p-4" key={field}><p className="text-xs text-zinc-500">{field}</p><p className="mt-2 text-sm font-medium">Decision pending</p></div>)}</div>}
function List({title,values}:{title:string;values:string[]}){return <div><p className="text-xs font-medium uppercase tracking-wider text-zinc-400">{title}</p><ul className="mt-3 space-y-2 text-sm text-zinc-600">{values.map(value=><li key={value}>— {value}</li>)}</ul></div>}
