import { createContext,useContext,useEffect } from 'react'
import { Link } from 'react-router-dom'
import { SectionLink } from '../SectionLink'

export type AtlasGateStatus='PASS'|'CONDITIONAL PASS'|'CONTINUE RESEARCHING'|'HOLD'|'FAIL'
export type AtlasEvidenceStatus='CONFIRMED'|'STRONGLY INDICATED'|'INDICATED'|'UNVERIFIED'|'UNKNOWN'|'BLOCKER'
export type AtlasScore={dimension:string;opportunity?:number;confidence?:number;note:string}

export type AtlasLocale='en'|'es'|'pt'|'fi'
const LocaleContext=createContext<AtlasLocale>('en')
const ui={
 en:{dimension:'Dimension',levelWord:'LEVEL',back:'Project Atlas candidates',candidate:'Candidate',date:'Research date',state:'Research status',recommendation:'Recommendation',blocker:'Primary blocker / key unknown',download:'Download Full Gate 1 Dossier — PDF',nav:'Candidate sections',opportunity:'Opportunity Score 0–5',confidence:'Evidence Confidence 0–5',assessment:'Assessment',missing:'Not scored',scoreNote:'Opportunity Score and Evidence Confidence are separate. Missing scores remain unscored rather than being converted into false precision.',demand:'ATLAS OPERATOR DEMAND',level:['No contact','Operator conversation','NDA / technical exchange','Written expression of interest','LOI','Capacity reservation / development agreement']},
 es:{dimension:'Dimensión',levelWord:'NIVEL',back:'Candidatos de Project Atlas',candidate:'Candidato',date:'Fecha de investigación',state:'Estado de la investigación',recommendation:'Recomendación',blocker:'Bloqueo principal / incógnita clave',download:'Descargar el dossier completo de Gate 1 — PDF',nav:'Secciones del candidato',opportunity:'Puntuación de Oportunidad 0–5',confidence:'Confianza de la Evidencia 0–5',assessment:'Evaluación',missing:'Sin puntuar',scoreNote:'La Puntuación de Oportunidad y la Confianza de la Evidencia son medidas distintas. La ausencia de puntuación no se convierte en una precisión ficticia.',demand:'DEMANDA DE OPERADORES PARA ATLAS',level:['Sin contacto','Conversación con un operador','NDA / intercambio técnico','Manifestación de interés por escrito','LOI','Reserva de capacidad / acuerdo de desarrollo']},
 pt:{dimension:'Dimensão',levelWord:'NÍVEL',back:'Candidatos do Project Atlas',candidate:'Candidato',date:'Data da investigação',state:'Estado da investigação',recommendation:'Recomendação',blocker:'Bloqueio principal / incógnita essencial',download:'Descarregar o dossier completo do Gate 1 — PDF',nav:'Secções do candidato',opportunity:'Pontuação de Oportunidade 0–5',confidence:'Confiança da Evidência 0–5',assessment:'Avaliação',missing:'Sem pontuação',scoreNote:'A Pontuação de Oportunidade e a Confiança da Evidência são medidas distintas. A ausência de pontuação não é convertida numa precisão artificial.',demand:'PROCURA DE OPERADORES PARA O ATLAS',level:['Sem contacto','Conversa com operador','NDA / intercâmbio técnico','Manifestação de interesse escrita','LOI','Reserva de capacidade / acordo de desenvolvimento']},
 fi:{dimension:'Osa-alue',levelWord:'TASO',back:'Project Atlas -kohteet',candidate:'Kohde',date:'Tutkimusajankohta',state:'Tutkimuksen tila',recommendation:'Suositus',blocker:'Keskeinen este / avoin kysymys',download:'Lataa koko Gate 1 -tutkimusraportti — PDF',nav:'Kohteen osiot',opportunity:'Mahdollisuuspisteet 0–5',confidence:'Näytön varmuus 0–5',assessment:'Arvio',missing:'Ei pisteytetty',scoreNote:'Mahdollisuuspisteet ja näytön varmuus ovat eri mittareita. Puuttuvaa pisteytystä ei korvata näennäisellä tarkkuudella.',demand:'ATLAKSEN OPERAATTORIKYSYNTÄ',level:['Ei yhteydenottoa','Keskustelu operaattorin kanssa','NDA / tekninen tiedonvaihto','Kirjallinen kiinnostuksenilmaus','LOI','Kapasiteettivaraus / kehityssopimus']},
} as const
const ev:Record<AtlasLocale,Record<AtlasEvidenceStatus,string>>={en:{CONFIRMED:'CONFIRMED','STRONGLY INDICATED':'STRONGLY INDICATED',INDICATED:'INDICATED',UNVERIFIED:'UNVERIFIED',UNKNOWN:'UNKNOWN',BLOCKER:'BLOCKER'},es:{CONFIRMED:'CONFIRMADO','STRONGLY INDICATED':'SÓLIDAMENTE INDICADO',INDICATED:'INDICADO',UNVERIFIED:'NO VERIFICADO',UNKNOWN:'DESCONOCIDO',BLOCKER:'BLOQUEO'},pt:{CONFIRMED:'CONFIRMADO','STRONGLY INDICATED':'FORTEMENTE INDICADO',INDICATED:'INDICADO',UNVERIFIED:'NÃO VERIFICADO',UNKNOWN:'DESCONHECIDO',BLOCKER:'BLOQUEIO'},fi:{CONFIRMED:'VAHVISTETTU','STRONGLY INDICATED':'VAHVA NÄYTTÖ',INDICATED:'VIITTEELLINEN',UNVERIFIED:'VARMISTAMATON',UNKNOWN:'TUNTEMATON',BLOCKER:'ESTE'}}
export function AtlasLocaleProvider({locale,children}:{locale:AtlasLocale;children:React.ReactNode}){useEffect(()=>{document.documentElement.lang=locale;window.dispatchEvent(new CustomEvent('atlas-language-change',{detail:locale}));return()=>{document.documentElement.lang='en';window.dispatchEvent(new CustomEvent('atlas-language-change',{detail:'en'}))}},[locale]);return <LocaleContext.Provider value={locale}>{children}</LocaleContext.Provider>}
export function AtlasLanguageSelector({locale,localCode,onChange,ariaLabel='Choose language'}:{locale:AtlasLocale;localCode:Exclude<AtlasLocale,'en'>;onChange:(locale:AtlasLocale)=>void;ariaLabel?:string}){return <div className="inline-flex rounded-full border border-white/20 bg-white/10 p-1" role="group" aria-label={ariaLabel}>{[localCode,'en'].map(code=><button type="button" key={code} lang={code} aria-pressed={locale===code} onClick={()=>onChange(code as AtlasLocale)} className={`min-h-10 min-w-12 rounded-full px-4 text-xs font-bold uppercase ${locale===code?'bg-white text-zinc-950':'text-zinc-200 hover:bg-white/10'}`}>{code}</button>)}</div>}

const gateLabels:Record<AtlasLocale,Record<AtlasGateStatus,string>>={en:{PASS:'PASS','CONDITIONAL PASS':'CONTINUE VALIDATION','CONTINUE RESEARCHING':'CONTINUE VALIDATION',HOLD:'VALIDATION PAUSED',FAIL:'CLOSED AFTER RESEARCH'},es:{PASS:'APROBADO','CONDITIONAL PASS':'CONTINUAR VALIDACIÓN','CONTINUE RESEARCHING':'CONTINUAR VALIDACIÓN',HOLD:'VALIDACIÓN EN PAUSA',FAIL:'CERRADO TRAS LA INVESTIGACIÓN'},pt:{PASS:'APROVADO','CONDITIONAL PASS':'CONTINUAR VALIDAÇÃO','CONTINUE RESEARCHING':'CONTINUAR VALIDAÇÃO',HOLD:'VALIDAÇÃO EM PAUSA',FAIL:'ENCERRADO APÓS INVESTIGAÇÃO'},fi:{PASS:'HYVÄKSYTTY','CONDITIONAL PASS':'JATKA VALIDOINTIA','CONTINUE RESEARCHING':'JATKA VALIDOINTIA',HOLD:'VALIDOINTI TAUOLLA',FAIL:'SULJETTU TUTKIMUKSEN JÄLKEEN'}}
const gateTone:Record<AtlasGateStatus,string>={PASS:'border-emerald-600/50 bg-emerald-950/50 text-emerald-100','CONDITIONAL PASS':'border-amber-500/50 bg-amber-950/50 text-amber-100','CONTINUE RESEARCHING':'border-sky-500/50 bg-sky-950/50 text-sky-100',HOLD:'border-zinc-500 bg-zinc-800 text-zinc-200',FAIL:'border-red-700/60 bg-red-950/60 text-red-100'}
export function AtlasGateBadge({status}:{status:AtlasGateStatus}){const locale=useContext(LocaleContext);return <span className={`inline-flex rounded-full border px-3 py-1 text-[11px] font-bold tracking-[.1em] ${gateTone[status]}`}>{gateLabels[locale][status]}</span>}
export function AtlasEvidenceBadge({status}:{status:AtlasEvidenceStatus}){const locale=useContext(LocaleContext);const style=status==='BLOCKER'?'border-red-300 bg-red-50 text-red-800':status==='CONFIRMED'?'border-emerald-300 bg-emerald-50 text-emerald-800':status==='UNKNOWN'||status==='UNVERIFIED'?'border-zinc-300 bg-zinc-100 text-zinc-700':'border-amber-300 bg-amber-50 text-amber-900';return <span className={`inline-flex whitespace-nowrap rounded-full border px-2.5 py-1 text-[10px] font-bold tracking-[.1em] ${style}`}>{ev[locale][status]}</span>}
export function AtlasDossierCTA({href,candidate,invert=false}:{href:string;candidate:string;invert?:boolean}){const locale=useContext(LocaleContext);return <a href={href} download className={`inline-flex min-h-12 items-center rounded-full px-6 text-sm font-semibold focus-visible:outline-2 focus-visible:outline-offset-2 ${invert?'bg-white text-zinc-950':'bg-zinc-950 text-white'}`} aria-label={`${ui[locale].download} — ${candidate}`}>{ui[locale].download} — {candidate}</a>}
export function AtlasCandidateHero({languageControl,country,name,id,gate,status,date,researchState,assessment,blocker,dossier}:{country:string;name:string;id:string;gate:string;status:AtlasGateStatus;date:string;researchState:string;assessment:string;blocker:string;dossier:string;languageControl?:React.ReactNode}){const locale=useContext(LocaleContext);const partnerLabel={en:'Discuss investment or partnership',es:'Hablar sobre inversión o colaboración',pt:'Falar sobre investimento ou parceria',fi:'Keskustele sijoituksesta tai kumppanuudesta'}[locale];return <section id="overview" className="scroll-mt-24 bg-zinc-950 text-white"><div className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-24"><Link to="/infrastructure/atlas" className="text-sm text-zinc-400 hover:text-white">← {ui[locale].back}</Link>{languageControl&&<div className="mt-6">{languageControl}</div>}<p className="mt-10 text-xs font-bold tracking-[.25em] text-amber-200">PROJECT ATLAS · {country.toUpperCase()}</p><div className="mt-5 grid gap-10 lg:grid-cols-[1fr_22rem]"><div><h1 className="text-5xl font-semibold tracking-tight md:text-7xl">{name}</h1><p className="mt-6 max-w-4xl text-xl leading-relaxed text-zinc-300">{assessment}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:items-center"><AtlasDossierCTA candidate={name} href={dossier} invert/><Link to="/infrastructure/atlas/partners" className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/30 px-6 text-center text-sm font-semibold">{partnerLabel}</Link></div></div><dl className="grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 text-sm"><HeroMeta label={ui[locale].candidate} value={id}/><HeroMeta label="Gate" value={gate}/><HeroMeta label={ui[locale].date} value={date}/><HeroMeta label={ui[locale].state} value={researchState}/><div className="col-span-2 p-5"><dt className="text-xs text-zinc-400">{ui[locale].recommendation}</dt><dd className="mt-2"><AtlasGateBadge status={status}/></dd></div></dl></div><div className="mt-10 rounded-2xl border border-white/10 bg-white/5 p-6"><p className="text-xs uppercase tracking-wider text-zinc-400">{ui[locale].blocker}</p><p className="mt-2 text-lg font-semibold">{blocker}</p></div></div></section>}
function HeroMeta({label,value}:{label:string;value:string}){return <div className="p-5"><dt className="text-xs text-zinc-400">{label}</dt><dd className="mt-2 font-semibold">{value}</dd></div>}
export function AtlasCandidateNav({items}:{items:{id:string;label:string}[]}){const locale=useContext(LocaleContext);return <nav aria-label={ui[locale].nav} className="sticky top-0 z-30 border-b border-zinc-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl gap-1 overflow-x-auto px-4 py-2">{items.map(item=><SectionLink className="whitespace-nowrap rounded-full px-3 py-2 text-xs font-medium text-zinc-600 focus-visible:outline-2 focus-visible:outline-offset-2 hover:bg-zinc-100 hover:text-zinc-950" id={item.id} key={item.id}>{item.label}</SectionLink>)}</div></nav>}
export function AtlasSection({id,number,eyebrow,title,children,dark=false}:{id?:string;number?:string;eyebrow?:string;title:string;children:React.ReactNode;dark?:boolean}){return <section id={id} tabIndex={id?-1:undefined} className={`scroll-mt-28 border-t ${dark?'border-zinc-800 bg-zinc-950 text-white':'border-zinc-200'}`}><div className="mx-auto max-w-7xl px-5 py-14 md:px-8 md:py-20"><p className={`text-xs font-bold tracking-[.18em] ${dark?'text-zinc-500':'text-zinc-400'}`}>{number}{number&&eyebrow?' · ':''}{eyebrow}</p><h2 className="mt-3 mb-8 text-3xl font-semibold tracking-tight md:text-5xl">{title}</h2>{children}</div></section>}
export function AtlasMetricCard({label,value,note}:{label:string;value:string;note?:string}){return <div className="rounded-2xl border border-zinc-200 p-5"><p className="text-xs uppercase tracking-wider text-zinc-400">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p>{note&&<p className="mt-3 text-sm text-zinc-600">{note}</p>}</div>}
export function AtlasDataTable({headers,rows}:{headers:string[];rows:React.ReactNode[][]}){return <div className="overflow-x-auto rounded-2xl border border-zinc-200"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-zinc-950 text-white"><tr>{headers.map(h=><th scope="col" className="p-4" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr className="border-t border-zinc-200" key={i}>{row.map((cell,j)=>j===0?<th scope="row" className="p-4 align-top font-semibold" key={j}>{cell}</th>:<td className="p-4 align-top text-zinc-600" key={j}>{cell}</td>)}</tr>)}</tbody></table></div>}
export function AtlasScorecard({scores}:{scores:AtlasScore[]}){const locale=useContext(LocaleContext);return <><p className="mb-6 text-sm text-zinc-600">{ui[locale].scoreNote}</p><AtlasDataTable headers={[ui[locale].dimension,ui[locale].opportunity,ui[locale].confidence,ui[locale].assessment]} rows={scores.map(s=>[s.dimension,s.opportunity===undefined?ui[locale].missing:`${s.opportunity} / 5`,s.confidence===undefined?ui[locale].missing:`${s.confidence} / 5`,s.note])}/></>}
export function AtlasWarning({title,children}:{title:string;children:React.ReactNode}){return <div className="border-l-4 border-red-800 bg-red-50 p-6 text-red-950"><p className="text-xl font-bold">{title}</p><div className="mt-2 text-sm leading-relaxed">{children}</div></div>}
export function AtlasDemandLadder({level,note}:{level:number;note:string}){const locale=useContext(LocaleContext);return <><div className="mb-7 rounded-2xl bg-zinc-950 p-6 text-white"><p className="text-xs text-zinc-400">{ui[locale].demand}</p><p className="mt-2 text-3xl font-semibold">{ui[locale].levelWord} {level}</p><p className="mt-3 font-bold text-amber-200">{note}</p></div><div className="grid gap-2 md:grid-cols-6">{ui[locale].level.map((label,i)=><div className={`rounded-xl border p-4 ${i===level?'border-zinc-950 bg-zinc-950 text-white':'border-zinc-200'}`} key={label}><p className="text-xs font-bold">{ui[locale].levelWord} {i}</p><p className="mt-2 text-sm">{label}</p></div>)}</div></>}
export function AtlasDevelopmentPathway({steps}:{steps:string[]}){return <div className="grid gap-2 md:grid-cols-4">{steps.map(step=><div className={`rounded-xl border p-4 text-sm font-semibold ${step.includes('COMPLETE')||step.includes('VALMIS')?'border-emerald-300 bg-emerald-50':step.includes('BLOCKED')||step.includes('ESTYNYT')?'border-red-300 bg-red-50':'border-zinc-200 text-zinc-500'}`} key={step}>{step}</div>)}</div>}
