import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
const origin='https://www.albedo-industries.com'
const pages=[
 ['/', 'ALBEDO Industries — Data Center & AI Infrastructure Development', 'ALBEDO Industries advances early-stage data-center infrastructure through Project Atlas and researches longer-term orbital compute, alongside physical interfaces and operational software.', 'Building the physical layer of AI.', 'ALBEDO Industries is an early-stage company focused primarily on data-center development through Project Atlas. Atlas originates, validates and advances infrastructure opportunities. Albedo Orbital is an early-stage initiative seeking investment and technical partners to research compute beyond the grid, beginning with terrestrial autonomous-compute experiments before any orbital infrastructure. Albedo Display explores persistent physical information interfaces; FastSoftware builds operational systems and human-reviewed AI workflows.'],
 ['/atlas','Project Atlas — Data Center Development & AI Infrastructure','Project Atlas identifies, validates, structures and advances early-stage data center and AI infrastructure opportunities across selected international markets.','From infrastructure opportunity to investable data-center project.','Atlas screens power and grid, land and site-control pathways, fibre and connectivity, cooling and water, planning, permitting, technical diligence, capital requirements and operator requirements. Typical initial phases under evaluation are 10–25 MW, with expansion considered where evidence supports it.'],
 ['/atlas/partners','Data Center Development Capital & Co-Development | Project Atlas','Work with Project Atlas on evidence-led data center development opportunities, development capital, operator requirements and infrastructure co-development.','Data center development capital and co-development','Development-capital providers, principal developers, infrastructure investors, operators, capacity partners, utilities, landowners and public institutions can engage Atlas. Public research establishes context; project-specific evidence and diligence may require an NDA. This website is not a securities offering and does not promise returns.'],
 ['/atlas/research','Data Center Site Research & Infrastructure Due Diligence | Project Atlas','Review Project Atlas research into power, land, fibre, cooling, planning, permitting and execution conditions for early-stage data center sites.','Data center site research and infrastructure diligence','Atlas research tests infrastructure conditions before a candidate becomes a development opportunity. Published research is not evidence that land, grid capacity, permits, financing or customers are secured.'],
 ['/orbital','Albedo Orbital — Orbital Data Centers & Space Compute Research','Albedo Orbital is ALBEDO Industries’ research initiative exploring autonomous compute, orbital data centers, power, thermal management, communications and infrastructure beyond traditional terrestrial grids.','Compute beyond Earth.','Albedo Orbital is a research / pre-development initiative. It maps launch, power, thermal rejection, radiation, communications, autonomy, servicing and economic constraints. ALBEDO is not launching satellites, manufacturing spacecraft or operating a space data center.'],
 ['/orbital/research','Orbital Data Center Research — Technical Bottlenecks | Albedo Orbital','Research into the power, thermal, launch, radiation, communications, autonomy and economic constraints that must be solved for large-scale orbital AI compute and data centers.','What must become true?','ALBEDO Research Note ORB-R01 maps ten coupled constraints for orbital compute. The current model does not establish hyperscale feasibility or economics. Power generation and thermal rejection both scale with area and mass; launch, radiation, communications, autonomy, servicing, regulation and useful hardware life remain open. All public numbers are explicitly scenario assumptions or derived first-order estimates while primary-source verification remains pending.'],
 ['/orbital/experiment-01','Albedo Orbital Experiment 01 — Autonomous Compute Node','A proposed terrestrial and later hosted-orbit test program designed to measure autonomous compute reliability, fault recovery, power management, communications and intervention burden.','Autonomous Compute Node.','Albedo Orbital Experiment 01 is at experiment-design stage. Stage A would test a terrestrial compute node under safe power, thermal, communications and software-fault conditions. Ground hardware is not yet assembled; flight hardware is not designed; no provider is selected and no launch is booked. Stage B is a conditional hosted-orbit concept only if terrestrial evidence earns progression.'],
 ['/display','Albedo Display — Persistent Displays for Data Center Infrastructure','Albedo Display is a pre-prototype persistent physical information interface designed for low-power operation around data-center racks, maintenance and commissioning.','Information that stays visible.','Albedo Display is a proposed persistent operational display for data centers and critical infrastructure. It is digitally updateable, designed for low-power operation, and intended for racks, maintenance, commissioning and infrastructure assets. The engineering architecture and final display technology remain open.'],
 ['/display/invest','Albedo Display Strategic Brief — Data Center Persistent Displays','Strategic partner brief for Albedo Display, a pre-prototype persistent operational display concept for data centers and critical infrastructure.','Validate the infrastructure workflow before scaling the hardware.','Albedo Display is pre-prototype. The strategic brief explains the data-center problem, open technical architecture, pilot strategy, capital uses, manufacturing path and potential commercial models without claiming a finished or available product.'],
 ['/fastsoftware','FastSoftware — Operational Software & AI Systems | ALBEDO Industries','FastSoftware builds focused operational software, internal tools and AI-assisted workflows around real company processes, from procurement and documents to projects and reporting.','Operational software built around real work.','FastSoftware turns manual workflows, disconnected tools and repeated operational work into focused internal systems and human-reviewed AI-assisted processes. Foreman and the Purchasing Agent demonstrate the method.'],
 ['/fastsoftware/purchasing-agent','Purchasing Agent Demo — AI-Assisted Procurement | FastSoftware','A transparent FastSoftware demonstration of supplier-offer comparison, missing-information checks and human-reviewed purchasing decision support.','Purchasing Agent Demo','A working interface demonstration showing how supplier emails, PDFs and spreadsheets can be normalized into an offer comparison. The system prepares structured decision support; people remain responsible for purchasing decisions.'],
 ['/foreman','Foreman — Construction Operations Software | FastSoftware','Foreman is a building-stage construction operations software project covering projects, purchasing context, materials, warehouse and site workflows.','Foreman construction operations software','A building-stage FastSoftware system exploring project visibility, purchasing, suppliers, materials, warehouse and site workflows for construction operations. No customer or deployment count is claimed.'],
 ['/about','About ALBEDO Industries — AI & Data Center Infrastructure','Learn about Project Atlas, Albedo Orbital, Albedo Display and FastSoftware, and ALBEDO Industries’ evidence-led approach to AI infrastructure.','About ALBEDO Industries','ALBEDO is an independent early-stage company founded by Alex Velasco. Project Atlas is the primary initiative; Albedo Orbital is research / pre-development; Albedo Display is pre-prototype; FastSoftware contains systems and demonstrations at different development stages.'],
 ['/infrastructure/spain/el-bierzo','El Bierzo AI Infrastructure Research | Project Atlas','Public Project Atlas research into an early-stage AI infrastructure candidate in El Bierzo, Spain.','El Bierzo infrastructure research','Evidence-labelled public research; no site, capacity, permits or financing are represented as secured.'],
 ['/infrastructure/uruguay/canelones','Canelones AI Infrastructure Research | Project Atlas','Public Project Atlas research into an early-stage AI infrastructure candidate in Canelones, Uruguay.','Canelones infrastructure research','Evidence-labelled public research; no site, capacity, permits or financing are represented as secured.'],
 ['/infrastructure/portugal/sines','Sines AI Infrastructure Research | Project Atlas','Public Project Atlas research into an early-stage AI infrastructure candidate in Sines, Portugal.','Sines infrastructure research','Evidence-labelled public research; no site, capacity, permits or financing are represented as secured.'],
 ['/infrastructure/spain/as-pontes','As Pontes AI Infrastructure Research | Project Atlas','Public Project Atlas research into an early-stage AI infrastructure candidate in As Pontes, Spain.','As Pontes infrastructure research','Evidence-labelled public research; no site, capacity, permits or financing are represented as secured.'],
 ['/infrastructure/spain/as-pontes/research','As Pontes Data Center Research | Project Atlas','Technical and documentary Project Atlas research into infrastructure conditions in As Pontes, Spain.','As Pontes data center research','Research evaluates power, land, connectivity and planning context without implying control.'],
 ['/infrastructure/finland/kouvola-kotka','Kouvola–Kotka AI Infrastructure Research | Project Atlas','Public Project Atlas research into an early-stage AI infrastructure candidate in Finland.','Kouvola–Kotka infrastructure research','Evidence-labelled public research; no site, capacity, permits or financing are represented as secured.'],
]
const template=await readFile('dist/index.html','utf8')
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')
for(const [route,title,description,h1,body] of pages){
 const canonical=origin+(route==='/'?'/':route); const graphItems=[{'@type':'WebPage',url:canonical,name:title,description},{'@type':'BreadcrumbList',itemListElement:route==='/'?[]:[{'@type':'ListItem',position:1,name:'ALBEDO Industries',item:origin+'/'},{'@type':'ListItem',position:2,name:h1,item:canonical}]}]; if(route==='/')graphItems.unshift({'@type':'Organization',name:'ALBEDO Industries',url:origin+'/',logo:origin+'/favicon.svg',description,founder:{'@type':'Person',name:'Alex Velasco'}},{'@type':'WebSite',name:'ALBEDO Industries',url:origin+'/'}); const graph={'@context':'https://schema.org','@graph':graphItems}
 let html=template.replace(/<title>.*?<\/title>/s,`<title>${esc(title)}</title>`).replace(/<meta name="description" content="[^"]*"\s*\/>/,`<meta name="description" content="${esc(description)}" />`).replace(/<link rel="canonical" href="[^"]*"\s*\/>/,`<link rel="canonical" href="${canonical}" />`).replace(/<meta property="og:title" content="[^"]*"\s*\/>/,`<meta property="og:title" content="${esc(title)}" />`).replace(/<meta property="og:description" content="[^"]*"\s*\/>/,`<meta property="og:description" content="${esc(description)}" />`).replace(/<meta property="og:url" content="[^"]*"\s*\/>/,`<meta property="og:url" content="${canonical}" />`).replace('</head>',`<script type="application/ld+json" data-site-structured-data>${JSON.stringify(graph).replaceAll('<','\\u003c')}</script></head>`).replace('<div id="root"></div>',`<div id="root"><main id="prerendered-content"><article><h1>${esc(h1)}</h1><p>${esc(body)}</p><nav aria-label="Related pages"><a href="/atlas">Project Atlas overview</a> · <a href="/atlas/partners">Development capital and co-development</a> · <a href="/atlas/research">Research and validation</a> · <a href="/orbital">Albedo Orbital</a> · <a href="/orbital/research">Orbital technical research</a> · <a href="/orbital/experiment-01">Orbital Experiment 01</a> · <a href="/display">Albedo Display</a> · <a href="/fastsoftware">FastSoftware</a> · <a href="/about">About ALBEDO Industries</a></nav></article></main></div>`)
 if(route.startsWith('/orbital')) html=html.replaceAll(origin+'/albedo-social.svg',origin+'/orbital-social.svg')
 const output=route==='/'?'dist/index.html':join('dist',route.slice(1),'index.html'); await mkdir(dirname(output),{recursive:true}); await writeFile(output,html)
}
const aliases = { '/infrastructure': '/atlas', '/infrastructure/europe': '/atlas', '/infrastructure/atlas': '/atlas', '/infrastructure/atlas/partners': '/atlas/partners', '/infrastructure/funding': '/atlas/partners', '/infrastructure/atlas/research': '/atlas/research' }
for (const [route, target] of Object.entries(aliases)) {
  const output=join('dist',route.slice(1),'index.html'); await mkdir(dirname(output),{recursive:true})
  await writeFile(output, `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="robots" content="noindex, follow"><link rel="canonical" href="${origin}${target}"><meta http-equiv="refresh" content="0;url=${target}"><title>Redirecting — ALBEDO Industries</title></head><body><p><a href="${target}">Continue to the canonical page</a></p><script>location.replace('${target}'+location.search+location.hash)</script></body></html>`)
}
const urls=pages.map(([route])=>`  <url><loc>${origin}${route==='/'?'/':route}</loc></url>`).join('\n')
await writeFile('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`)
await copyFile('public/404.html','dist/404.html')
console.log(`Prerendered ${pages.length} canonical public routes.`)
