import { useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
const email='alex@albedo-industries.com'
type Fields={name:string;email:string;organisation:string;workflow:string;environment:string;website:string}
const empty:Fields={name:'',email:'',organisation:'',workflow:'',environment:'',website:''}
export default function DisplayPilotForm(){const [fields,setFields]=useState(empty);const [state,setState]=useState<'idle'|'sending'|'sent'|'fallback'>('idle');const [error,setError]=useState('');const set=(key:keyof Fields,value:string)=>setFields(x=>({...x,[key]:value}));const mailto=`mailto:${email}?subject=${encodeURIComponent(`Albedo Display pilot — ${fields.organisation||fields.name}`)}&body=${encodeURIComponent(`Name: ${fields.name}\nEmail: ${fields.email}\nOrganisation: ${fields.organisation}\nEnvironment: ${fields.environment}\nWorkflow: ${fields.workflow}`)}`;async function submit(event:FormEvent){event.preventDefault();if(fields.website)return;if(!fields.name.trim()||!/^\S+@\S+\.\S+$/.test(fields.email)||!fields.organisation.trim()||!fields.workflow.trim()){setError('Complete your name, work email, organisation and proposed workflow.');return}setError('');const endpoint=import.meta.env.VITE_DISPLAY_PILOT_ENDPOINT as string|undefined;if(!endpoint){setState('fallback');return}setState('sending');try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,website:undefined})});if(!response.ok)throw new Error();setState('sent');setFields(empty)}catch{setState('fallback')}}
if(state==='sent')return <div className="border border-zinc-300 p-6" role="status"><h3 className="text-xl font-semibold">Pilot enquiry received.</h3><p className="mt-3 text-sm text-zinc-600">ALBEDO will review the workflow and respond by email.</p></div>
return <form onSubmit={submit} noValidate className="grid gap-5 border-t border-zinc-300 pt-6 sm:grid-cols-2"><div className="hidden" aria-hidden="true"><label>Website<input tabIndex={-1} value={fields.website} onChange={e=>set('website',e.target.value)}/></label></div>{error&&<p className="border-l-2 border-red-700 pl-3 text-sm text-red-800 sm:col-span-2" role="alert">{error}</p>}{state==='fallback'&&<p className="border-l-2 border-amber-500 pl-3 text-sm sm:col-span-2" role="status">The online form is not connected. <a className="underline" href={mailto}>Open a pre-filled email instead.</a></p>}<Field label="Name"><input className="mt-2 min-h-12 w-full border border-zinc-300 px-3" autoComplete="name" value={fields.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="Work email"><input className="mt-2 min-h-12 w-full border border-zinc-300 px-3" type="email" autoComplete="email" value={fields.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="Organisation"><input className="mt-2 min-h-12 w-full border border-zinc-300 px-3" autoComplete="organization" value={fields.organisation} onChange={e=>set('organisation',e.target.value)}/></Field><Field label="Physical environment"><input className="mt-2 min-h-12 w-full border border-zinc-300 px-3" placeholder="Data hall, commissioning area…" value={fields.environment} onChange={e=>set('environment',e.target.value)}/></Field><label className="text-sm font-semibold sm:col-span-2">One operational workflow<textarea className="mt-2 w-full border border-zinc-300 p-3" rows={4} placeholder="What information changes, where should it remain visible, and who updates it?" value={fields.workflow} onChange={e=>set('workflow',e.target.value)}/></label><div className="flex flex-col gap-4 sm:col-span-2 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-md text-xs text-zinc-500">Details are used to respond to this enquiry. Read the <Link className="underline" to="/privacy">privacy notice</Link>.</p><button disabled={state==='sending'} className="min-h-12 bg-zinc-950 px-6 text-sm font-semibold text-white">{state==='sending'?'Sending…':'Discuss a pilot'}</button></div></form>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-sm font-semibold">{label}{children}</label>}
